// SPDX-License-Identifier: CC-BY-SA-4.0
//
// Autogenerated by plan44 FontHexer2 pixel font generator

// This is a font file to be included from textview.cpp to define a font

// Original font outline (vector) version (c) 2015 VileR - Creative Commons Attribution-ShareAlike 4.0 International

#ifdef GENERATE_FONT_SOURCE

// MARK: - 'bios' generated font verification data

static const char * font_bios_glyphstrings[] = {
  " " /* UTF-8 20 - Glyph 0 */

  "\n"   "........"  
  "\n"   "........"  
  "\n"   "........"  
  "\n"   "........"  
  "\n"   "........"  
  "\n"   "........" ,

  "!" /* UTF-8 21 - Glyph 1 */

  "\n"   "........"  
  "\n"   ".....XX."  
  "\n"   ".X.XXXXX"  
  "\n"   ".X.XXXXX"  
  "\n"   ".....XX." ,

  "\"" /* UTF-8 22 - Glyph 2 */

  "\n"   "........"  
  "\n"   ".....XXX"  
  "\n"   ".....XXX"  
  "\n"   "........"  
  "\n"   ".....XXX"  
  "\n"   ".....XXX" ,

  "#" /* UTF-8 23 - Glyph 3 */

  "\n"   "...X.X.."  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   "...X.X.."  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   "...X.X.." ,

  "$" /* UTF-8 24 - Glyph 4 */

  "\n"   "..X..X.."  
  "\n"   "..X.XXX."  
  "\n"   ".XX.X.XX"  
  "\n"   ".XX.X.XX"  
  "\n"   "..XXX.X."  
  "\n"   "...X..X." ,

  "%" /* UTF-8 25 - Glyph 5 */

  "\n"   ".X...XX."  
  "\n"   ".XX..XX."  
  "\n"   "..XX...."  
  "\n"   "...XX..."  
  "\n"   "....XX.."  
  "\n"   ".XX..XX."  
  "\n"   ".XX...X." ,

  "&" /* UTF-8 26 - Glyph 6 */

  "\n"   "..XX...."  
  "\n"   ".XXXX.X."  
  "\n"   ".X..XXXX"  
  "\n"   ".X.XXX.X"  
  "\n"   "..XX.XXX"  
  "\n"   ".XXXX.X."  
  "\n"   ".X..X..." ,

  "'" /* UTF-8 27 - Glyph 7 */

  "\n"   ".....X.."  
  "\n"   ".....XXX"  
  "\n"   "......XX" ,

  "(" /* UTF-8 28 - Glyph 8 */

  "\n"   "........"  
  "\n"   "...XXX.."  
  "\n"   "..XXXXX."  
  "\n"   ".XX...XX"  
  "\n"   ".X.....X" ,

  ")" /* UTF-8 29 - Glyph 9 */

  "\n"   "........"  
  "\n"   ".X.....X"  
  "\n"   ".XX...XX"  
  "\n"   "..XXXXX."  
  "\n"   "...XXX.." ,

  "*" /* UTF-8 2A - Glyph 10 */

  "\n"   "....X..."  
  "\n"   "..X.X.X."  
  "\n"   "..XXXXX."  
  "\n"   "...XXX.."  
  "\n"   "...XXX.."  
  "\n"   "..XXXXX."  
  "\n"   "..X.X.X."  
  "\n"   "....X..." ,

  "+" /* UTF-8 2B - Glyph 11 */

  "\n"   "....X..."  
  "\n"   "....X..."  
  "\n"   "..XXXXX."  
  "\n"   "..XXXXX."  
  "\n"   "....X..."  
  "\n"   "....X..." ,

  "," /* UTF-8 2C - Glyph 12 */

  "\n"   "........"  
  "\n"   "X......."  
  "\n"   "XXX....."  
  "\n"   ".XX....." ,

  "-" /* UTF-8 2D - Glyph 13 */

  "\n"   "....X..."  
  "\n"   "....X..."  
  "\n"   "....X..."  
  "\n"   "....X..."  
  "\n"   "....X..."  
  "\n"   "....X..." ,

  "." /* UTF-8 2E - Glyph 14 */

  "\n"   "........"  
  "\n"   "........"  
  "\n"   ".XX....."  
  "\n"   ".XX....." ,

  "/" /* UTF-8 2F - Glyph 15 */

  "\n"   ".XX....."  
  "\n"   "..XX...."  
  "\n"   "...XX..."  
  "\n"   "....XX.."  
  "\n"   ".....XX."  
  "\n"   "......XX"  
  "\n"   ".......X" ,

  "0" /* UTF-8 30 - Glyph 16 */

  "\n"   "..XXXXX."  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXX...X"  
  "\n"   ".X.XX..X"  
  "\n"   ".X..XX.X"  
  "\n"   ".XXXXXXX"  
  "\n"   "..XXXXX." ,

  "1" /* UTF-8 31 - Glyph 17 */

  "\n"   ".X......"  
  "\n"   ".X....X."  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X......"  
  "\n"   ".X......" ,

  "2" /* UTF-8 32 - Glyph 18 */

  "\n"   ".XX...X."  
  "\n"   ".XXX..XX"  
  "\n"   ".X.XX..X"  
  "\n"   ".X..X..X"  
  "\n"   ".X..XXXX"  
  "\n"   ".XX..XX." ,

  "3" /* UTF-8 33 - Glyph 19 */

  "\n"   "..X...X."  
  "\n"   ".XX...XX"  
  "\n"   ".X..X..X"  
  "\n"   ".X..X..X"  
  "\n"   ".XXXXXXX"  
  "\n"   "..XX.XX." ,

  "4" /* UTF-8 34 - Glyph 20 */

  "\n"   "...XX..."  
  "\n"   "...XXX.."  
  "\n"   "...X.XX."  
  "\n"   ".X.X..XX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X.X...." ,

  "5" /* UTF-8 35 - Glyph 21 */

  "\n"   "..X..XXX"  
  "\n"   ".XX..XXX"  
  "\n"   ".X...X.X"  
  "\n"   ".X...X.X"  
  "\n"   ".XXXXX.X"  
  "\n"   "..XXX..X" ,

  "6" /* UTF-8 36 - Glyph 22 */

  "\n"   "..XXXX.."  
  "\n"   ".XXXXXX."  
  "\n"   ".X..X.XX"  
  "\n"   ".X..X..X"  
  "\n"   ".XXXX..X"  
  "\n"   "..XX...." ,

  "7" /* UTF-8 37 - Glyph 23 */

  "\n"   "......XX"  
  "\n"   "......XX"  
  "\n"   ".XXX...X"  
  "\n"   ".XXXX..X"  
  "\n"   "....XXXX"  
  "\n"   ".....XXX" ,

  "8" /* UTF-8 38 - Glyph 24 */

  "\n"   "..XX.XX."  
  "\n"   ".XXXXXXX"  
  "\n"   ".X..X..X"  
  "\n"   ".X..X..X"  
  "\n"   ".XXXXXXX"  
  "\n"   "..XX.XX." ,

  "9" /* UTF-8 39 - Glyph 25 */

  "\n"   ".....XX."  
  "\n"   ".X..XXXX"  
  "\n"   ".X..X..X"  
  "\n"   ".XX.X..X"  
  "\n"   "..XXXXXX"  
  "\n"   "...XXXX." ,

  ":" /* UTF-8 3A - Glyph 26 */

  "\n"   "........"  
  "\n"   "........"  
  "\n"   ".XX..XX."  
  "\n"   ".XX..XX." ,

  ";" /* UTF-8 3B - Glyph 27 */

  "\n"   "........"  
  "\n"   ".X......"  
  "\n"   ".XXX.XX."  
  "\n"   "..XX.XX." ,

  "<" /* UTF-8 3C - Glyph 28 */

  "\n"   "....X..."  
  "\n"   "...XXX.."  
  "\n"   "..XX.XX."  
  "\n"   ".XX...XX"  
  "\n"   ".X.....X" ,

  "=" /* UTF-8 3D - Glyph 29 */

  "\n"   "..X..X.."  
  "\n"   "..X..X.."  
  "\n"   "..X..X.."  
  "\n"   "..X..X.."  
  "\n"   "..X..X.."  
  "\n"   "..X..X.." ,

  ">" /* UTF-8 3E - Glyph 30 */

  "\n"   "........"  
  "\n"   ".X.....X"  
  "\n"   ".XX...XX"  
  "\n"   "..XX.XX."  
  "\n"   "...XXX.."  
  "\n"   "....X..." ,

  "?" /* UTF-8 3F - Glyph 31 */

  "\n"   "......X."  
  "\n"   "......XX"  
  "\n"   ".X.X...X"  
  "\n"   ".X.XX..X"  
  "\n"   "....XXXX"  
  "\n"   ".....XX." ,

  "@" /* UTF-8 40 - Glyph 32 */

  "\n"   "..XXXXX."  
  "\n"   ".XXXXXXX"  
  "\n"   ".X.....X"  
  "\n"   ".X.XXX.X"  
  "\n"   ".X.XXX.X"  
  "\n"   "...XXXXX"  
  "\n"   "...XXXX." ,

  "A" /* UTF-8 41 - Glyph 33 */

  "\n"   ".XXXXX.."  
  "\n"   ".XXXXXX."  
  "\n"   "...X..XX"  
  "\n"   "...X..XX"  
  "\n"   ".XXXXXX."  
  "\n"   ".XXXXX.." ,

  "À" /* UTF-8 C3 80 - Glyph 34 */

  "\n"   ".XXXX..X"  
  "\n"   ".XXXXX.X"  
  "\n"   "...X.XX."  
  "\n"   "...X..X."  
  "\n"   "...X.XX."  
  "\n"   ".XXXXX.."  
  "\n"   ".XXXX..." ,

  "Á" /* UTF-8 C3 81 - Glyph 35 */

  "\n"   ".XXXX..."  
  "\n"   ".XXXXX.."  
  "\n"   "...X.XX."  
  "\n"   "...X..X."  
  "\n"   "...X.XX."  
  "\n"   ".XXXXX.X"  
  "\n"   ".XXXX..X" ,

  "Â" /* UTF-8 C3 82 - Glyph 36 */

  "\n"   ".XXX..X."  
  "\n"   ".XXXX.XX"  
  "\n"   "..X.XX.X"  
  "\n"   "..X..X.X"  
  "\n"   "..X.XX.X"  
  "\n"   ".XXXX.XX"  
  "\n"   ".XXX..X." ,

  "Ä" /* UTF-8 C3 84 - Glyph 37 */

  "\n"   ".XXXX..X"  
  "\n"   ".XXXXX.X"  
  "\n"   "...X.XX."  
  "\n"   "...X..X."  
  "\n"   "...X.XX."  
  "\n"   ".XXXXX.X"  
  "\n"   ".XXXX..X" ,

  "B" /* UTF-8 42 - Glyph 38 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X..X..X"  
  "\n"   ".X..X..X"  
  "\n"   ".XXXXXXX"  
  "\n"   "..XX.XX." ,

  "C" /* UTF-8 43 - Glyph 39 */

  "\n"   "...XXX.."  
  "\n"   "..XXXXX."  
  "\n"   ".XX...XX"  
  "\n"   ".X.....X"  
  "\n"   ".X.....X"  
  "\n"   ".XX...XX"  
  "\n"   "..X...X." ,

  "D" /* UTF-8 44 - Glyph 40 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X.....X"  
  "\n"   ".XX...XX"  
  "\n"   "..XXXXX."  
  "\n"   "...XXX.." ,

  "E" /* UTF-8 45 - Glyph 41 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X..X..X"  
  "\n"   ".X.XXX.X"  
  "\n"   ".X.....X"  
  "\n"   ".XX...XX" ,

  "È" /* UTF-8 C3 88 - Glyph 42 */

  "\n"   ".X...X.X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".X.X.X.."  
  "\n"   ".X.X.X.."  
  "\n"   ".X...X.." ,

  "É" /* UTF-8 C3 89 - Glyph 43 */

  "\n"   ".X...X.."  
  "\n"   ".XXXXX.."  
  "\n"   ".XXXXX.."  
  "\n"   ".X.X.X.X"  
  "\n"   ".X.X.X.X"  
  "\n"   ".X...X.X" ,

  "Ê" /* UTF-8 C3 8A - Glyph 44 */

  "\n"   ".X...XX."  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXX.X"  
  "\n"   ".X.X.X.X"  
  "\n"   ".X.X.XXX"  
  "\n"   ".X...XX." ,

  "F" /* UTF-8 46 - Glyph 45 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X..X..X"  
  "\n"   "...XXX.X"  
  "\n"   ".......X"  
  "\n"   "......XX" ,

  "G" /* UTF-8 47 - Glyph 46 */

  "\n"   "...XXX.."  
  "\n"   "..XXXXX."  
  "\n"   ".XX...XX"  
  "\n"   ".X.....X"  
  "\n"   ".X.X...X"  
  "\n"   ".XXX..XX"  
  "\n"   ".XXX..X." ,

  "H" /* UTF-8 48 - Glyph 47 */

  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   "....X..."  
  "\n"   "....X..."  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX" ,

  "I" /* UTF-8 49 - Glyph 48 */

  "\n"   "........"  
  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X.....X" ,

  "J" /* UTF-8 4A - Glyph 49 */

  "\n"   "..XX...."  
  "\n"   ".XXX...."  
  "\n"   ".X......"  
  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   "..XXXXXX"  
  "\n"   ".......X" ,

  "K" /* UTF-8 4B - Glyph 50 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   "....X..."  
  "\n"   "...XXX.."  
  "\n"   ".XXX.XXX"  
  "\n"   ".XX...XX" ,

  "L" /* UTF-8 4C - Glyph 51 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X.....X"  
  "\n"   ".X......"  
  "\n"   ".XX....."  
  "\n"   ".XXX...." ,

  "M" /* UTF-8 4D - Glyph 52 */

  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   "....XXX."  
  "\n"   "...XXX.."  
  "\n"   "....XXX."  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX" ,

  "N" /* UTF-8 4E - Glyph 53 */

  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".....XX."  
  "\n"   "....XX.."  
  "\n"   "...XX..."  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX" ,

  "O" /* UTF-8 4F - Glyph 54 */

  "\n"   "...XXX.."  
  "\n"   "..XXXXX."  
  "\n"   ".XX...XX"  
  "\n"   ".X.....X"  
  "\n"   ".XX...XX"  
  "\n"   "..XXXXX."  
  "\n"   "...XXX.." ,

  "Ö" /* UTF-8 C3 96 - Glyph 55 */

  "\n"   ".......X"  
  "\n"   "...XX..X"  
  "\n"   "..XXXX.."  
  "\n"   ".XX..XX."  
  "\n"   ".XX..XX."  
  "\n"   "..XXXX.."  
  "\n"   "...XX..X"  
  "\n"   ".......X" ,

  "P" /* UTF-8 50 - Glyph 56 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X..X..X"  
  "\n"   "....X..X"  
  "\n"   "....XXXX"  
  "\n"   ".....XX." ,

  "Q" /* UTF-8 51 - Glyph 57 */

  "\n"   "...XXXX."  
  "\n"   "..XXXXXX"  
  "\n"   "..X....X"  
  "\n"   ".XXX...X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X.XXXX." ,

  "R" /* UTF-8 52 - Glyph 58 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   "....X..X"  
  "\n"   "...XX..X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XX..XX." ,

  "S" /* UTF-8 53 - Glyph 59 */

  "\n"   "..X..XX."  
  "\n"   ".XX.XXXX"  
  "\n"   ".X..XX.X"  
  "\n"   ".X.XX..X"  
  "\n"   ".XXX..XX"  
  "\n"   "..XX..X." ,

  "T" /* UTF-8 54 - Glyph 60 */

  "\n"   "......XX"  
  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X.....X"  
  "\n"   "......XX" ,

  "U" /* UTF-8 55 - Glyph 61 */

  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X......"  
  "\n"   ".X......"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX" ,

  "Ü" /* UTF-8 C3 9C - Glyph 62 */

  "\n"   "..XXXX.X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".X......"  
  "\n"   ".X......"  
  "\n"   ".XXXXX.X"  
  "\n"   "..XXXX.X" ,

  "V" /* UTF-8 56 - Glyph 63 */

  "\n"   "...XXXXX"  
  "\n"   "..XXXXXX"  
  "\n"   ".XX....."  
  "\n"   ".XX....."  
  "\n"   "..XXXXXX"  
  "\n"   "...XXXXX" ,

  "W" /* UTF-8 57 - Glyph 64 */

  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   "..XX...."  
  "\n"   "...XX..."  
  "\n"   "..XX...."  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX" ,

  "X" /* UTF-8 58 - Glyph 65 */

  "\n"   ".X....XX"  
  "\n"   ".XX..XXX"  
  "\n"   "..XXXX.."  
  "\n"   "...XX..."  
  "\n"   "..XXXX.."  
  "\n"   ".XX..XXX"  
  "\n"   ".X....XX" ,

  "Y" /* UTF-8 59 - Glyph 66 */

  "\n"   ".....XXX"  
  "\n"   ".X..XXXX"  
  "\n"   ".XXXX..."  
  "\n"   ".XXXX..."  
  "\n"   ".X..XXXX"  
  "\n"   ".....XXX" ,

  "Z" /* UTF-8 5A - Glyph 67 */

  "\n"   ".X...XXX"  
  "\n"   ".XX...XX"  
  "\n"   ".XXX...X"  
  "\n"   ".X.XX..X"  
  "\n"   ".X..XX.X"  
  "\n"   ".XX..XXX"  
  "\n"   ".XXX..XX" ,

  "[" /* UTF-8 5B - Glyph 68 */

  "\n"   "........"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X.....X"  
  "\n"   ".X.....X" ,

  "\\" /* UTF-8 5C - Glyph 69 */

  "\n"   ".......X"  
  "\n"   "......XX"  
  "\n"   ".....XX."  
  "\n"   "....XX.."  
  "\n"   "...XX..."  
  "\n"   "..XX...."  
  "\n"   ".XX....." ,

  "]" /* UTF-8 5D - Glyph 70 */

  "\n"   "........"  
  "\n"   ".X.....X"  
  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX" ,

  "^" /* UTF-8 5E - Glyph 71 */

  "\n"   "....X..."  
  "\n"   "....XX.."  
  "\n"   ".....XX."  
  "\n"   "......XX"  
  "\n"   ".....XX."  
  "\n"   "....XX.."  
  "\n"   "....X..." ,

  "_" /* UTF-8 5F - Glyph 72 */

  "\n"   "X......."  
  "\n"   "X......."  
  "\n"   "X......."  
  "\n"   "X......."  
  "\n"   "X......."  
  "\n"   "X......."  
  "\n"   "X......."  
  "\n"   "X......." ,

  "`" /* UTF-8 60 - Glyph 73 */

  "\n"   "........"  
  "\n"   "........"  
  "\n"   "......XX"  
  "\n"   ".....XXX"  
  "\n"   ".....X.." ,

  "a" /* UTF-8 61 - Glyph 74 */

  "\n"   "..X....."  
  "\n"   ".XXX.X.."  
  "\n"   ".X.X.X.."  
  "\n"   ".X.X.X.."  
  "\n"   "..XXXX.."  
  "\n"   ".XXXX..."  
  "\n"   ".X......" ,

  "à" /* UTF-8 C3 A0 - Glyph 75 */

  "\n"   "..X....X"  
  "\n"   ".XXX.X.X"  
  "\n"   ".X.X.X.X"  
  "\n"   ".X.X.X.."  
  "\n"   ".XXXXX.."  
  "\n"   ".XXXX..."  
  "\n"   ".X......" ,

  "á" /* UTF-8 C3 A1 - Glyph 76 */

  "\n"   "..X....."  
  "\n"   ".XXX.X.."  
  "\n"   ".X.X.X.."  
  "\n"   ".X.X.X.X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".XXXX..X"  
  "\n"   ".X......" ,

  "â" /* UTF-8 C3 A2 - Glyph 77 */

  "\n"   "......X."  
  "\n"   "..X...XX"  
  "\n"   ".XXX.X.X"  
  "\n"   ".X.X.X.X"  
  "\n"   ".X.X.X.X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".XXXX.XX"  
  "\n"   ".X....X." ,

  "ä" /* UTF-8 C3 A4 - Glyph 78 */

  "\n"   "..X....X"  
  "\n"   ".XXX.X.X"  
  "\n"   ".X.X.X.."  
  "\n"   ".X.X.X.."  
  "\n"   ".XXXXX.X"  
  "\n"   ".XXXX..X"  
  "\n"   ".X......" ,

  "b" /* UTF-8 62 - Glyph 79 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   "..XXXXXX"  
  "\n"   ".X..X..."  
  "\n"   ".X..X..."  
  "\n"   ".XXXX..."  
  "\n"   "..XX...." ,

  "c" /* UTF-8 63 - Glyph 80 */

  "\n"   "..XXX..."  
  "\n"   ".XXXXX.."  
  "\n"   ".X...X.."  
  "\n"   ".X...X.."  
  "\n"   ".XX.XX.."  
  "\n"   "..X.X..." ,

  "ç" /* UTF-8 C3 A7 - Glyph 81 */

  "\n"   "...XX..."  
  "\n"   "..XXXX.."  
  "\n"   "X.X..X.."  
  "\n"   "X.X..X.."  
  "\n"   "XXX..X.."  
  "\n"   ".X......" ,

  "d" /* UTF-8 64 - Glyph 82 */

  "\n"   "..XX...."  
  "\n"   ".XXXX..."  
  "\n"   ".X..X..."  
  "\n"   ".X..X..X"  
  "\n"   "..XXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X......" ,

  "e" /* UTF-8 65 - Glyph 83 */

  "\n"   "..XXX..."  
  "\n"   ".XXXXX.."  
  "\n"   ".X.X.X.."  
  "\n"   ".X.X.X.."  
  "\n"   ".X.XXX.."  
  "\n"   "...XX..." ,

  "è" /* UTF-8 C3 A8 - Glyph 84 */

  "\n"   "..XXX..X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".X.X.X.X"  
  "\n"   ".X.X.X.."  
  "\n"   ".X.XXX.."  
  "\n"   "...XX..." ,

  "é" /* UTF-8 C3 A9 - Glyph 85 */

  "\n"   "..XXX..."  
  "\n"   ".XXXXX.."  
  "\n"   ".X.X.X.."  
  "\n"   ".X.X.X.X"  
  "\n"   ".X.XXX.X"  
  "\n"   "...XX..X" ,

  "ê" /* UTF-8 C3 AA - Glyph 86 */

  "\n"   "......X."  
  "\n"   "..XXX.XX"  
  "\n"   ".XXXXX.X"  
  "\n"   ".X.X.X.X"  
  "\n"   ".X.X.X.X"  
  "\n"   ".X.XXX.X"  
  "\n"   "...XX.XX"  
  "\n"   "......X." ,

  "ë" /* UTF-8 C3 AB - Glyph 87 */

  "\n"   "..XXX..X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".X.X.X.."  
  "\n"   ".X.X.X.."  
  "\n"   ".X.XXX.X"  
  "\n"   "...XX..X" ,

  "f" /* UTF-8 66 - Glyph 88 */

  "\n"   ".X..X..."  
  "\n"   ".XXXXXX."  
  "\n"   ".XXXXXXX"  
  "\n"   ".X..X..X"  
  "\n"   "......XX"  
  "\n"   "......X." ,

  "g" /* UTF-8 67 - Glyph 89 */

  "\n"   "X..XX..."  
  "\n"   "X.XXXX.."  
  "\n"   "X.X..X.."  
  "\n"   "X.X..X.."  
  "\n"   "XXXXX..."  
  "\n"   ".XXXXX.."  
  "\n"   ".....X.." ,

  "h" /* UTF-8 68 - Glyph 90 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   "....X..."  
  "\n"   ".....X.."  
  "\n"   ".XXXXX.."  
  "\n"   ".XXXX..." ,

  "i" /* UTF-8 69 - Glyph 91 */

  "\n"   "........"  
  "\n"   ".X...X.."  
  "\n"   ".XXXXX.X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".X......" ,

  "ì" /* UTF-8 C3 AC - Glyph 92 */

  "\n"   ".......X"  
  "\n"   ".X...X.X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".XXXXX.."  
  "\n"   ".X......" ,

  "í" /* UTF-8 C3 AD - Glyph 93 */

  "\n"   "........"  
  "\n"   ".X...X.."  
  "\n"   ".XXXXX.X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".X.....X" ,

  "î" /* UTF-8 C3 AE - Glyph 94 */

  "\n"   "......X."  
  "\n"   "......XX"  
  "\n"   ".X...X.X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".XXXXX.X"  
  "\n"   ".X....XX"  
  "\n"   "......X." ,

  "ï" /* UTF-8 C3 AF - Glyph 95 */

  "\n"   ".......X"  
  "\n"   ".X...X.X"  
  "\n"   ".XXXXX.."  
  "\n"   ".XXXXX.."  
  "\n"   ".X.....X"  
  "\n"   ".......X" ,

  "j" /* UTF-8 6A - Glyph 96 */

  "\n"   ".XX....."  
  "\n"   "XXX....."  
  "\n"   "X......."  
  "\n"   "X......."  
  "\n"   "XXXXXX.X"  
  "\n"   ".XXXXX.X" ,

  "k" /* UTF-8 6B - Glyph 97 */

  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   "...X...."  
  "\n"   "..XXX..."  
  "\n"   ".XX.XX.."  
  "\n"   ".X...X.." ,

  "l" /* UTF-8 6C - Glyph 98 */

  "\n"   "........"  
  "\n"   ".X.....X"  
  "\n"   ".XXXXXXX"  
  "\n"   ".XXXXXXX"  
  "\n"   ".X......" ,

  "m" /* UTF-8 6D - Glyph 99 */

  "\n"   ".XXXXX.."  
  "\n"   ".XXXXX.."  
  "\n"   "...XX..."  
  "\n"   "..XXX..."  
  "\n"   "...XXX.."  
  "\n"   ".XXXXX.."  
  "\n"   ".XXXX..." ,

  "n" /* UTF-8 6E - Glyph 100 */

  "\n"   ".XXXXX.."  
  "\n"   ".XXXXX.."  
  "\n"   ".....X.."  
  "\n"   ".....X.."  
  "\n"   ".XXXXX.."  
  "\n"   ".XXXX..." ,

  "o" /* UTF-8 6F - Glyph 101 */

  "\n"   "..XXX..."  
  "\n"   ".XXXXX.."  
  "\n"   ".X...X.."  
  "\n"   ".X...X.."  
  "\n"   ".XXXXX.."  
  "\n"   "..XXX..." ,

  "ö" /* UTF-8 C3 B6 - Glyph 102 */

  "\n"   "..XX..X."  
  "\n"   ".XXXX.X."  
  "\n"   ".X..X..."  
  "\n"   ".X..X..."  
  "\n"   ".XXXX.X."  
  "\n"   "..XX..X." ,

  "p" /* UTF-8 70 - Glyph 103 */

  "\n"   "X....X.."  
  "\n"   "XXXXXX.."  
  "\n"   "XXXXX..."  
  "\n"   "X.X..X.."  
  "\n"   "..X..X.."  
  "\n"   "..XXXX.."  
  "\n"   "...XX..." ,

  "placeholder" /* UTF-8 70 6C 61 63 65 68 6F 6C 64 65 72 - Glyph 104 */

  "\n"   "XXXXXXXX"  
  "\n"   "X......X"  
  "\n"   "X......X"  
  "\n"   "X......X"  
  "\n"   "X......X"  
  "\n"   "XXXXXXXX" ,

  "q" /* UTF-8 71 - Glyph 105 */

  "\n"   "...XX..."  
  "\n"   "..XXXX.."  
  "\n"   "..X..X.."  
  "\n"   "X.X..X.."  
  "\n"   "XXXXX..."  
  "\n"   "XXXXXX.."  
  "\n"   "X....X.." ,

  "r" /* UTF-8 72 - Glyph 106 */

  "\n"   ".X...X.."  
  "\n"   ".XXXXX.."  
  "\n"   ".XXXX..."  
  "\n"   ".X..XX.."  
  "\n"   ".....X.."  
  "\n"   "...XXX.."  
  "\n"   "...XX..." ,

  "s" /* UTF-8 73 - Glyph 107 */

  "\n"   ".X..X..."  
  "\n"   ".X.XXX.."  
  "\n"   ".X.X.X.."  
  "\n"   ".X.X.X.."  
  "\n"   ".XXX.X.."  
  "\n"   "..X..X.." ,

  "t" /* UTF-8 74 - Glyph 108 */

  "\n"   "........"  
  "\n"   ".....X.."  
  "\n"   "..XXXXX."  
  "\n"   ".XXXXXXX"  
  "\n"   ".X...X.."  
  "\n"   "..X..X.." ,

  "u" /* UTF-8 75 - Glyph 109 */

  "\n"   "..XXXX.."  
  "\n"   ".XXXXX.."  
  "\n"   ".X......"  
  "\n"   ".X......"  
  "\n"   "..XXXX.."  
  "\n"   ".XXXXX.."  
  "\n"   ".X......" ,

  "ü" /* UTF-8 C3 BC - Glyph 110 */

  "\n"   "..XXX.X."  
  "\n"   ".XXXX.X."  
  "\n"   ".X......"  
  "\n"   ".X......"  
  "\n"   ".XXXX.X."  
  "\n"   ".XXXX.X."  
  "\n"   ".X......" ,

  "v" /* UTF-8 76 - Glyph 111 */

  "\n"   "...XXX.."  
  "\n"   "..XXXX.."  
  "\n"   ".XX....."  
  "\n"   ".XX....."  
  "\n"   "..XXXX.."  
  "\n"   "...XXX.." ,

  "w" /* UTF-8 77 - Glyph 112 */

  "\n"   "..XXXX.."  
  "\n"   ".XXXXX.."  
  "\n"   ".XXX...."  
  "\n"   "..XXX..."  
  "\n"   ".XXX...."  
  "\n"   ".XXXXX.."  
  "\n"   "..XXXX.." ,

  "x" /* UTF-8 78 - Glyph 113 */

  "\n"   ".X...X.."  
  "\n"   ".XX.XX.."  
  "\n"   "..XXX..."  
  "\n"   "...X...."  
  "\n"   "..XXX..."  
  "\n"   ".XX.XX.."  
  "\n"   ".X...X.." ,

  "y" /* UTF-8 79 - Glyph 114 */

  "\n"   "X..XXX.."  
  "\n"   "X.XXXX.."  
  "\n"   "X.X....."  
  "\n"   "X.X....."  
  "\n"   "XXXXXX.."  
  "\n"   ".XXXXX.." ,

  "z" /* UTF-8 7A - Glyph 115 */

  "\n"   ".X..XX.."  
  "\n"   ".XX..X.."  
  "\n"   ".XXX.X.."  
  "\n"   ".X.XXX.."  
  "\n"   ".X..XX.."  
  "\n"   ".XX..X.." ,

  "{" /* UTF-8 7B - Glyph 116 */

  "\n"   "....X..."  
  "\n"   "....X..."  
  "\n"   "..XXXXX."  
  "\n"   ".XXX.XXX"  
  "\n"   ".X.....X"  
  "\n"   ".X.....X" ,

  "|" /* UTF-8 7C - Glyph 117 */

  "\n"   "........"  
  "\n"   "........"  
  "\n"   "........"  
  "\n"   ".XXX.XXX"  
  "\n"   ".XXX.XXX" ,

  "}" /* UTF-8 7D - Glyph 118 */

  "\n"   ".X.....X"  
  "\n"   ".X.....X"  
  "\n"   ".XXX.XXX"  
  "\n"   "..XXXXX."  
  "\n"   "....X..."  
  "\n"   "....X..." ,

  "~" /* UTF-8 7E - Glyph 119 */

  "\n"   "......X."  
  "\n"   "......XX"  
  "\n"   ".......X"  
  "\n"   "......XX"  
  "\n"   "......X."  
  "\n"   "......XX"  
  "\n"   ".......X" ,

  "–" /* UTF-8 E2 80 93 - Glyph 120 */

  "\n"   "........"  
  "\n"   "....X..."  
  "\n"   "....X..."  
  "\n"   "....X..."  
  "\n"   "....X..."  
  "\n"   "....X..." ,

  "’" /* UTF-8 E2 80 99 - Glyph 121 */

  "\n"   "........"  
  "\n"   ".....X.."  
  "\n"   ".....XXX"  
  "\n"   "......XX" ,

  "•" /* UTF-8 E2 80 A2 - Glyph 122 */

  "\n"   "........"  
  "\n"   "........"  
  "\n"   "...XX..."  
  "\n"   "..XXXX.."  
  "\n"   "..XXXX.."  
  "\n"   "...XX..." ,

  nullptr // terminator
};

// MARK: - end of generated font verification data


#endif // GENERATE_FONT_SOURCE


// MARK: - 'bios' generated font data

static const glyph_t font_bios_glyphs[] = {
  {  6, "\xff\x81\x81\x81\x81\xff"                 },  // placeholder          (input # 6 -> glyph # 0)
  {  6, "\x00\x00\x00\x00\x00\x00"                 },  // ' ' UTF-8 20         (input # 49 -> glyph # 1)
  {  5, "\x00\x06\x5f\x5f\x06"                     },  // '!' UTF-8 21         (input # 52 -> glyph # 2)
  {  6, "\x00\x07\x07\x00\x07\x07"                 },  // '"' UTF-8 22         (input # 55 -> glyph # 3)
  {  7, "\x14\x7f\x7f\x14\x7f\x7f\x14"             },  // '#' UTF-8 23         (input # 58 -> glyph # 4)
  {  6, "\x24\x2e\x6b\x6b\x3a\x12"                 },  // '$' UTF-8 24         (input # 60 -> glyph # 5)
  {  7, "\x46\x66\x30\x18\x0c\x66\x62"             },  // '%' UTF-8 25         (input # 62 -> glyph # 6)
  {  7, "\x30\x7a\x4f\x5d\x37\x7a\x48"             },  // '&' UTF-8 26         (input # 64 -> glyph # 7)
  {  3, "\x04\x07\x03"                             },  // ''' UTF-8 27         (input # 66 -> glyph # 8)
  {  5, "\x00\x1c\x3e\x63\x41"                     },  // '(' UTF-8 28         (input # 68 -> glyph # 9)
  {  5, "\x00\x41\x63\x3e\x1c"                     },  // ')' UTF-8 29         (input # 70 -> glyph # 10)
  {  8, "\x08\x2a\x3e\x1c\x1c\x3e\x2a\x08"         },  // '*' UTF-8 2A         (input # 72 -> glyph # 11)
  {  6, "\x08\x08\x3e\x3e\x08\x08"                 },  // '+' UTF-8 2B         (input # 74 -> glyph # 12)
  {  4, "\x00\x80\xe0\x60"                         },  // ',' UTF-8 2C         (input # 75 -> glyph # 13)
  {  6, "\x08\x08\x08\x08\x08\x08"                 },  // '-' UTF-8 2D         (input # 76 -> glyph # 14)
  {  4, "\x00\x00\x60\x60"                         },  // '.' UTF-8 2E         (input # 77 -> glyph # 15)
  {  7, "\x60\x30\x18\x0c\x06\x03\x01"             },  // '/' UTF-8 2F         (input # 79 -> glyph # 16)
  {  7, "\x3e\x7f\x71\x59\x4d\x7f\x3e"             },  // '0' UTF-8 30         (input # 80 -> glyph # 17)
  {  6, "\x40\x42\x7f\x7f\x40\x40"                 },  // '1' UTF-8 31         (input # 81 -> glyph # 18)
  {  6, "\x62\x73\x59\x49\x4f\x66"                 },  // '2' UTF-8 32         (input # 82 -> glyph # 19)
  {  6, "\x22\x63\x49\x49\x7f\x36"                 },  // '3' UTF-8 33         (input # 83 -> glyph # 20)
  {  7, "\x18\x1c\x16\x53\x7f\x7f\x50"             },  // '4' UTF-8 34         (input # 84 -> glyph # 21)
  {  6, "\x27\x67\x45\x45\x7d\x39"                 },  // '5' UTF-8 35         (input # 86 -> glyph # 22)
  {  6, "\x3c\x7e\x4b\x49\x79\x30"                 },  // '6' UTF-8 36         (input # 87 -> glyph # 23)
  {  6, "\x03\x03\x71\x79\x0f\x07"                 },  // '7' UTF-8 37         (input # 88 -> glyph # 24)
  {  6, "\x36\x7f\x49\x49\x7f\x36"                 },  // '8' UTF-8 38         (input # 89 -> glyph # 25)
  {  6, "\x06\x4f\x49\x69\x3f\x1e"                 },  // '9' UTF-8 39         (input # 91 -> glyph # 26)
  {  4, "\x00\x00\x66\x66"                         },  // ':' UTF-8 3A         (input # 93 -> glyph # 27)
  {  4, "\x00\x40\x76\x36"                         },  // ';' UTF-8 3B         (input # 95 -> glyph # 28)
  {  5, "\x08\x1c\x36\x63\x41"                     },  // '<' UTF-8 3C         (input # 96 -> glyph # 29)
  {  6, "\x24\x24\x24\x24\x24\x24"                 },  // '=' UTF-8 3D         (input # 98 -> glyph # 30)
  {  6, "\x00\x41\x63\x36\x1c\x08"                 },  // '>' UTF-8 3E         (input # 99 -> glyph # 31)
  {  6, "\x02\x03\x51\x59\x0f\x06"                 },  // '?' UTF-8 3F         (input # 100 -> glyph # 32)
  {  7, "\x3e\x7f\x41\x5d\x5d\x1f\x1e"             },  // '@' UTF-8 40         (input # 102 -> glyph # 33)
  {  6, "\x7c\x7e\x13\x13\x7e\x7c"                 },  // 'A' UTF-8 41         (input # 104 -> glyph # 34)
  {  7, "\x41\x7f\x7f\x49\x49\x7f\x36"             },  // 'B' UTF-8 42         (input # 106 -> glyph # 35)
  {  7, "\x1c\x3e\x63\x41\x41\x63\x22"             },  // 'C' UTF-8 43         (input # 108 -> glyph # 36)
  {  7, "\x41\x7f\x7f\x41\x63\x3e\x1c"             },  // 'D' UTF-8 44         (input # 110 -> glyph # 37)
  {  7, "\x41\x7f\x7f\x49\x5d\x41\x63"             },  // 'E' UTF-8 45         (input # 112 -> glyph # 38)
  {  7, "\x41\x7f\x7f\x49\x1d\x01\x03"             },  // 'F' UTF-8 46         (input # 114 -> glyph # 39)
  {  7, "\x1c\x3e\x63\x41\x51\x73\x72"             },  // 'G' UTF-8 47         (input # 116 -> glyph # 40)
  {  6, "\x7f\x7f\x08\x08\x7f\x7f"                 },  // 'H' UTF-8 48         (input # 118 -> glyph # 41)
  {  5, "\x00\x41\x7f\x7f\x41"                     },  // 'I' UTF-8 49         (input # 119 -> glyph # 42)
  {  7, "\x30\x70\x40\x41\x7f\x3f\x01"             },  // 'J' UTF-8 4A         (input # 120 -> glyph # 43)
  {  7, "\x41\x7f\x7f\x08\x1c\x77\x63"             },  // 'K' UTF-8 4B         (input # 121 -> glyph # 44)
  {  7, "\x41\x7f\x7f\x41\x40\x60\x70"             },  // 'L' UTF-8 4C         (input # 122 -> glyph # 45)
  {  7, "\x7f\x7f\x0e\x1c\x0e\x7f\x7f"             },  // 'M' UTF-8 4D         (input # 123 -> glyph # 46)
  {  7, "\x7f\x7f\x06\x0c\x18\x7f\x7f"             },  // 'N' UTF-8 4E         (input # 1 -> glyph # 47)
  {  7, "\x1c\x3e\x63\x41\x63\x3e\x1c"             },  // 'O' UTF-8 4F         (input # 3 -> glyph # 48)
  {  7, "\x41\x7f\x7f\x49\x09\x0f\x06"             },  // 'P' UTF-8 50         (input # 4 -> glyph # 49)
  {  6, "\x1e\x3f\x21\x71\x7f\x5e"                 },  // 'Q' UTF-8 51         (input # 5 -> glyph # 50)
  {  7, "\x41\x7f\x7f\x09\x19\x7f\x66"             },  // 'R' UTF-8 52         (input # 7 -> glyph # 51)
  {  6, "\x26\x6f\x4d\x59\x73\x32"                 },  // 'S' UTF-8 53         (input # 8 -> glyph # 52)
  {  6, "\x03\x41\x7f\x7f\x41\x03"                 },  // 'T' UTF-8 54         (input # 9 -> glyph # 53)
  {  6, "\x7f\x7f\x40\x40\x7f\x7f"                 },  // 'U' UTF-8 55         (input # 11 -> glyph # 54)
  {  6, "\x1f\x3f\x60\x60\x3f\x1f"                 },  // 'V' UTF-8 56         (input # 12 -> glyph # 55)
  {  7, "\x7f\x7f\x30\x18\x30\x7f\x7f"             },  // 'W' UTF-8 57         (input # 13 -> glyph # 56)
  {  7, "\x43\x67\x3c\x18\x3c\x67\x43"             },  // 'X' UTF-8 58         (input # 14 -> glyph # 57)
  {  6, "\x07\x4f\x78\x78\x4f\x07"                 },  // 'Y' UTF-8 59         (input # 15 -> glyph # 58)
  {  7, "\x47\x63\x71\x59\x4d\x67\x73"             },  // 'Z' UTF-8 5A         (input # 16 -> glyph # 59)
  {  5, "\x00\x7f\x7f\x41\x41"                     },  // '[' UTF-8 5B         (input # 17 -> glyph # 60)
  {  7, "\x01\x03\x06\x0c\x18\x30\x60"             },  // '\' UTF-8 5C         (input # 18 -> glyph # 61)
  {  5, "\x00\x41\x41\x7f\x7f"                     },  // ']' UTF-8 5D         (input # 19 -> glyph # 62)
  {  7, "\x08\x0c\x06\x03\x06\x0c\x08"             },  // '^' UTF-8 5E         (input # 20 -> glyph # 63)
  {  8, "\x80\x80\x80\x80\x80\x80\x80\x80"         },  // '_' UTF-8 5F         (input # 21 -> glyph # 64)
  {  5, "\x00\x00\x03\x07\x04"                     },  // '`' UTF-8 60         (input # 23 -> glyph # 65)
  {  7, "\x20\x74\x54\x54\x3c\x78\x40"             },  // 'a' UTF-8 61         (input # 24 -> glyph # 66)
  {  7, "\x41\x7f\x3f\x48\x48\x78\x30"             },  // 'b' UTF-8 62         (input # 25 -> glyph # 67)
  {  6, "\x38\x7c\x44\x44\x6c\x28"                 },  // 'c' UTF-8 63         (input # 26 -> glyph # 68)
  {  7, "\x30\x78\x48\x49\x3f\x7f\x40"             },  // 'd' UTF-8 64         (input # 27 -> glyph # 69)
  {  6, "\x38\x7c\x54\x54\x5c\x18"                 },  // 'e' UTF-8 65         (input # 28 -> glyph # 70)
  {  6, "\x48\x7e\x7f\x49\x03\x02"                 },  // 'f' UTF-8 66         (input # 30 -> glyph # 71)
  {  7, "\x98\xbc\xa4\xa4\xf8\x7c\x04"             },  // 'g' UTF-8 67         (input # 31 -> glyph # 72)
  {  7, "\x41\x7f\x7f\x08\x04\x7c\x78"             },  // 'h' UTF-8 68         (input # 32 -> glyph # 73)
  {  5, "\x00\x44\x7d\x7d\x40"                     },  // 'i' UTF-8 69         (input # 33 -> glyph # 74)
  {  6, "\x60\xe0\x80\x80\xfd\x7d"                 },  // 'j' UTF-8 6A         (input # 34 -> glyph # 75)
  {  7, "\x41\x7f\x7f\x10\x38\x6c\x44"             },  // 'k' UTF-8 6B         (input # 35 -> glyph # 76)
  {  5, "\x00\x41\x7f\x7f\x40"                     },  // 'l' UTF-8 6C         (input # 36 -> glyph # 77)
  {  7, "\x7c\x7c\x18\x38\x1c\x7c\x78"             },  // 'm' UTF-8 6D         (input # 38 -> glyph # 78)
  {  6, "\x7c\x7c\x04\x04\x7c\x78"                 },  // 'n' UTF-8 6E         (input # 40 -> glyph # 79)
  {  6, "\x38\x7c\x44\x44\x7c\x38"                 },  // 'o' UTF-8 6F         (input # 43 -> glyph # 80)
  {  7, "\x84\xfc\xf8\xa4\x24\x3c\x18"             },  // 'p' UTF-8 70         (input # 44 -> glyph # 81)
  {  7, "\x18\x3c\x24\xa4\xf8\xfc\x84"             },  // 'q' UTF-8 71         (input # 46 -> glyph # 82)
  {  7, "\x44\x7c\x78\x4c\x04\x1c\x18"             },  // 'r' UTF-8 72         (input # 47 -> glyph # 83)
  {  6, "\x48\x5c\x54\x54\x74\x24"                 },  // 's' UTF-8 73         (input # 48 -> glyph # 84)
  {  6, "\x00\x04\x3e\x7f\x44\x24"                 },  // 't' UTF-8 74         (input # 50 -> glyph # 85)
  {  7, "\x3c\x7c\x40\x40\x3c\x7c\x40"             },  // 'u' UTF-8 75         (input # 53 -> glyph # 86)
  {  6, "\x1c\x3c\x60\x60\x3c\x1c"                 },  // 'v' UTF-8 76         (input # 56 -> glyph # 87)
  {  7, "\x3c\x7c\x70\x38\x70\x7c\x3c"             },  // 'w' UTF-8 77         (input # 59 -> glyph # 88)
  {  7, "\x44\x6c\x38\x10\x38\x6c\x44"             },  // 'x' UTF-8 78         (input # 61 -> glyph # 89)
  {  6, "\x9c\xbc\xa0\xa0\xfc\x7c"                 },  // 'y' UTF-8 79         (input # 63 -> glyph # 90)
  {  6, "\x4c\x64\x74\x5c\x4c\x64"                 },  // 'z' UTF-8 7A         (input # 65 -> glyph # 91)
  {  6, "\x08\x08\x3e\x77\x41\x41"                 },  // '{' UTF-8 7B         (input # 67 -> glyph # 92)
  {  5, "\x00\x00\x00\x77\x77"                     },  // '|' UTF-8 7C         (input # 69 -> glyph # 93)
  {  6, "\x41\x41\x77\x3e\x08\x08"                 },  // '}' UTF-8 7D         (input # 71 -> glyph # 94)
  {  7, "\x02\x03\x01\x03\x02\x03\x01"             },  // '~' UTF-8 7E         (input # 73 -> glyph # 95)
  {  7, "\x79\x7d\x16\x12\x16\x7c\x78"             },  // 'À' UTF-8 C3 80     (input # 37 -> glyph # 96)
  {  7, "\x78\x7c\x16\x12\x16\x7d\x79"             },  // 'Á' UTF-8 C3 81     (input # 39 -> glyph # 97)
  {  7, "\x72\x7b\x2d\x25\x2d\x7b\x72"             },  // 'Â' UTF-8 C3 82     (input # 41 -> glyph # 98)
  {  7, "\x79\x7d\x16\x12\x16\x7d\x79"             },  // 'Ä' UTF-8 C3 84     (input # 45 -> glyph # 99)
  {  6, "\x45\x7d\x7d\x54\x54\x44"                 },  // 'È' UTF-8 C3 88     (input # 51 -> glyph # 100)
  {  6, "\x44\x7c\x7c\x55\x55\x45"                 },  // 'É' UTF-8 C3 89     (input # 54 -> glyph # 101)
  {  6, "\x46\x7f\x7d\x55\x57\x46"                 },  // 'Ê' UTF-8 C3 8A     (input # 57 -> glyph # 102)
  {  8, "\x01\x19\x3c\x66\x66\x3c\x19\x01"         },  // 'Ö' UTF-8 C3 96     (input # 78 -> glyph # 103)
  {  6, "\x3d\x7d\x40\x40\x7d\x3d"                 },  // 'Ü' UTF-8 C3 9C     (input # 85 -> glyph # 104)
  {  7, "\x21\x75\x55\x54\x7c\x78\x40"             },  // 'à' UTF-8 C3 A0     (input # 90 -> glyph # 105)
  {  7, "\x20\x74\x54\x55\x7d\x79\x40"             },  // 'á' UTF-8 C3 A1     (input # 92 -> glyph # 106)
  {  8, "\x02\x23\x75\x55\x55\x7d\x7b\x42"         },  // 'â' UTF-8 C3 A2     (input # 94 -> glyph # 107)
  {  7, "\x21\x75\x54\x54\x7d\x79\x40"             },  // 'ä' UTF-8 C3 A4     (input # 97 -> glyph # 108)
  {  6, "\x18\x3c\xa4\xa4\xe4\x40"                 },  // 'ç' UTF-8 C3 A7     (input # 101 -> glyph # 109)
  {  6, "\x39\x7d\x55\x54\x5c\x18"                 },  // 'è' UTF-8 C3 A8     (input # 103 -> glyph # 110)
  {  6, "\x38\x7c\x54\x55\x5d\x19"                 },  // 'é' UTF-8 C3 A9     (input # 105 -> glyph # 111)
  {  8, "\x02\x3b\x7d\x55\x55\x5d\x1b\x02"         },  // 'ê' UTF-8 C3 AA     (input # 107 -> glyph # 112)
  {  6, "\x39\x7d\x54\x54\x5d\x19"                 },  // 'ë' UTF-8 C3 AB     (input # 109 -> glyph # 113)
  {  5, "\x01\x45\x7d\x7c\x40"                     },  // 'ì' UTF-8 C3 AC     (input # 111 -> glyph # 114)
  {  5, "\x00\x44\x7d\x7d\x41"                     },  // 'í' UTF-8 C3 AD     (input # 113 -> glyph # 115)
  {  7, "\x02\x03\x45\x7d\x7d\x43\x02"             },  // 'î' UTF-8 C3 AE     (input # 115 -> glyph # 116)
  {  6, "\x01\x45\x7c\x7c\x41\x01"                 },  // 'ï' UTF-8 C3 AF     (input # 117 -> glyph # 117)
  {  6, "\x32\x7a\x48\x48\x7a\x32"                 },  // 'ö' UTF-8 C3 B6     (input # 2 -> glyph # 118)
  {  7, "\x3a\x7a\x40\x40\x7a\x7a\x40"             },  // 'ü' UTF-8 C3 BC     (input # 10 -> glyph # 119)
  {  6, "\x00\x08\x08\x08\x08\x08"                 },  // '–' UTF-8 E2 80 93 (input # 22 -> glyph # 120)
  {  4, "\x00\x04\x07\x03"                         },  // '’' UTF-8 E2 80 99 (input # 29 -> glyph # 121)
  {  6, "\x00\x00\x18\x3c\x3c\x18"                 },  // '•' UTF-8 E2 80 A2 (input # 42 -> glyph # 122)
};

static const GlyphRange font_bios_ranges[] = {
  { "", 0x20, 0x7E, 1 }, //  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
  { "\xc3", 0x80, 0x82, 96 }, // ÀÁÂ
  { "\xc3", 0x84, 0x84, 99 }, // Ä
  { "\xc3", 0x88, 0x8A, 100 }, // ÈÉÊ
  { "\xc3", 0x96, 0x96, 103 }, // Ö
  { "\xc3", 0x9C, 0x9C, 104 }, // Ü
  { "\xc3", 0xA0, 0xA2, 105 }, // àáâ
  { "\xc3", 0xA4, 0xA4, 108 }, // ä
  { "\xc3", 0xA7, 0xAF, 109 }, // çèéêëìíîï
  { "\xc3", 0xB6, 0xB6, 118 }, // ö
  { "\xc3", 0xBC, 0xBC, 119 }, // ü
  { "\xe2\x80", 0x93, 0x93, 120 }, // –
  { "\xe2\x80", 0x99, 0x99, 121 }, // ’
  { "\xe2\x80", 0xA2, 0xA2, 122 }, // •
  { NULL, 0, 0, 0 }
};

static const font_t font_bios = {
  .fontName = "bios",
  .glyphHeight = 8,
  .numGlyphs = 123,
  .glyphRanges = font_bios_ranges,
  .glyphs = font_bios_glyphs
};

// MARK: - end of generated font data

