//  SPDX-License-Identifier: GPL-3.0-or-later
//
//  Autogenerated by p44lrgraphics font generator
//
//  You should have received a copy of the GNU General Public License
//  along with p44lrgraphics. If not, see <http://www.gnu.org/licenses/>.
//

//  Include this file into a p44lrgraphics build to define a built-in font

#include "fonts.hpp"

using namespace p44;

#ifdef GENERATE_FONT_SOURCE

// MARK: - '5x7' generated font verification data

static const char * font_5x7_copyright = nullptr;

static const char * font_5x7_glyphstrings[] = {
  "placeholder" /* 0x00 - Glyph 0 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "X.....X"   // 41
  "\n"   "X.....X"   // 41
  "\n"   "X.....X"   // 41
  "\n"   "XXXXXXX" , // 7F

  " " /* UTF-8 20 - Glyph 1 */

  "\n"   "......."   // 00
  "\n"   "......."   // 00
  "\n"   "......."   // 00
  "\n"   "......."   // 00
  "\n"   "......." , // 00

  "!" /* UTF-8 21 - Glyph 2 */

  "\n"   "X.XXXXX" , // 5F

  "\"" /* UTF-8 22 - Glyph 3 */

  "\n"   ".....XX"   // 03
  "\n"   "......."   // 00
  "\n"   ".....XX" , // 03

  "#" /* UTF-8 23 - Glyph 4 */

  "\n"   ".X.X..."   // 28
  "\n"   "XXXXX.."   // 7C
  "\n"   ".X.X..."   // 28
  "\n"   "XXXXX.."   // 7C
  "\n"   ".X.X..." , // 28

  "$" /* UTF-8 24 - Glyph 5 */

  "\n"   ".X..X.."   // 24
  "\n"   ".X.X.X."   // 2A
  "\n"   "XXXXXXX"   // 7F
  "\n"   ".X.X.X."   // 2A
  "\n"   "..X..X." , // 12

  "%" /* UTF-8 25 - Glyph 6 */

  "\n"   "X..XX.."   // 4C
  "\n"   ".X.XX.."   // 2C
  "\n"   "..X...."   // 10
  "\n"   "XX.X..."   // 68
  "\n"   "XX..X.." , // 64

  "&" /* UTF-8 26 - Glyph 7 */

  "\n"   ".XX...."   // 30
  "\n"   "X..XXX."   // 4E
  "\n"   "X.X.X.X"   // 55
  "\n"   ".X...X."   // 22
  "\n"   "X......" , // 40

  "'" /* UTF-8 27 - Glyph 8 */

  "\n"   ".....XX" , // 03

  "(" /* UTF-8 28 - Glyph 9 */

  "\n"   "..XXX.."   // 1C
  "\n"   ".X...X."   // 22
  "\n"   "X.....X" , // 41

  ")" /* UTF-8 29 - Glyph 10 */

  "\n"   "X.....X"   // 41
  "\n"   ".X...X."   // 22
  "\n"   "..XXX.." , // 1C

  "*" /* UTF-8 2A - Glyph 11 */

  "\n"   "..X.X.."   // 14
  "\n"   "...X..."   // 08
  "\n"   ".XXXXX."   // 3E
  "\n"   "...X..."   // 08
  "\n"   "..X.X.." , // 14

  "+" /* UTF-8 2B - Glyph 12 */

  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   ".XXXXX."   // 3E
  "\n"   "...X..."   // 08
  "\n"   "...X..." , // 08

  "," /* UTF-8 2C - Glyph 13 */

  "\n"   "X.X...."   // 50
  "\n"   ".XX...." , // 30

  "-" /* UTF-8 2D - Glyph 14 */

  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "...X..." , // 08

  "." /* UTF-8 2E - Glyph 15 */

  "\n"   "XX....."   // 60
  "\n"   "XX....." , // 60

  "/" /* UTF-8 2F - Glyph 16 */

  "\n"   "X......"   // 40
  "\n"   ".X....."   // 20
  "\n"   "..X...."   // 10
  "\n"   "...X..."   // 08
  "\n"   "....X.."   // 04
  "\n"   ".....X." , // 02

  "0" /* UTF-8 30 - Glyph 17 */

  "\n"   ".XXXXX."   // 3E
  "\n"   "X.X...X"   // 51
  "\n"   "X..X..X"   // 49
  "\n"   "X...X.X"   // 45
  "\n"   ".XXXXX." , // 3E

  "1" /* UTF-8 31 - Glyph 18 */

  "\n"   "X....X."   // 42
  "\n"   "XXXXXXX"   // 7F
  "\n"   "X......" , // 40

  "2" /* UTF-8 32 - Glyph 19 */

  "\n"   "XX...X."   // 62
  "\n"   "X.X...X"   // 51
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   "X...XX." , // 46

  "3" /* UTF-8 33 - Glyph 20 */

  "\n"   ".X...X."   // 22
  "\n"   "X.....X"   // 41
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   ".XX.XX." , // 36

  "4" /* UTF-8 34 - Glyph 21 */

  "\n"   "..XXX.."   // 1C
  "\n"   "..X..X."   // 12
  "\n"   "..X...X"   // 11
  "\n"   "XXXXXXX"   // 7F
  "\n"   "..X...." , // 10

  "5" /* UTF-8 35 - Glyph 22 */

  "\n"   "X..XXXX"   // 4F
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   ".XX...X" , // 31

  "6" /* UTF-8 36 - Glyph 23 */

  "\n"   ".XXXXX."   // 3E
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   ".XX..X." , // 32

  "7" /* UTF-8 37 - Glyph 24 */

  "\n"   ".....XX"   // 03
  "\n"   "......X"   // 01
  "\n"   "XXX...X"   // 71
  "\n"   "...X..X"   // 09
  "\n"   "....XXX" , // 07

  "8" /* UTF-8 38 - Glyph 25 */

  "\n"   ".XX.XX."   // 36
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   ".XX.XX." , // 36

  "9" /* UTF-8 39 - Glyph 26 */

  "\n"   ".X..XX."   // 26
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   ".XXXXX." , // 3E

  ":" /* UTF-8 3A - Glyph 27 */

  "\n"   "XX..XX."   // 66
  "\n"   "XX..XX." , // 66

  ";" /* UTF-8 3B - Glyph 28 */

  "\n"   "X.X.XX."   // 56
  "\n"   ".XX.XX." , // 36

  "<" /* UTF-8 3C - Glyph 29 */

  "\n"   "...X..."   // 08
  "\n"   "..X.X.."   // 14
  "\n"   ".X...X."   // 22
  "\n"   "X.....X" , // 41

  "=" /* UTF-8 3D - Glyph 30 */

  "\n"   "..X.X.."   // 14
  "\n"   "..X.X.."   // 14
  "\n"   "..X.X.."   // 14
  "\n"   "..X.X.." , // 14

  ">" /* UTF-8 3E - Glyph 31 */

  "\n"   "X.....X"   // 41
  "\n"   ".X...X."   // 22
  "\n"   "..X.X.."   // 14
  "\n"   "...X..." , // 08

  "?" /* UTF-8 3F - Glyph 32 */

  "\n"   ".....X."   // 02
  "\n"   "......X"   // 01
  "\n"   "X.XX..X"   // 59
  "\n"   "...X..X"   // 09
  "\n"   "....XX." , // 06

  "@" /* UTF-8 40 - Glyph 33 */

  "\n"   ".XXXXX."   // 3E
  "\n"   "X.....X"   // 41
  "\n"   "X.XXX.X"   // 5D
  "\n"   "X.X.X.X"   // 55
  "\n"   "X.XXXX." , // 5E

  "A" /* UTF-8 41 - Glyph 34 */

  "\n"   "XXXXX.."   // 7C
  "\n"   "...X.X."   // 0A
  "\n"   "...X..X"   // 09
  "\n"   "...X.X."   // 0A
  "\n"   "XXXXX.." , // 7C

  "B" /* UTF-8 42 - Glyph 35 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   ".XX.XX." , // 36

  "C" /* UTF-8 43 - Glyph 36 */

  "\n"   ".XXXXX."   // 3E
  "\n"   "X.....X"   // 41
  "\n"   "X.....X"   // 41
  "\n"   "X.....X"   // 41
  "\n"   ".X...X." , // 22

  "D" /* UTF-8 44 - Glyph 37 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "X.....X"   // 41
  "\n"   "X.....X"   // 41
  "\n"   ".X...X."   // 22
  "\n"   "..XXX.." , // 1C

  "E" /* UTF-8 45 - Glyph 38 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   "X.....X"   // 41
  "\n"   "X.....X" , // 41

  "F" /* UTF-8 46 - Glyph 39 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "...X..X"   // 09
  "\n"   "...X..X"   // 09
  "\n"   "......X"   // 01
  "\n"   "......X" , // 01

  "G" /* UTF-8 47 - Glyph 40 */

  "\n"   ".XXXXX."   // 3E
  "\n"   "X.....X"   // 41
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   "XXXX.X." , // 7A

  "H" /* UTF-8 48 - Glyph 41 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "XXXXXXX" , // 7F

  "I" /* UTF-8 49 - Glyph 42 */

  "\n"   "X.....X"   // 41
  "\n"   "XXXXXXX"   // 7F
  "\n"   "X.....X" , // 41

  "J" /* UTF-8 4A - Glyph 43 */

  "\n"   ".XX...."   // 30
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   ".XXXXXX" , // 3F

  "K" /* UTF-8 4B - Glyph 44 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "...X..."   // 08
  "\n"   "...XX.."   // 0C
  "\n"   "..X..X."   // 12
  "\n"   "XX....X" , // 61

  "L" /* UTF-8 4C - Glyph 45 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "X......" , // 40

  "M" /* UTF-8 4D - Glyph 46 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   ".....X."   // 02
  "\n"   "....X.."   // 04
  "\n"   "...XX.."   // 0C
  "\n"   "....X.."   // 04
  "\n"   ".....X."   // 02
  "\n"   "XXXXXXX" , // 7F

  "N" /* UTF-8 4E - Glyph 47 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   ".....X."   // 02
  "\n"   "....X.."   // 04
  "\n"   "...X..."   // 08
  "\n"   "XXXXXXX" , // 7F

  "O" /* UTF-8 4F - Glyph 48 */

  "\n"   ".XXXXX."   // 3E
  "\n"   "X.....X"   // 41
  "\n"   "X.....X"   // 41
  "\n"   "X.....X"   // 41
  "\n"   ".XXXXX." , // 3E

  "P" /* UTF-8 50 - Glyph 49 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "...X..X"   // 09
  "\n"   "...X..X"   // 09
  "\n"   "...X..X"   // 09
  "\n"   "....XX." , // 06

  "Q" /* UTF-8 51 - Glyph 50 */

  "\n"   ".XXXXX."   // 3E
  "\n"   "X.....X"   // 41
  "\n"   "X.X...X"   // 51
  "\n"   "XX....X"   // 61
  "\n"   "XXXXXX." , // 7E

  "R" /* UTF-8 52 - Glyph 51 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "...X..X"   // 09
  "\n"   "...X..X"   // 09
  "\n"   "...X..X"   // 09
  "\n"   "XXX.XX." , // 76

  "S" /* UTF-8 53 - Glyph 52 */

  "\n"   ".X..XX."   // 26
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   "X..X..X"   // 49
  "\n"   ".XX..X." , // 32

  "T" /* UTF-8 54 - Glyph 53 */

  "\n"   "......X"   // 01
  "\n"   "......X"   // 01
  "\n"   "XXXXXXX"   // 7F
  "\n"   "......X"   // 01
  "\n"   "......X" , // 01

  "U" /* UTF-8 55 - Glyph 54 */

  "\n"   ".XXXXXX"   // 3F
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   ".XXXXXX" , // 3F

  "V" /* UTF-8 56 - Glyph 55 */

  "\n"   "..XXXXX"   // 1F
  "\n"   ".X....."   // 20
  "\n"   "X......"   // 40
  "\n"   ".X....."   // 20
  "\n"   "..XXXXX" , // 1F

  "W" /* UTF-8 57 - Glyph 56 */

  "\n"   "...XXXX"   // 0F
  "\n"   ".XX...."   // 30
  "\n"   "X......"   // 40
  "\n"   ".XX...."   // 30
  "\n"   "...XX.."   // 0C
  "\n"   ".XX...."   // 30
  "\n"   "X......"   // 40
  "\n"   ".XX...."   // 30
  "\n"   "...XXXX" , // 0F

  "X" /* UTF-8 58 - Glyph 57 */

  "\n"   "XX...XX"   // 63
  "\n"   "..X.X.."   // 14
  "\n"   "...X..."   // 08
  "\n"   "..X.X.."   // 14
  "\n"   "XX...XX" , // 63

  "Y" /* UTF-8 59 - Glyph 58 */

  "\n"   ".....XX"   // 03
  "\n"   "....X.."   // 04
  "\n"   "XXXX..."   // 78
  "\n"   "....X.."   // 04
  "\n"   ".....XX" , // 03

  "Z" /* UTF-8 5A - Glyph 59 */

  "\n"   "XX....X"   // 61
  "\n"   "X.X...X"   // 51
  "\n"   "X..X..X"   // 49
  "\n"   "X...X.X"   // 45
  "\n"   "X....XX" , // 43

  "[" /* UTF-8 5B - Glyph 60 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "X.....X"   // 41
  "\n"   "X.....X" , // 41

  "\\" /* UTF-8 5C - Glyph 61 */

  "\n"   "....X.."   // 04
  "\n"   "...X..."   // 08
  "\n"   "..X...."   // 10
  "\n"   ".X....."   // 20
  "\n"   "X......" , // 40

  "]" /* UTF-8 5D - Glyph 62 */

  "\n"   "X.....X"   // 41
  "\n"   "X.....X"   // 41
  "\n"   "XXXXXXX" , // 7F

  "^" /* UTF-8 5E - Glyph 63 */

  "\n"   "....X.."   // 04
  "\n"   ".....X."   // 02
  "\n"   "......X"   // 01
  "\n"   ".....X."   // 02
  "\n"   "....X.." , // 04

  "_" /* UTF-8 5F - Glyph 64 */

  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "X......" , // 40

  "`" /* UTF-8 60 - Glyph 65 */

  "\n"   "......X"   // 01
  "\n"   ".....X." , // 02

  "a" /* UTF-8 61 - Glyph 66 */

  "\n"   ".X....."   // 20
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.X.."   // 54
  "\n"   "XXXX..." , // 78

  "b" /* UTF-8 62 - Glyph 67 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "X...X.."   // 44
  "\n"   "X...X.."   // 44
  "\n"   "X...X.."   // 44
  "\n"   ".XXX..." , // 38

  "c" /* UTF-8 63 - Glyph 68 */

  "\n"   ".XXX..."   // 38
  "\n"   "X...X.."   // 44
  "\n"   "X...X.."   // 44
  "\n"   "X...X.."   // 44
  "\n"   "...X..." , // 08

  "d" /* UTF-8 64 - Glyph 69 */

  "\n"   ".XXX..."   // 38
  "\n"   "X...X.."   // 44
  "\n"   "X...X.."   // 44
  "\n"   "X...X.."   // 44
  "\n"   "XXXXXXX" , // 7F

  "e" /* UTF-8 65 - Glyph 70 */

  "\n"   ".XXX..."   // 38
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.X.."   // 54
  "\n"   "..XX..." , // 18

  "f" /* UTF-8 66 - Glyph 71 */

  "\n"   "...X..."   // 08
  "\n"   "XXXXXX."   // 7E
  "\n"   "...X..X"   // 09
  "\n"   "...X..X"   // 09
  "\n"   ".....X." , // 02

  "g" /* UTF-8 67 - Glyph 72 */

  "\n"   "X..X..."   // 48
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.X.."   // 54
  "\n"   ".XXX..." , // 38

  "h" /* UTF-8 68 - Glyph 73 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "XXX...." , // 70

  "i" /* UTF-8 69 - Glyph 74 */

  "\n"   "X..X..."   // 48
  "\n"   "XXXX.X."   // 7A
  "\n"   "X......" , // 40

  "j" /* UTF-8 6A - Glyph 75 */

  "\n"   ".X....."   // 20
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "X..X..."   // 48
  "\n"   ".XXX.X." , // 3A

  "k" /* UTF-8 6B - Glyph 76 */

  "\n"   "XXXXXXX"   // 7F
  "\n"   "..X...."   // 10
  "\n"   ".X.X..."   // 28
  "\n"   "X...X.." , // 44

  "l" /* UTF-8 6C - Glyph 77 */

  "\n"   ".XXXXXX"   // 3F
  "\n"   "X......"   // 40
  "\n"   "X......" , // 40

  "m" /* UTF-8 6D - Glyph 78 */

  "\n"   "XXXXX.."   // 7C
  "\n"   "....X.."   // 04
  "\n"   "....X.."   // 04
  "\n"   ".XXX..."   // 38
  "\n"   "....X.."   // 04
  "\n"   "....X.."   // 04
  "\n"   "XXXX..." , // 78

  "n" /* UTF-8 6E - Glyph 79 */

  "\n"   "XXXXX.."   // 7C
  "\n"   "....X.."   // 04
  "\n"   "....X.."   // 04
  "\n"   "....X.."   // 04
  "\n"   "XXXX..." , // 78

  "o" /* UTF-8 6F - Glyph 80 */

  "\n"   ".XXX..."   // 38
  "\n"   "X...X.."   // 44
  "\n"   "X...X.."   // 44
  "\n"   "X...X.."   // 44
  "\n"   ".XXX..." , // 38

  "p" /* UTF-8 70 - Glyph 81 */

  "\n"   "XXXXX.."   // 7C
  "\n"   "..X.X.."   // 14
  "\n"   "..X.X.."   // 14
  "\n"   "..X.X.."   // 14
  "\n"   "...X..." , // 08

  "q" /* UTF-8 71 - Glyph 82 */

  "\n"   "...X..."   // 08
  "\n"   "..X.X.."   // 14
  "\n"   "..X.X.."   // 14
  "\n"   "XXXXX.."   // 7C
  "\n"   "X......" , // 40

  "r" /* UTF-8 72 - Glyph 83 */

  "\n"   "XXXXX.."   // 7C
  "\n"   "....X.."   // 04
  "\n"   "....X.."   // 04
  "\n"   "....X.."   // 04
  "\n"   "...X..." , // 08

  "s" /* UTF-8 73 - Glyph 84 */

  "\n"   "X..X..."   // 48
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.X.."   // 54
  "\n"   ".X..X.." , // 24

  "t" /* UTF-8 74 - Glyph 85 */

  "\n"   "....X.."   // 04
  "\n"   "....X.."   // 04
  "\n"   "XXXXXXX"   // 7F
  "\n"   "X...X.."   // 44
  "\n"   "X...X.." , // 44

  "u" /* UTF-8 75 - Glyph 86 */

  "\n"   ".XXXX.."   // 3C
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "XXXXX.." , // 7C

  "v" /* UTF-8 76 - Glyph 87 */

  "\n"   "..XXX.."   // 1C
  "\n"   ".X....."   // 20
  "\n"   "X......"   // 40
  "\n"   ".X....."   // 20
  "\n"   "..XXX.." , // 1C

  "w" /* UTF-8 77 - Glyph 88 */

  "\n"   "XXXXX.."   // 7C
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   ".XXX..."   // 38
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "XXXXX.." , // 7C

  "x" /* UTF-8 78 - Glyph 89 */

  "\n"   "X...X.."   // 44
  "\n"   ".X.X..."   // 28
  "\n"   "..X...."   // 10
  "\n"   ".X.X..."   // 28
  "\n"   "X...X.." , // 44

  "y" /* UTF-8 79 - Glyph 90 */

  "\n"   "...XX.."   // 0C
  "\n"   "X.X...."   // 50
  "\n"   "X.X...."   // 50
  "\n"   "X.X...."   // 50
  "\n"   ".XXXX.." , // 3C

  "z" /* UTF-8 7A - Glyph 91 */

  "\n"   "X...X.."   // 44
  "\n"   "XX..X.."   // 64
  "\n"   "X.X.X.."   // 54
  "\n"   "X..XX.."   // 4C
  "\n"   "X...X.." , // 44

  "{" /* UTF-8 7B - Glyph 92 */

  "\n"   "...X..."   // 08
  "\n"   ".XX.XX."   // 36
  "\n"   "X.....X" , // 41

  "|" /* UTF-8 7C - Glyph 93 */

  "\n"   "XXXXXXX" , // 7F

  "}" /* UTF-8 7D - Glyph 94 */

  "\n"   "X.....X"   // 41
  "\n"   ".XX.XX."   // 36
  "\n"   "...X..." , // 08

  "~" /* UTF-8 7E - Glyph 95 */

  "\n"   "....X.."   // 04
  "\n"   ".....X."   // 02
  "\n"   "....X.."   // 04
  "\n"   "...X..."   // 08
  "\n"   "....X.." , // 04

  " " /* UTF-8 C2 A0 - Glyph 96 */

  "\n"   "......."   // 00
  "\n"   "......."   // 00
  "\n"   "......."   // 00
  "\n"   "......."   // 00
  "\n"   "......." , // 00

  "À" /* UTF-8 C3 80 - Glyph 97 */

  "\n"   "XXXX..."   // 78
  "\n"   "..X.X.X"   // 15
  "\n"   "..X..X."   // 12
  "\n"   "..X.X.."   // 14
  "\n"   "XXXX..." , // 78

  "Á" /* UTF-8 C3 81 - Glyph 98 */

  "\n"   "XXXX..."   // 78
  "\n"   "..X.X.."   // 14
  "\n"   "..X..X."   // 12
  "\n"   "..X.X.X"   // 15
  "\n"   "XXXX..." , // 78

  "Â" /* UTF-8 C3 82 - Glyph 99 */

  "\n"   "XXXX..."   // 78
  "\n"   "..X.XX."   // 16
  "\n"   "..X..XX"   // 13
  "\n"   "..X.XX."   // 16
  "\n"   "XXXX..." , // 78

  "Ä" /* UTF-8 C3 84 - Glyph 100 */

  "\n"   "XXXXX.X"   // 7D
  "\n"   "...X.X."   // 0A
  "\n"   "...X..X"   // 09
  "\n"   "...X.X."   // 0A
  "\n"   "XXXXX.X" , // 7D

  "È" /* UTF-8 C3 88 - Glyph 101 */

  "\n"   "XXXXXX."   // 7E
  "\n"   "X..X.XX"   // 4B
  "\n"   "X..X.X."   // 4A
  "\n"   "X....X."   // 42
  "\n"   "X....X." , // 42

  "É" /* UTF-8 C3 89 - Glyph 102 */

  "\n"   "XXXXXX."   // 7E
  "\n"   "X..X.X."   // 4A
  "\n"   "X..X.X."   // 4A
  "\n"   "X....XX"   // 43
  "\n"   "X....X." , // 42

  "Ê" /* UTF-8 C3 8A - Glyph 103 */

  "\n"   "XXXXXX."   // 7E
  "\n"   "X..X.XX"   // 4B
  "\n"   "X..X.XX"   // 4B
  "\n"   "X....XX"   // 43
  "\n"   "X....X." , // 42

  "Ö" /* UTF-8 C3 96 - Glyph 104 */

  "\n"   ".XXXX.X"   // 3D
  "\n"   "X....X."   // 42
  "\n"   "X....X."   // 42
  "\n"   "X....X."   // 42
  "\n"   ".XXXX.X" , // 3D

  "Ü" /* UTF-8 C3 9C - Glyph 105 */

  "\n"   ".XXXX.X"   // 3D
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   "X......"   // 40
  "\n"   ".XXXX.X" , // 3D

  "à" /* UTF-8 C3 A0 - Glyph 106 */

  "\n"   ".X....."   // 20
  "\n"   "X.X.X.X"   // 55
  "\n"   "X.X.XX."   // 56
  "\n"   "X.X.X.."   // 54
  "\n"   "XXXX..." , // 78

  "á" /* UTF-8 C3 A1 - Glyph 107 */

  "\n"   ".X....."   // 20
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.XX."   // 56
  "\n"   "X.X.X.X"   // 55
  "\n"   "XXXX..." , // 78

  "â" /* UTF-8 C3 A2 - Glyph 108 */

  "\n"   ".X....."   // 20
  "\n"   "X.X.XX."   // 56
  "\n"   "X.X.X.X"   // 55
  "\n"   "X.X.XX."   // 56
  "\n"   "XXXX..." , // 78

  "ä" /* UTF-8 C3 A4 - Glyph 109 */

  "\n"   ".X....."   // 20
  "\n"   "X.X.X.X"   // 55
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.X.X"   // 55
  "\n"   "XXXX..." , // 78

  "ç" /* UTF-8 C3 A7 - Glyph 110 */

  "\n"   ".XXX..."   // 38
  "\n"   "X...X.."   // 44
  "\n"   "XX..X.."   // 64
  "\n"   "X...X.."   // 44
  "\n"   "...X..." , // 08

  "è" /* UTF-8 C3 A8 - Glyph 111 */

  "\n"   ".XXX..."   // 38
  "\n"   "X.X.X.X"   // 55
  "\n"   "X.X.XX."   // 56
  "\n"   "X.X.X.."   // 54
  "\n"   "..XX..." , // 18

  "é" /* UTF-8 C3 A9 - Glyph 112 */

  "\n"   ".XXX..."   // 38
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.XX."   // 56
  "\n"   "X.X.X.X"   // 55
  "\n"   "..XX..." , // 18

  "ê" /* UTF-8 C3 AA - Glyph 113 */

  "\n"   ".XXX..."   // 38
  "\n"   "X.X.XX."   // 56
  "\n"   "X.X.X.X"   // 55
  "\n"   "X.X.XX."   // 56
  "\n"   "..XX..." , // 18

  "ë" /* UTF-8 C3 AB - Glyph 114 */

  "\n"   ".XXX..."   // 38
  "\n"   "X.X.X.X"   // 55
  "\n"   "X.X.X.."   // 54
  "\n"   "X.X.X.X"   // 55
  "\n"   "..XX..." , // 18

  "ì" /* UTF-8 C3 AC - Glyph 115 */

  "\n"   "X..X.X."   // 4A
  "\n"   "XXXX..."   // 78
  "\n"   "X....X." , // 42

  "í" /* UTF-8 C3 AD - Glyph 116 */

  "\n"   "X..X.X."   // 4A
  "\n"   "XXXX..."   // 78
  "\n"   "X....X." , // 42

  "î" /* UTF-8 C3 AE - Glyph 117 */

  "\n"   "X..X.X."   // 4A
  "\n"   "XXXX..X"   // 79
  "\n"   "X....X." , // 42

  "ï" /* UTF-8 C3 AF - Glyph 118 */

  "\n"   "X..X.X."   // 4A
  "\n"   "XXXX..."   // 78
  "\n"   "X....X." , // 42

  "ö" /* UTF-8 C3 B6 - Glyph 119 */

  "\n"   ".XXX..."   // 38
  "\n"   "X...X.X"   // 45
  "\n"   "X...X.."   // 44
  "\n"   "X...X.X"   // 45
  "\n"   ".XXX..." , // 38

  "ü" /* UTF-8 C3 BC - Glyph 120 */

  "\n"   ".XXXX.."   // 3C
  "\n"   "X.....X"   // 41
  "\n"   "X......"   // 40
  "\n"   "X.....X"   // 41
  "\n"   "XXXXX.." , // 7C

  "–" /* UTF-8 E2 80 93 - Glyph 121 */

  "\n"   "......."   // 00
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "...X..."   // 08
  "\n"   "......." , // 00

  "’" /* UTF-8 E2 80 99 - Glyph 122 */

  "\n"   "....X.."   // 04
  "\n"   ".....XX" , // 03

  "•" /* UTF-8 E2 80 A2 - Glyph 123 */

  "\n"   "..XX..."   // 18
  "\n"   "..XX..." , // 18

  nullptr // terminator
};

// MARK: - end of generated font verification data


#endif // GENERATE_FONT_SOURCE


// MARK: - '5x7' generated font data

static const glyph_t font_5x7_glyphs[] = {
  {  5, "\x7f\x41\x41\x41\x7f"                     },  // placeholder          (input # 0 -> glyph # 0)
  {  5, "\x00\x00\x00\x00\x00"                     },  // ' ' UTF-8 20         (input # 1 -> glyph # 1)
  {  1, "\x5f"                                     },  // '!' UTF-8 21         (input # 2 -> glyph # 2)
  {  3, "\x03\x00\x03"                             },  // '"' UTF-8 22         (input # 3 -> glyph # 3)
  {  5, "\x28\x7c\x28\x7c\x28"                     },  // '#' UTF-8 23         (input # 4 -> glyph # 4)
  {  5, "\x24\x2a\x7f\x2a\x12"                     },  // '$' UTF-8 24         (input # 5 -> glyph # 5)
  {  5, "\x4c\x2c\x10\x68\x64"                     },  // '%' UTF-8 25         (input # 6 -> glyph # 6)
  {  5, "\x30\x4e\x55\x22\x40"                     },  // '&' UTF-8 26         (input # 7 -> glyph # 7)
  {  1, "\x03"                                     },  // ''' UTF-8 27         (input # 8 -> glyph # 8)
  {  3, "\x1c\x22\x41"                             },  // '(' UTF-8 28         (input # 9 -> glyph # 9)
  {  3, "\x41\x22\x1c"                             },  // ')' UTF-8 29         (input # 10 -> glyph # 10)
  {  5, "\x14\x08\x3e\x08\x14"                     },  // '*' UTF-8 2A         (input # 11 -> glyph # 11)
  {  5, "\x08\x08\x3e\x08\x08"                     },  // '+' UTF-8 2B         (input # 12 -> glyph # 12)
  {  2, "\x50\x30"                                 },  // ',' UTF-8 2C         (input # 13 -> glyph # 13)
  {  5, "\x08\x08\x08\x08\x08"                     },  // '-' UTF-8 2D         (input # 14 -> glyph # 14)
  {  2, "\x60\x60"                                 },  // '.' UTF-8 2E         (input # 15 -> glyph # 15)
  {  6, "\x40\x20\x10\x08\x04\x02"                 },  // '/' UTF-8 2F         (input # 16 -> glyph # 16)
  {  5, "\x3e\x51\x49\x45\x3e"                     },  // '0' UTF-8 30         (input # 17 -> glyph # 17)
  {  3, "\x42\x7f\x40"                             },  // '1' UTF-8 31         (input # 18 -> glyph # 18)
  {  5, "\x62\x51\x49\x49\x46"                     },  // '2' UTF-8 32         (input # 19 -> glyph # 19)
  {  5, "\x22\x41\x49\x49\x36"                     },  // '3' UTF-8 33         (input # 20 -> glyph # 20)
  {  5, "\x1c\x12\x11\x7f\x10"                     },  // '4' UTF-8 34         (input # 21 -> glyph # 21)
  {  5, "\x4f\x49\x49\x49\x31"                     },  // '5' UTF-8 35         (input # 22 -> glyph # 22)
  {  5, "\x3e\x49\x49\x49\x32"                     },  // '6' UTF-8 36         (input # 23 -> glyph # 23)
  {  5, "\x03\x01\x71\x09\x07"                     },  // '7' UTF-8 37         (input # 24 -> glyph # 24)
  {  5, "\x36\x49\x49\x49\x36"                     },  // '8' UTF-8 38         (input # 25 -> glyph # 25)
  {  5, "\x26\x49\x49\x49\x3e"                     },  // '9' UTF-8 39         (input # 26 -> glyph # 26)
  {  2, "\x66\x66"                                 },  // ':' UTF-8 3A         (input # 27 -> glyph # 27)
  {  2, "\x56\x36"                                 },  // ';' UTF-8 3B         (input # 28 -> glyph # 28)
  {  4, "\x08\x14\x22\x41"                         },  // '<' UTF-8 3C         (input # 29 -> glyph # 29)
  {  4, "\x14\x14\x14\x14"                         },  // '=' UTF-8 3D         (input # 30 -> glyph # 30)
  {  4, "\x41\x22\x14\x08"                         },  // '>' UTF-8 3E         (input # 31 -> glyph # 31)
  {  5, "\x02\x01\x59\x09\x06"                     },  // '?' UTF-8 3F         (input # 32 -> glyph # 32)
  {  5, "\x3e\x41\x5d\x55\x5e"                     },  // '@' UTF-8 40         (input # 33 -> glyph # 33)
  {  5, "\x7c\x0a\x09\x0a\x7c"                     },  // 'A' UTF-8 41         (input # 34 -> glyph # 34)
  {  5, "\x7f\x49\x49\x49\x36"                     },  // 'B' UTF-8 42         (input # 35 -> glyph # 35)
  {  5, "\x3e\x41\x41\x41\x22"                     },  // 'C' UTF-8 43         (input # 36 -> glyph # 36)
  {  5, "\x7f\x41\x41\x22\x1c"                     },  // 'D' UTF-8 44         (input # 37 -> glyph # 37)
  {  5, "\x7f\x49\x49\x41\x41"                     },  // 'E' UTF-8 45         (input # 38 -> glyph # 38)
  {  5, "\x7f\x09\x09\x01\x01"                     },  // 'F' UTF-8 46         (input # 39 -> glyph # 39)
  {  5, "\x3e\x41\x49\x49\x7a"                     },  // 'G' UTF-8 47         (input # 40 -> glyph # 40)
  {  5, "\x7f\x08\x08\x08\x7f"                     },  // 'H' UTF-8 48         (input # 41 -> glyph # 41)
  {  3, "\x41\x7f\x41"                             },  // 'I' UTF-8 49         (input # 42 -> glyph # 42)
  {  5, "\x30\x40\x40\x40\x3f"                     },  // 'J' UTF-8 4A         (input # 43 -> glyph # 43)
  {  5, "\x7f\x08\x0c\x12\x61"                     },  // 'K' UTF-8 4B         (input # 44 -> glyph # 44)
  {  5, "\x7f\x40\x40\x40\x40"                     },  // 'L' UTF-8 4C         (input # 45 -> glyph # 45)
  {  7, "\x7f\x02\x04\x0c\x04\x02\x7f"             },  // 'M' UTF-8 4D         (input # 46 -> glyph # 46)
  {  5, "\x7f\x02\x04\x08\x7f"                     },  // 'N' UTF-8 4E         (input # 47 -> glyph # 47)
  {  5, "\x3e\x41\x41\x41\x3e"                     },  // 'O' UTF-8 4F         (input # 48 -> glyph # 48)
  {  5, "\x7f\x09\x09\x09\x06"                     },  // 'P' UTF-8 50         (input # 49 -> glyph # 49)
  {  5, "\x3e\x41\x51\x61\x7e"                     },  // 'Q' UTF-8 51         (input # 50 -> glyph # 50)
  {  5, "\x7f\x09\x09\x09\x76"                     },  // 'R' UTF-8 52         (input # 51 -> glyph # 51)
  {  5, "\x26\x49\x49\x49\x32"                     },  // 'S' UTF-8 53         (input # 52 -> glyph # 52)
  {  5, "\x01\x01\x7f\x01\x01"                     },  // 'T' UTF-8 54         (input # 53 -> glyph # 53)
  {  5, "\x3f\x40\x40\x40\x3f"                     },  // 'U' UTF-8 55         (input # 54 -> glyph # 54)
  {  5, "\x1f\x20\x40\x20\x1f"                     },  // 'V' UTF-8 56         (input # 55 -> glyph # 55)
  {  9, "\x0f\x30\x40\x30\x0c\x30\x40\x30\x0f"     },  // 'W' UTF-8 57         (input # 56 -> glyph # 56)
  {  5, "\x63\x14\x08\x14\x63"                     },  // 'X' UTF-8 58         (input # 57 -> glyph # 57)
  {  5, "\x03\x04\x78\x04\x03"                     },  // 'Y' UTF-8 59         (input # 58 -> glyph # 58)
  {  5, "\x61\x51\x49\x45\x43"                     },  // 'Z' UTF-8 5A         (input # 59 -> glyph # 59)
  {  3, "\x7f\x41\x41"                             },  // '[' UTF-8 5B         (input # 60 -> glyph # 60)
  {  5, "\x04\x08\x10\x20\x40"                     },  // '\' UTF-8 5C         (input # 61 -> glyph # 61)
  {  3, "\x41\x41\x7f"                             },  // ']' UTF-8 5D         (input # 62 -> glyph # 62)
  {  5, "\x04\x02\x01\x02\x04"                     },  // '^' UTF-8 5E         (input # 63 -> glyph # 63)
  {  5, "\x40\x40\x40\x40\x40"                     },  // '_' UTF-8 5F         (input # 64 -> glyph # 64)
  {  2, "\x01\x02"                                 },  // '`' UTF-8 60         (input # 65 -> glyph # 65)
  {  5, "\x20\x54\x54\x54\x78"                     },  // 'a' UTF-8 61         (input # 66 -> glyph # 66)
  {  5, "\x7f\x44\x44\x44\x38"                     },  // 'b' UTF-8 62         (input # 67 -> glyph # 67)
  {  5, "\x38\x44\x44\x44\x08"                     },  // 'c' UTF-8 63         (input # 68 -> glyph # 68)
  {  5, "\x38\x44\x44\x44\x7f"                     },  // 'd' UTF-8 64         (input # 69 -> glyph # 69)
  {  5, "\x38\x54\x54\x54\x18"                     },  // 'e' UTF-8 65         (input # 70 -> glyph # 70)
  {  5, "\x08\x7e\x09\x09\x02"                     },  // 'f' UTF-8 66         (input # 71 -> glyph # 71)
  {  5, "\x48\x54\x54\x54\x38"                     },  // 'g' UTF-8 67         (input # 72 -> glyph # 72)
  {  5, "\x7f\x08\x08\x08\x70"                     },  // 'h' UTF-8 68         (input # 73 -> glyph # 73)
  {  3, "\x48\x7a\x40"                             },  // 'i' UTF-8 69         (input # 74 -> glyph # 74)
  {  5, "\x20\x40\x40\x48\x3a"                     },  // 'j' UTF-8 6A         (input # 75 -> glyph # 75)
  {  4, "\x7f\x10\x28\x44"                         },  // 'k' UTF-8 6B         (input # 76 -> glyph # 76)
  {  3, "\x3f\x40\x40"                             },  // 'l' UTF-8 6C         (input # 77 -> glyph # 77)
  {  7, "\x7c\x04\x04\x38\x04\x04\x78"             },  // 'm' UTF-8 6D         (input # 78 -> glyph # 78)
  {  5, "\x7c\x04\x04\x04\x78"                     },  // 'n' UTF-8 6E         (input # 79 -> glyph # 79)
  {  5, "\x38\x44\x44\x44\x38"                     },  // 'o' UTF-8 6F         (input # 80 -> glyph # 80)
  {  5, "\x7c\x14\x14\x14\x08"                     },  // 'p' UTF-8 70         (input # 81 -> glyph # 81)
  {  5, "\x08\x14\x14\x7c\x40"                     },  // 'q' UTF-8 71         (input # 82 -> glyph # 82)
  {  5, "\x7c\x04\x04\x04\x08"                     },  // 'r' UTF-8 72         (input # 83 -> glyph # 83)
  {  5, "\x48\x54\x54\x54\x24"                     },  // 's' UTF-8 73         (input # 84 -> glyph # 84)
  {  5, "\x04\x04\x7f\x44\x44"                     },  // 't' UTF-8 74         (input # 85 -> glyph # 85)
  {  5, "\x3c\x40\x40\x40\x7c"                     },  // 'u' UTF-8 75         (input # 86 -> glyph # 86)
  {  5, "\x1c\x20\x40\x20\x1c"                     },  // 'v' UTF-8 76         (input # 87 -> glyph # 87)
  {  7, "\x7c\x40\x40\x38\x40\x40\x7c"             },  // 'w' UTF-8 77         (input # 88 -> glyph # 88)
  {  5, "\x44\x28\x10\x28\x44"                     },  // 'x' UTF-8 78         (input # 89 -> glyph # 89)
  {  5, "\x0c\x50\x50\x50\x3c"                     },  // 'y' UTF-8 79         (input # 90 -> glyph # 90)
  {  5, "\x44\x64\x54\x4c\x44"                     },  // 'z' UTF-8 7A         (input # 91 -> glyph # 91)
  {  3, "\x08\x36\x41"                             },  // '{' UTF-8 7B         (input # 92 -> glyph # 92)
  {  1, "\x7f"                                     },  // '|' UTF-8 7C         (input # 93 -> glyph # 93)
  {  3, "\x41\x36\x08"                             },  // '}' UTF-8 7D         (input # 94 -> glyph # 94)
  {  5, "\x04\x02\x04\x08\x04"                     },  // '~' UTF-8 7E         (input # 95 -> glyph # 95)
  {  5, "\x00\x00\x00\x00\x00"                     },  // ' ' UTF-8 C2 A0     (input # 96 -> glyph # 96)
  {  5, "\x78\x15\x12\x14\x78"                     },  // 'À' UTF-8 C3 80     (input # 97 -> glyph # 97)
  {  5, "\x78\x14\x12\x15\x78"                     },  // 'Á' UTF-8 C3 81     (input # 98 -> glyph # 98)
  {  5, "\x78\x16\x13\x16\x78"                     },  // 'Â' UTF-8 C3 82     (input # 99 -> glyph # 99)
  {  5, "\x7d\x0a\x09\x0a\x7d"                     },  // 'Ä' UTF-8 C3 84     (input # 100 -> glyph # 100)
  {  5, "\x7e\x4b\x4a\x42\x42"                     },  // 'È' UTF-8 C3 88     (input # 101 -> glyph # 101)
  {  5, "\x7e\x4a\x4a\x43\x42"                     },  // 'É' UTF-8 C3 89     (input # 102 -> glyph # 102)
  {  5, "\x7e\x4b\x4b\x43\x42"                     },  // 'Ê' UTF-8 C3 8A     (input # 103 -> glyph # 103)
  {  5, "\x3d\x42\x42\x42\x3d"                     },  // 'Ö' UTF-8 C3 96     (input # 104 -> glyph # 104)
  {  5, "\x3d\x40\x40\x40\x3d"                     },  // 'Ü' UTF-8 C3 9C     (input # 105 -> glyph # 105)
  {  5, "\x20\x55\x56\x54\x78"                     },  // 'à' UTF-8 C3 A0     (input # 106 -> glyph # 106)
  {  5, "\x20\x54\x56\x55\x78"                     },  // 'á' UTF-8 C3 A1     (input # 107 -> glyph # 107)
  {  5, "\x20\x56\x55\x56\x78"                     },  // 'â' UTF-8 C3 A2     (input # 108 -> glyph # 108)
  {  5, "\x20\x55\x54\x55\x78"                     },  // 'ä' UTF-8 C3 A4     (input # 109 -> glyph # 109)
  {  5, "\x38\x44\x64\x44\x08"                     },  // 'ç' UTF-8 C3 A7     (input # 110 -> glyph # 110)
  {  5, "\x38\x55\x56\x54\x18"                     },  // 'è' UTF-8 C3 A8     (input # 111 -> glyph # 111)
  {  5, "\x38\x54\x56\x55\x18"                     },  // 'é' UTF-8 C3 A9     (input # 112 -> glyph # 112)
  {  5, "\x38\x56\x55\x56\x18"                     },  // 'ê' UTF-8 C3 AA     (input # 113 -> glyph # 113)
  {  5, "\x38\x55\x54\x55\x18"                     },  // 'ë' UTF-8 C3 AB     (input # 114 -> glyph # 114)
  {  3, "\x4a\x78\x42"                             },  // 'ì' UTF-8 C3 AC     (input # 115 -> glyph # 115)
  {  3, "\x4a\x78\x42"                             },  // 'í' UTF-8 C3 AD     (input # 116 -> glyph # 116)
  {  3, "\x4a\x79\x42"                             },  // 'î' UTF-8 C3 AE     (input # 117 -> glyph # 117)
  {  3, "\x4a\x78\x42"                             },  // 'ï' UTF-8 C3 AF     (input # 118 -> glyph # 118)
  {  5, "\x38\x45\x44\x45\x38"                     },  // 'ö' UTF-8 C3 B6     (input # 119 -> glyph # 119)
  {  5, "\x3c\x41\x40\x41\x7c"                     },  // 'ü' UTF-8 C3 BC     (input # 120 -> glyph # 120)
  {  8, "\x00\x08\x08\x08\x08\x08\x08\x00"         },  // '–' UTF-8 E2 80 93 (input # 121 -> glyph # 121)
  {  2, "\x04\x03"                                 },  // '’' UTF-8 E2 80 99 (input # 122 -> glyph # 122)
  {  2, "\x18\x18"                                 },  // '•' UTF-8 E2 80 A2 (input # 123 -> glyph # 123)
};

static const GlyphRange font_5x7_ranges[] = {
  { "", 0x20, 0x7E, 1 }, //  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
  { "\xc2", 0xA0, 0xA0, 96 }, //  
  { "\xc3", 0x80, 0x82, 97 }, // ÀÁÂ
  { "\xc3", 0x84, 0x84, 100 }, // Ä
  { "\xc3", 0x88, 0x8A, 101 }, // ÈÉÊ
  { "\xc3", 0x96, 0x96, 104 }, // Ö
  { "\xc3", 0x9C, 0x9C, 105 }, // Ü
  { "\xc3", 0xA0, 0xA2, 106 }, // àáâ
  { "\xc3", 0xA4, 0xA4, 109 }, // ä
  { "\xc3", 0xA7, 0xAF, 110 }, // çèéêëìíîï
  { "\xc3", 0xB6, 0xB6, 119 }, // ö
  { "\xc3", 0xBC, 0xBC, 120 }, // ü
  { "\xe2\x80", 0x93, 0x93, 121 }, // –
  { "\xe2\x80", 0x99, 0x99, 122 }, // ’
  { "\xe2\x80", 0xA2, 0xA2, 123 }, // •
  { NULL, 0, 0, 0 }
};

static const font_t font_5x7 = {
  .fontName = "5x7",
  .glyphHeight = 7,
  .numGlyphs = 124,
  .glyphRanges = font_5x7_ranges,
  .glyphs = font_5x7_glyphs,
   #ifdef GENERATE_FONT_SOURCE
   .copyright = font_5x7_copyright,
   .glyphstrings = font_5x7_glyphstrings
   #else
   .copyright = nullptr
   #endif
};

static BuiltinFontRegistrar r(font_5x7);

// MARK: - end of generated font data

