//  SPDX-License-Identifier: GPL-3.0-or-later
//
//  Autogenerated by p44lrgraphics font generator
//
//  You should have received a copy of the GNU General Public License
//  along with p44lrgraphics. If not, see <http://www.gnu.org/licenses/>.

//  Include this file into a p44lrgraphics build to define a built-in font

#include "fonts.hpp"

using namespace p44;

#ifdef GENERATE_FONT_SOURCE

// Font author's copyright
static const char * font_m3x6_copyright =
  "Original font is (c) by Daniel Linssen - No embedding restrictions";

// MARK: - 'm3x6' generated font verification data

static const char * font_m3x6_glyphstrings[] = {
  "placeholder" /* 0x00 - Glyph 0 */

  "\n"   "XXXXXXXX"   // FF
  "\n"   "X......X"   // 81
  "\n"   "XXXXXXXX" , // FF

  " " /* UTF-8 20 - Glyph 1 */

  "\n"   "........"   // 00
  "\n"   "........"   // 00
  "\n"   "........" , // 00

  "!" /* UTF-8 21 - Glyph 2 */

  "\n"   "..X.XXXX" , // 2F

  "\"" /* UTF-8 22 - Glyph 3 */

  "\n"   "......XX"   // 03
  "\n"   "........"   // 00
  "\n"   "......XX" , // 03

  "#" /* UTF-8 23 - Glyph 4 */

  "\n"   "...X..X."   // 12
  "\n"   "..XXXXXX"   // 3F
  "\n"   "...X..X."   // 12
  "\n"   "..XXXXXX"   // 3F
  "\n"   "...X..X." , // 12

  "$" /* UTF-8 24 - Glyph 5 */

  "\n"   "..X.XX.."   // 2C
  "\n"   ".XX.X.XX"   // 6B
  "\n"   "...XX.X." , // 1A

  "%" /* UTF-8 25 - Glyph 6 */

  "\n"   "...X..X."   // 12
  "\n"   "....X..."   // 08
  "\n"   "..X..X.." , // 24

  "&" /* UTF-8 26 - Glyph 7 */

  "\n"   "...XX.X."   // 1A
  "\n"   "..X..X.X"   // 25
  "\n"   "..X.X.X."   // 2A
  "\n"   "...X...."   // 10
  "\n"   "..X.X..." , // 28

  "'" /* UTF-8 27 - Glyph 8 */

  "\n"   "......XX" , // 03

  "(" /* UTF-8 28 - Glyph 9 */

  "\n"   "..XXXXX."   // 3E
  "\n"   ".X.....X" , // 41

  ")" /* UTF-8 29 - Glyph 10 */

  "\n"   ".X.....X"   // 41
  "\n"   "..XXXXX." , // 3E

  "*" /* UTF-8 2A - Glyph 11 */

  "\n"   ".....X.X"   // 05
  "\n"   "......X."   // 02
  "\n"   ".....X.X" , // 05

  "+" /* UTF-8 2B - Glyph 12 */

  "\n"   "....X..."   // 08
  "\n"   "...XXX.."   // 1C
  "\n"   "....X..." , // 08

  "," /* UTF-8 2C - Glyph 13 */

  "\n"   ".XX....." , // 60

  "-" /* UTF-8 2D - Glyph 14 */

  "\n"   "....X..."   // 08
  "\n"   "....X..."   // 08
  "\n"   "....X..." , // 08

  "." /* UTF-8 2E - Glyph 15 */

  "\n"   "..X....." , // 20

  "/" /* UTF-8 2F - Glyph 16 */

  "\n"   "..XX...."   // 30
  "\n"   "....XX.."   // 0C
  "\n"   "......XX" , // 03

  "0" /* UTF-8 30 - Glyph 17 */

  "\n"   "..XXXXX."   // 3E
  "\n"   "..X....X"   // 21
  "\n"   "...XXXXX" , // 1F

  "1" /* UTF-8 31 - Glyph 18 */

  "\n"   "..X...X."   // 22
  "\n"   "..XXXXXX"   // 3F
  "\n"   "..X....." , // 20

  "2" /* UTF-8 32 - Glyph 19 */

  "\n"   "..XX...X"   // 31
  "\n"   "..X.X..X"   // 29
  "\n"   "..X..XX." , // 26

  "3" /* UTF-8 33 - Glyph 20 */

  "\n"   "..X..X.X"   // 25
  "\n"   "..X..X.X"   // 25
  "\n"   "...XX.X." , // 1A

  "4" /* UTF-8 34 - Glyph 21 */

  "\n"   "......XX"   // 03
  "\n"   ".....X.."   // 04
  "\n"   "..XXXXXX" , // 3F

  "5" /* UTF-8 35 - Glyph 22 */

  "\n"   "..X..XXX"   // 27
  "\n"   "..X..X.X"   // 25
  "\n"   "...XX..X" , // 19

  "6" /* UTF-8 36 - Glyph 23 */

  "\n"   "...XXXX."   // 1E
  "\n"   "..X..X.X"   // 25
  "\n"   "..XXX..X" , // 39

  "7" /* UTF-8 37 - Glyph 24 */

  "\n"   ".......X"   // 01
  "\n"   "..XXX..X"   // 39
  "\n"   ".....XXX" , // 07

  "8" /* UTF-8 38 - Glyph 25 */

  "\n"   "..XXX.X."   // 3A
  "\n"   "..X..X.X"   // 25
  "\n"   "...XX.XX" , // 1B

  "9" /* UTF-8 39 - Glyph 26 */

  "\n"   "..X..XXX"   // 27
  "\n"   "..X.X..X"   // 29
  "\n"   "...XXXX." , // 1E

  ":" /* UTF-8 3A - Glyph 27 */

  "\n"   "..X..X.." , // 24

  ";" /* UTF-8 3B - Glyph 28 */

  "\n"   ".XX..X.." , // 64

  "<" /* UTF-8 3C - Glyph 29 */

  "\n"   "....X..."   // 08
  "\n"   "...X.X.."   // 14
  "\n"   "..X...X." , // 22

  "=" /* UTF-8 3D - Glyph 30 */

  "\n"   "...X.X.."   // 14
  "\n"   "...X.X.."   // 14
  "\n"   "...X.X.." , // 14

  ">" /* UTF-8 3E - Glyph 31 */

  "\n"   "..X...X."   // 22
  "\n"   "...X.X.."   // 14
  "\n"   "....X..." , // 08

  "?" /* UTF-8 3F - Glyph 32 */

  "\n"   ".......X"   // 01
  "\n"   "..X.X..X"   // 29
  "\n"   ".....XX." , // 06

  "@" /* UTF-8 40 - Glyph 33 */

  "\n"   "...XXXX."   // 1E
  "\n"   "..X....X"   // 21
  "\n"   "..X.XX.X"   // 2D
  "\n"   "..X.X.XX"   // 2B
  "\n"   "..X.XXX." , // 2E

  "A" /* UTF-8 41 - Glyph 34 */

  "\n"   "..XXXXX."   // 3E
  "\n"   ".....X.X"   // 05
  "\n"   "..XXXXXX" , // 3F

  "B" /* UTF-8 42 - Glyph 35 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   "..X..X.X"   // 25
  "\n"   "..XXXXX." , // 3E

  "C" /* UTF-8 43 - Glyph 36 */

  "\n"   "..XXXXX."   // 3E
  "\n"   "..X....X"   // 21
  "\n"   "..X....X" , // 21

  "D" /* UTF-8 44 - Glyph 37 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   "..X....X"   // 21
  "\n"   "...XXXX." , // 1E

  "E" /* UTF-8 45 - Glyph 38 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   "..X..X.X"   // 25
  "\n"   "..X....X" , // 21

  "F" /* UTF-8 46 - Glyph 39 */

  "\n"   "..XXXXX."   // 3E
  "\n"   ".....X.X"   // 05
  "\n"   ".......X" , // 01

  "G" /* UTF-8 47 - Glyph 40 */

  "\n"   "..XXXXX."   // 3E
  "\n"   "..X....X"   // 21
  "\n"   "..XXX..X" , // 39

  "H" /* UTF-8 48 - Glyph 41 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   ".....X.."   // 04
  "\n"   "..XXXXXX" , // 3F

  "I" /* UTF-8 49 - Glyph 42 */

  "\n"   "..X....X"   // 21
  "\n"   "..XXXXXX"   // 3F
  "\n"   "..X....X" , // 21

  "J" /* UTF-8 4A - Glyph 43 */

  "\n"   "..X....X"   // 21
  "\n"   "..X....X"   // 21
  "\n"   "...XXXXX" , // 1F

  "K" /* UTF-8 4B - Glyph 44 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   ".....X.."   // 04
  "\n"   "..XXX.XX" , // 3B

  "L" /* UTF-8 4C - Glyph 45 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   "..X....."   // 20
  "\n"   "..X....." , // 20

  "M" /* UTF-8 4D - Glyph 46 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   ".......X"   // 01
  "\n"   "...XXXXX"   // 1F
  "\n"   ".......X"   // 01
  "\n"   "..XXXXX." , // 3E

  "N" /* UTF-8 4E - Glyph 47 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   ".......X"   // 01
  "\n"   "..XXXXX." , // 3E

  "O" /* UTF-8 4F - Glyph 48 */

  "\n"   "..XXXXX."   // 3E
  "\n"   "..X....X"   // 21
  "\n"   "...XXXXX" , // 1F

  "P" /* UTF-8 50 - Glyph 49 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   ".....X.X"   // 05
  "\n"   "......XX" , // 03

  "Q" /* UTF-8 51 - Glyph 50 */

  "\n"   "..XXXXX."   // 3E
  "\n"   "..X....X"   // 21
  "\n"   ".X.XXXXX" , // 5F

  "R" /* UTF-8 52 - Glyph 51 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   ".....X.X"   // 05
  "\n"   "..XXX.XX" , // 3B

  "S" /* UTF-8 53 - Glyph 52 */

  "\n"   "..X..XX."   // 26
  "\n"   "..X..X.X"   // 25
  "\n"   "...XXX.X" , // 1D

  "T" /* UTF-8 54 - Glyph 53 */

  "\n"   ".......X"   // 01
  "\n"   "..XXXXXX"   // 3F
  "\n"   ".......X" , // 01

  "U" /* UTF-8 55 - Glyph 54 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   "..X....."   // 20
  "\n"   "..XXXXXX" , // 3F

  "V" /* UTF-8 56 - Glyph 55 */

  "\n"   "...XXXXX"   // 1F
  "\n"   "..X....."   // 20
  "\n"   "...XXXXX" , // 1F

  "W" /* UTF-8 57 - Glyph 56 */

  "\n"   "...XXXXX"   // 1F
  "\n"   "..X....."   // 20
  "\n"   "...XXXX."   // 1E
  "\n"   "..X....."   // 20
  "\n"   "...XXXXX" , // 1F

  "X" /* UTF-8 58 - Glyph 57 */

  "\n"   "..XX..XX"   // 33
  "\n"   "....XX.."   // 0C
  "\n"   "..XX..XX" , // 33

  "Y" /* UTF-8 59 - Glyph 58 */

  "\n"   ".....XXX"   // 07
  "\n"   "..XXX..."   // 38
  "\n"   ".....XXX" , // 07

  "Z" /* UTF-8 5A - Glyph 59 */

  "\n"   "..XX...X"   // 31
  "\n"   "..X.XX.X"   // 2D
  "\n"   "..X...XX" , // 23

  "[" /* UTF-8 5B - Glyph 60 */

  "\n"   ".XXXXXXX"   // 7F
  "\n"   ".X.....X" , // 41

  "\\" /* UTF-8 5C - Glyph 61 */

  "\n"   "......XX"   // 03
  "\n"   "....XX.."   // 0C
  "\n"   "..XX...." , // 30

  "]" /* UTF-8 5D - Glyph 62 */

  "\n"   ".X.....X"   // 41
  "\n"   ".XXXXXXX" , // 7F

  "^" /* UTF-8 5E - Glyph 63 */

  "\n"   ".....X.."   // 04
  "\n"   "......X."   // 02
  "\n"   ".....X.." , // 04

  "_" /* UTF-8 5F - Glyph 64 */

  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....." , // 20

  "`" /* UTF-8 60 - Glyph 65 */

  "\n"   "......XX" , // 03

  "a" /* UTF-8 61 - Glyph 66 */

  "\n"   "..XX..X."   // 32
  "\n"   "..X.X.X."   // 2A
  "\n"   "..XXXX.." , // 3C

  "b" /* UTF-8 62 - Glyph 67 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   "..X...X."   // 22
  "\n"   "..XXXX.." , // 3C

  "c" /* UTF-8 63 - Glyph 68 */

  "\n"   "..XXXX.."   // 3C
  "\n"   "..X...X."   // 22
  "\n"   "..X...X." , // 22

  "d" /* UTF-8 64 - Glyph 69 */

  "\n"   "..XXXX.."   // 3C
  "\n"   "..X...X."   // 22
  "\n"   "..XXXXXX" , // 3F

  "e" /* UTF-8 65 - Glyph 70 */

  "\n"   "...XXX.."   // 1C
  "\n"   "..X.X.X."   // 2A
  "\n"   "..X.XXX." , // 2E

  "f" /* UTF-8 66 - Glyph 71 */

  "\n"   "....X..."   // 08
  "\n"   "..XXXXX."   // 3E
  "\n"   "....X..X" , // 09

  "g" /* UTF-8 67 - Glyph 72 */

  "\n"   "X.XXXX.."   // BC
  "\n"   "X.X...X."   // A2
  "\n"   ".XXXXXX." , // 7E

  "h" /* UTF-8 68 - Glyph 73 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   "......X."   // 02
  "\n"   "..XXXX.." , // 3C

  "i" /* UTF-8 69 - Glyph 74 */

  "\n"   "..XXXX.X" , // 3D

  "j" /* UTF-8 6A - Glyph 75 */

  "\n"   "X......."   // 80
  "\n"   ".XXXXX.X" , // 7D

  "k" /* UTF-8 6B - Glyph 76 */

  "\n"   "..XXXXXX"   // 3F
  "\n"   "....X..."   // 08
  "\n"   "..XX.X.." , // 34

  "l" /* UTF-8 6C - Glyph 77 */

  "\n"   "...XXXXX"   // 1F
  "\n"   "..X....." , // 20

  "m" /* UTF-8 6D - Glyph 78 */

  "\n"   "..XXXXX."   // 3E
  "\n"   "......X."   // 02
  "\n"   "..XXXX.."   // 3C
  "\n"   "......X."   // 02
  "\n"   "..XXXX.." , // 3C

  "n" /* UTF-8 6E - Glyph 79 */

  "\n"   "..XXXXX."   // 3E
  "\n"   "......X."   // 02
  "\n"   "..XXXX.." , // 3C

  "o" /* UTF-8 6F - Glyph 80 */

  "\n"   "..XXXX.."   // 3C
  "\n"   "..X...X."   // 22
  "\n"   "...XXXX." , // 1E

  "p" /* UTF-8 70 - Glyph 81 */

  "\n"   "XXXXXXX."   // FE
  "\n"   "..X...X."   // 22
  "\n"   "...XXXX." , // 1E

  "q" /* UTF-8 71 - Glyph 82 */

  "\n"   "..XXXX.."   // 3C
  "\n"   "..X...X."   // 22
  "\n"   "XXXXXXX." , // FE

  "r" /* UTF-8 72 - Glyph 83 */

  "\n"   "..XXXX.."   // 3C
  "\n"   "......X."   // 02
  "\n"   "......X." , // 02

  "s" /* UTF-8 73 - Glyph 84 */

  "\n"   "..X.XX.."   // 2C
  "\n"   "..X.X.X."   // 2A
  "\n"   "...XX.X." , // 1A

  "t" /* UTF-8 74 - Glyph 85 */

  "\n"   ".....X.."   // 04
  "\n"   "..XXXXXX"   // 3F
  "\n"   ".....X.." , // 04

  "u" /* UTF-8 75 - Glyph 86 */

  "\n"   "..XXXXX."   // 3E
  "\n"   "..X....."   // 20
  "\n"   "..XXXXX." , // 3E

  "v" /* UTF-8 76 - Glyph 87 */

  "\n"   "...XXXX."   // 1E
  "\n"   "..X....."   // 20
  "\n"   "...XXXX." , // 1E

  "w" /* UTF-8 77 - Glyph 88 */

  "\n"   "...XXXX."   // 1E
  "\n"   "..X....."   // 20
  "\n"   "...XXX.."   // 1C
  "\n"   "..X....."   // 20
  "\n"   "...XXXX." , // 1E

  "x" /* UTF-8 78 - Glyph 89 */

  "\n"   "..XX.XX."   // 36
  "\n"   "....X..."   // 08
  "\n"   "..XX.XX." , // 36

  "y" /* UTF-8 79 - Glyph 90 */

  "\n"   "X..XXXX."   // 9E
  "\n"   "X.X....."   // A0
  "\n"   ".XXXXXX." , // 7E

  "z" /* UTF-8 7A - Glyph 91 */

  "\n"   "..XX..X."   // 32
  "\n"   "..X.X.X."   // 2A
  "\n"   "..X..XX." , // 26

  "{" /* UTF-8 7B - Glyph 92 */

  "\n"   "....X..."   // 08
  "\n"   "..XX.XX."   // 36
  "\n"   ".X.....X" , // 41

  "|" /* UTF-8 7C - Glyph 93 */

  "\n"   ".XXXXXXX" , // 7F

  "}" /* UTF-8 7D - Glyph 94 */

  "\n"   ".X.....X"   // 41
  "\n"   "..XX.XX."   // 36
  "\n"   "....X..." , // 08

  "~" /* UTF-8 7E - Glyph 95 */

  "\n"   "....X..."   // 08
  "\n"   "....XX.."   // 0C
  "\n"   ".....X.." , // 04

  nullptr // terminator
};

// MARK: - end of generated font verification data


#endif // GENERATE_FONT_SOURCE


// MARK: - 'm3x6' generated font data

static const glyph_t font_m3x6_glyphs[] = {
  {  3, "\xff\x81\xff"                             },  // placeholder          (input # 0 -> glyph # 0)
  {  3, "\x00\x00\x00"                             },  // ' ' UTF-8 20         (input # 1 -> glyph # 1)
  {  1, "\x2f"                                     },  // '!' UTF-8 21         (input # 2 -> glyph # 2)
  {  3, "\x03\x00\x03"                             },  // '"' UTF-8 22         (input # 3 -> glyph # 3)
  {  5, "\x12\x3f\x12\x3f\x12"                     },  // '#' UTF-8 23         (input # 4 -> glyph # 4)
  {  3, "\x2c\x6b\x1a"                             },  // '$' UTF-8 24         (input # 5 -> glyph # 5)
  {  3, "\x12\x08\x24"                             },  // '%' UTF-8 25         (input # 6 -> glyph # 6)
  {  5, "\x1a\x25\x2a\x10\x28"                     },  // '&' UTF-8 26         (input # 7 -> glyph # 7)
  {  1, "\x03"                                     },  // ''' UTF-8 27         (input # 8 -> glyph # 8)
  {  2, "\x3e\x41"                                 },  // '(' UTF-8 28         (input # 9 -> glyph # 9)
  {  2, "\x41\x3e"                                 },  // ')' UTF-8 29         (input # 10 -> glyph # 10)
  {  3, "\x05\x02\x05"                             },  // '*' UTF-8 2A         (input # 11 -> glyph # 11)
  {  3, "\x08\x1c\x08"                             },  // '+' UTF-8 2B         (input # 12 -> glyph # 12)
  {  1, "\x60"                                     },  // ',' UTF-8 2C         (input # 13 -> glyph # 13)
  {  3, "\x08\x08\x08"                             },  // '-' UTF-8 2D         (input # 14 -> glyph # 14)
  {  1, "\x20"                                     },  // '.' UTF-8 2E         (input # 15 -> glyph # 15)
  {  3, "\x30\x0c\x03"                             },  // '/' UTF-8 2F         (input # 16 -> glyph # 16)
  {  3, "\x3e\x21\x1f"                             },  // '0' UTF-8 30         (input # 17 -> glyph # 17)
  {  3, "\x22\x3f\x20"                             },  // '1' UTF-8 31         (input # 18 -> glyph # 18)
  {  3, "\x31\x29\x26"                             },  // '2' UTF-8 32         (input # 19 -> glyph # 19)
  {  3, "\x25\x25\x1a"                             },  // '3' UTF-8 33         (input # 20 -> glyph # 20)
  {  3, "\x03\x04\x3f"                             },  // '4' UTF-8 34         (input # 21 -> glyph # 21)
  {  3, "\x27\x25\x19"                             },  // '5' UTF-8 35         (input # 22 -> glyph # 22)
  {  3, "\x1e\x25\x39"                             },  // '6' UTF-8 36         (input # 23 -> glyph # 23)
  {  3, "\x01\x39\x07"                             },  // '7' UTF-8 37         (input # 24 -> glyph # 24)
  {  3, "\x3a\x25\x1b"                             },  // '8' UTF-8 38         (input # 25 -> glyph # 25)
  {  3, "\x27\x29\x1e"                             },  // '9' UTF-8 39         (input # 26 -> glyph # 26)
  {  1, "\x24"                                     },  // ':' UTF-8 3A         (input # 27 -> glyph # 27)
  {  1, "\x64"                                     },  // ';' UTF-8 3B         (input # 28 -> glyph # 28)
  {  3, "\x08\x14\x22"                             },  // '<' UTF-8 3C         (input # 29 -> glyph # 29)
  {  3, "\x14\x14\x14"                             },  // '=' UTF-8 3D         (input # 30 -> glyph # 30)
  {  3, "\x22\x14\x08"                             },  // '>' UTF-8 3E         (input # 31 -> glyph # 31)
  {  3, "\x01\x29\x06"                             },  // '?' UTF-8 3F         (input # 32 -> glyph # 32)
  {  5, "\x1e\x21\x2d\x2b\x2e"                     },  // '@' UTF-8 40         (input # 33 -> glyph # 33)
  {  3, "\x3e\x05\x3f"                             },  // 'A' UTF-8 41         (input # 34 -> glyph # 34)
  {  3, "\x3f\x25\x3e"                             },  // 'B' UTF-8 42         (input # 35 -> glyph # 35)
  {  3, "\x3e\x21\x21"                             },  // 'C' UTF-8 43         (input # 36 -> glyph # 36)
  {  3, "\x3f\x21\x1e"                             },  // 'D' UTF-8 44         (input # 37 -> glyph # 37)
  {  3, "\x3f\x25\x21"                             },  // 'E' UTF-8 45         (input # 38 -> glyph # 38)
  {  3, "\x3e\x05\x01"                             },  // 'F' UTF-8 46         (input # 39 -> glyph # 39)
  {  3, "\x3e\x21\x39"                             },  // 'G' UTF-8 47         (input # 40 -> glyph # 40)
  {  3, "\x3f\x04\x3f"                             },  // 'H' UTF-8 48         (input # 41 -> glyph # 41)
  {  3, "\x21\x3f\x21"                             },  // 'I' UTF-8 49         (input # 42 -> glyph # 42)
  {  3, "\x21\x21\x1f"                             },  // 'J' UTF-8 4A         (input # 43 -> glyph # 43)
  {  3, "\x3f\x04\x3b"                             },  // 'K' UTF-8 4B         (input # 44 -> glyph # 44)
  {  3, "\x3f\x20\x20"                             },  // 'L' UTF-8 4C         (input # 45 -> glyph # 45)
  {  5, "\x3f\x01\x1f\x01\x3e"                     },  // 'M' UTF-8 4D         (input # 46 -> glyph # 46)
  {  3, "\x3f\x01\x3e"                             },  // 'N' UTF-8 4E         (input # 47 -> glyph # 47)
  {  3, "\x3e\x21\x1f"                             },  // 'O' UTF-8 4F         (input # 48 -> glyph # 48)
  {  3, "\x3f\x05\x03"                             },  // 'P' UTF-8 50         (input # 49 -> glyph # 49)
  {  3, "\x3e\x21\x5f"                             },  // 'Q' UTF-8 51         (input # 50 -> glyph # 50)
  {  3, "\x3f\x05\x3b"                             },  // 'R' UTF-8 52         (input # 51 -> glyph # 51)
  {  3, "\x26\x25\x1d"                             },  // 'S' UTF-8 53         (input # 52 -> glyph # 52)
  {  3, "\x01\x3f\x01"                             },  // 'T' UTF-8 54         (input # 53 -> glyph # 53)
  {  3, "\x3f\x20\x3f"                             },  // 'U' UTF-8 55         (input # 54 -> glyph # 54)
  {  3, "\x1f\x20\x1f"                             },  // 'V' UTF-8 56         (input # 55 -> glyph # 55)
  {  5, "\x1f\x20\x1e\x20\x1f"                     },  // 'W' UTF-8 57         (input # 56 -> glyph # 56)
  {  3, "\x33\x0c\x33"                             },  // 'X' UTF-8 58         (input # 57 -> glyph # 57)
  {  3, "\x07\x38\x07"                             },  // 'Y' UTF-8 59         (input # 58 -> glyph # 58)
  {  3, "\x31\x2d\x23"                             },  // 'Z' UTF-8 5A         (input # 59 -> glyph # 59)
  {  2, "\x7f\x41"                                 },  // '[' UTF-8 5B         (input # 60 -> glyph # 60)
  {  3, "\x03\x0c\x30"                             },  // '\' UTF-8 5C         (input # 61 -> glyph # 61)
  {  2, "\x41\x7f"                                 },  // ']' UTF-8 5D         (input # 62 -> glyph # 62)
  {  3, "\x04\x02\x04"                             },  // '^' UTF-8 5E         (input # 63 -> glyph # 63)
  {  3, "\x20\x20\x20"                             },  // '_' UTF-8 5F         (input # 64 -> glyph # 64)
  {  1, "\x03"                                     },  // '`' UTF-8 60         (input # 65 -> glyph # 65)
  {  3, "\x32\x2a\x3c"                             },  // 'a' UTF-8 61         (input # 66 -> glyph # 66)
  {  3, "\x3f\x22\x3c"                             },  // 'b' UTF-8 62         (input # 67 -> glyph # 67)
  {  3, "\x3c\x22\x22"                             },  // 'c' UTF-8 63         (input # 68 -> glyph # 68)
  {  3, "\x3c\x22\x3f"                             },  // 'd' UTF-8 64         (input # 69 -> glyph # 69)
  {  3, "\x1c\x2a\x2e"                             },  // 'e' UTF-8 65         (input # 70 -> glyph # 70)
  {  3, "\x08\x3e\x09"                             },  // 'f' UTF-8 66         (input # 71 -> glyph # 71)
  {  3, "\xbc\xa2\x7e"                             },  // 'g' UTF-8 67         (input # 72 -> glyph # 72)
  {  3, "\x3f\x02\x3c"                             },  // 'h' UTF-8 68         (input # 73 -> glyph # 73)
  {  1, "\x3d"                                     },  // 'i' UTF-8 69         (input # 74 -> glyph # 74)
  {  2, "\x80\x7d"                                 },  // 'j' UTF-8 6A         (input # 75 -> glyph # 75)
  {  3, "\x3f\x08\x34"                             },  // 'k' UTF-8 6B         (input # 76 -> glyph # 76)
  {  2, "\x1f\x20"                                 },  // 'l' UTF-8 6C         (input # 77 -> glyph # 77)
  {  5, "\x3e\x02\x3c\x02\x3c"                     },  // 'm' UTF-8 6D         (input # 78 -> glyph # 78)
  {  3, "\x3e\x02\x3c"                             },  // 'n' UTF-8 6E         (input # 79 -> glyph # 79)
  {  3, "\x3c\x22\x1e"                             },  // 'o' UTF-8 6F         (input # 80 -> glyph # 80)
  {  3, "\xfe\x22\x1e"                             },  // 'p' UTF-8 70         (input # 81 -> glyph # 81)
  {  3, "\x3c\x22\xfe"                             },  // 'q' UTF-8 71         (input # 82 -> glyph # 82)
  {  3, "\x3c\x02\x02"                             },  // 'r' UTF-8 72         (input # 83 -> glyph # 83)
  {  3, "\x2c\x2a\x1a"                             },  // 's' UTF-8 73         (input # 84 -> glyph # 84)
  {  3, "\x04\x3f\x04"                             },  // 't' UTF-8 74         (input # 85 -> glyph # 85)
  {  3, "\x3e\x20\x3e"                             },  // 'u' UTF-8 75         (input # 86 -> glyph # 86)
  {  3, "\x1e\x20\x1e"                             },  // 'v' UTF-8 76         (input # 87 -> glyph # 87)
  {  5, "\x1e\x20\x1c\x20\x1e"                     },  // 'w' UTF-8 77         (input # 88 -> glyph # 88)
  {  3, "\x36\x08\x36"                             },  // 'x' UTF-8 78         (input # 89 -> glyph # 89)
  {  3, "\x9e\xa0\x7e"                             },  // 'y' UTF-8 79         (input # 90 -> glyph # 90)
  {  3, "\x32\x2a\x26"                             },  // 'z' UTF-8 7A         (input # 91 -> glyph # 91)
  {  3, "\x08\x36\x41"                             },  // '{' UTF-8 7B         (input # 92 -> glyph # 92)
  {  1, "\x7f"                                     },  // '|' UTF-8 7C         (input # 93 -> glyph # 93)
  {  3, "\x41\x36\x08"                             },  // '}' UTF-8 7D         (input # 94 -> glyph # 94)
  {  3, "\x08\x0c\x04"                             },  // '~' UTF-8 7E         (input # 95 -> glyph # 95)
};

static const GlyphRange font_m3x6_ranges[] = {
  { "", 0x20, 0x7E, 1 }, //  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
  { NULL, 0, 0, 0 }
};

static const font_t font_m3x6 = {
  .fontName = "m3x6",
  .glyphHeight = 8,
  .numGlyphs = 96,
  .glyphRanges = font_m3x6_ranges,
  .glyphs = font_m3x6_glyphs,
  #ifdef GENERATE_FONT_SOURCE
  .copyright = font_m3x6_copyright,
  .glyphstrings = font_m3x6_glyphstrings
  #else
  .copyright = nullptr
  #endif
};

static BuiltinFontRegistrar r(font_m3x6);

// MARK: - end of generated font data

