//  SPDX-License-Identifier: GPL-3.0-or-later
//
//  Autogenerated by plan44 FontHexer2 pixel font generator
//
//  You should have received a copy of the GNU General Public License
//  along with p44lrgraphics. If not, see <http://www.gnu.org/licenses/>.
//

// This is a font file to be included from textview.cpp to define a font

#ifdef GENERATE_FONT_SOURCE

// MARK: - 'vcr_osd_mono' generated font verification data

static const char * font_vcr_osd_mono_glyphstrings[] = {
  " " /* UTF-8 20 - Glyph 0 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................" ,

  "!" /* UTF-8 21 - Glyph 1 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "XX..XXXXXXXXXX.."  
  "\n"   "XX..XXXXXXXXXX.." ,

  "\"" /* UTF-8 22 - Glyph 2 */

  "\n"   "................"  
  "\n"   "...........XXX.."  
  "\n"   "..........XXXX.."  
  "\n"   "...........XXX.."  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "...........XXX.."  
  "\n"   "..........XXXX.."  
  "\n"   "...........XXX.." ,

  "#" /* UTF-8 23 - Glyph 3 */

  "\n"   "...XX...XX......"  
  "\n"   "...XX...XX......"  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "....XX...XX....."  
  "\n"   "....XX...XX....."  
  "\n"   "..XXXXXXXXXXXX.."  
  "\n"   "..XXXXXXXXXXXX.."  
  "\n"   ".....XX...XX...."  
  "\n"   ".....XX...XX...." ,

  "$" /* UTF-8 24 - Glyph 4 */

  "\n"   "...XX...XXX....."  
  "\n"   "..XXX..XXXXX...."  
  "\n"   ".XXX..XXX.XXX..."  
  "\n"   ".XX...XX...XX..."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   ".XX...XX...XX..."  
  "\n"   ".XXX.XXX..XXX..."  
  "\n"   "..XXXXX..XXX...."  
  "\n"   "...XXX...XX....." ,

  "%" /* UTF-8 25 - Glyph 5 */

  "\n"   "XXXX.....XXXX..."  
  "\n"   "XXXXX...XXXXXX.."  
  "\n"   "...XXX..XX..XX.."  
  "\n"   "....XXX.XXXXXX.."  
  "\n"   ".....XXX.XXXX..."  
  "\n"   ".XXXX.XXX......."  
  "\n"   "XXXXXX.XXX......"  
  "\n"   "XX..XX..XXX....."  
  "\n"   "XXXXXX...XXXXX.."  
  "\n"   ".XXXX.....XXXX.." ,

  "&" /* UTF-8 26 - Glyph 6 */

  "\n"   "..XXXXX........."  
  "\n"   ".XXXXXXX..XXXX.."  
  "\n"   "XXX...XXXXXXXXX."  
  "\n"   "XX....XXXX....XX"  
  "\n"   "XX...XXXX.....XX"  
  "\n"   "XX..XXXXXX....XX"  
  "\n"   "XXXXXX..XXXXXXX."  
  "\n"   ".XXXX.....XXXX.."  
  "\n"   "XXXXXX.........."  
  "\n"   "XX..XX.........." ,

  "'" /* UTF-8 27 - Glyph 7 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "...........XXX.."  
  "\n"   "..........XXXX.."  
  "\n"   "...........XXX.." ,

  "(" /* UTF-8 28 - Glyph 8 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "...XXXXXXXXXX..."  
  "\n"   "..XXXXXXXXXXXX.."  
  "\n"   ".XX..........XX."  
  "\n"   "XX............XX"  
  "\n"   "X..............X" ,

  ")" /* UTF-8 29 - Glyph 9 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "X..............X"  
  "\n"   "XX............XX"  
  "\n"   ".XX..........XX."  
  "\n"   "..XXXXXXXXXXXX.."  
  "\n"   "...XXXXXXXXXX..." ,

  "*" /* UTF-8 2A - Glyph 10 */

  "\n"   "................"  
  "\n"   ".......XX...XX.."  
  "\n"   "........XX.XX..."  
  "\n"   ".........XXX...."  
  "\n"   "......XXXXXXXXX."  
  "\n"   "......XXXXXXXXX."  
  "\n"   ".........XXX...."  
  "\n"   "........XX.XX..."  
  "\n"   ".......XX...XX.." ,

  "+" /* UTF-8 2B - Glyph 11 */

  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "..XXXXXXXXXX...."  
  "\n"   "..XXXXXXXXXX...."  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........" ,

  "," /* UTF-8 2C - Glyph 12 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "X..............."  
  "\n"   "XX.............."  
  "\n"   ".XXX............"  
  "\n"   "..XX............" ,

  "-" /* UTF-8 2D - Glyph 13 */

  "\n"   "................"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........" ,

  "." /* UTF-8 2E - Glyph 14 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "XX.............."  
  "\n"   "XX.............." ,

  "/" /* UTF-8 2F - Glyph 15 */

  "\n"   "XXXX............"  
  "\n"   "XXXXX..........."  
  "\n"   "...XXX.........."  
  "\n"   "....XXX........."  
  "\n"   ".....XXX........"  
  "\n"   "......XXX......."  
  "\n"   ".......XXX......"  
  "\n"   "........XXX....."  
  "\n"   ".........XXXXX.."  
  "\n"   "..........XXXX.." ,

  "0" /* UTF-8 30 - Glyph 16 */

  "\n"   "..XXXXXXXXXX...."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "XXX.XX.....XXX.."  
  "\n"   "XX..XXX.....XX.."  
  "\n"   "XX...XXX....XX.."  
  "\n"   "XX....XXX...XX.."  
  "\n"   "XX.....XXX..XX.."  
  "\n"   "XXX.....XX.XXX.."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "..XXXXXXXXXX...." ,

  "1" /* UTF-8 31 - Glyph 17 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "XX........XX...."  
  "\n"   "XX........XXX..."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XX.............."  
  "\n"   "XX.............." ,

  "2" /* UTF-8 32 - Glyph 18 */

  "\n"   "XXXXXX....XX...."  
  "\n"   "XXXXXXX...XXX..."  
  "\n"   "XX...XXX...XXX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XXX..XXX.."  
  "\n"   "XX.....XXXXXX..."  
  "\n"   "XX......XXXX...." ,

  "3" /* UTF-8 33 - Glyph 19 */

  "\n"   "..XX......XX...."  
  "\n"   ".XXX......XXX..."  
  "\n"   "XXX........XXX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XXX..XXXX..XXX.."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "..XXXX..XXXX...." ,

  "4" /* UTF-8 34 - Glyph 20 */

  "\n"   "....XXXX........"  
  "\n"   "....XXXXX......."  
  "\n"   "....XX.XXX......"  
  "\n"   "....XX..XXX....."  
  "\n"   "....XX...XXX...."  
  "\n"   "....XX....XXX..."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "....XX.........."  
  "\n"   "....XX.........." ,

  "5" /* UTF-8 35 - Glyph 21 */

  "\n"   "..XX....XXXXXX.."  
  "\n"   ".XXX....XXXXXX.."  
  "\n"   "XXX.....XX..XX.."  
  "\n"   "XX......XX..XX.."  
  "\n"   "XX......XX..XX.."  
  "\n"   "XX......XX..XX.."  
  "\n"   "XX......XX..XX.."  
  "\n"   "XXX....XXX..XX.."  
  "\n"   ".XXXXXXXX...XX.."  
  "\n"   "..XXXXXX....XX.." ,

  "6" /* UTF-8 36 - Glyph 22 */

  "\n"   "..XXXXXXXXXX...."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "XXX...XX...XXX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XXX..XXX...XXX.."  
  "\n"   ".XXXXXX...XXX..."  
  "\n"   "..XXXX....XX...." ,

  "7" /* UTF-8 37 - Glyph 23 */

  "\n"   "............XX.."  
  "\n"   "............XX.."  
  "\n"   "............XX.."  
  "\n"   "............XX.."  
  "\n"   "XXXXXXX.....XX.."  
  "\n"   "XXXXXXXX....XX.."  
  "\n"   "......XXX...XX.."  
  "\n"   ".......XXX..XX.."  
  "\n"   "........XXXXXX.."  
  "\n"   ".........XXXXX.." ,

  "8" /* UTF-8 38 - Glyph 24 */

  "\n"   "..XXXX..XXXX...."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "XXX..XXXX..XXX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XXX..XXXX..XXX.."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "..XXXX..XXXX...." ,

  "9" /* UTF-8 39 - Glyph 25 */

  "\n"   "..XX....XXXX...."  
  "\n"   ".XXX...XXXXXX..."  
  "\n"   "XXX...XXX..XXX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XXX...XX...XXX.."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "..XXXXXXXXXX...." ,

  ":" /* UTF-8 3A - Glyph 26 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "..XX......XX...."  
  "\n"   "..XX......XX...." ,

  ";" /* UTF-8 3B - Glyph 27 */

  "\n"   "................"  
  "\n"   "X..............."  
  "\n"   "XX.............."  
  "\n"   ".XXX......XX...."  
  "\n"   "..XX......XX...." ,

  "<" /* UTF-8 3C - Glyph 28 */

  "\n"   "................"  
  "\n"   "......XXX......."  
  "\n"   ".....XXXXX......"  
  "\n"   "....XXX.XXX....."  
  "\n"   "...XXX...XXX...."  
  "\n"   "..XXX.....XXX..."  
  "\n"   ".XXX.......XXX.."  
  "\n"   "XXX.........XXX."  
  "\n"   "XX...........XX." ,

  "=" /* UTF-8 3D - Glyph 29 */

  "\n"   "....XX..XX......"  
  "\n"   "....XX..XX......"  
  "\n"   "....XX..XX......"  
  "\n"   "....XX..XX......"  
  "\n"   "....XX..XX......"  
  "\n"   "....XX..XX......"  
  "\n"   "....XX..XX......"  
  "\n"   "....XX..XX......"  
  "\n"   "....XX..XX......"  
  "\n"   "....XX..XX......" ,

  ">" /* UTF-8 3E - Glyph 30 */

  "\n"   "................"  
  "\n"   "XX...........XX."  
  "\n"   "XXX.........XXX."  
  "\n"   ".XXX.......XXX.."  
  "\n"   "..XXX.....XXX..."  
  "\n"   "...XXX...XXX...."  
  "\n"   "....XXX.XXX....."  
  "\n"   ".....XXXXX......"  
  "\n"   "......XXX......." ,

  "?" /* UTF-8 3F - Glyph 31 */

  "\n"   "..........XX...."  
  "\n"   "..........XXX..."  
  "\n"   "...........XXX.."  
  "\n"   "............XX.."  
  "\n"   "XX..XX......XX.."  
  "\n"   "XX..XXX.....XX.."  
  "\n"   ".....XXX....XX.."  
  "\n"   "......XXX..XXX.."  
  "\n"   ".......XXXXXX..."  
  "\n"   "........XXXX...." ,

  "@" /* UTF-8 40 - Glyph 32 */

  "\n"   "...XXXXXXXX....."  
  "\n"   "..XX......XX...."  
  "\n"   ".XX..XXXX..XX..."  
  "\n"   ".X..XXXXXX..X..."  
  "\n"   ".X..X....X..X..."  
  "\n"   ".X..XXXXX...X..."  
  "\n"   ".X...XXXXX..X..."  
  "\n"   ".XX.X......XX..."  
  "\n"   "..X.XX....XX...."  
  "\n"   ".....XXXXXX....." ,

  "A" /* UTF-8 41 - Glyph 33 */

  "\n"   "XXXXXXXXXX......"  
  "\n"   "XXXXXXXXXXX....."  
  "\n"   "....XX...XXX...."  
  "\n"   "....XX....XXX..."  
  "\n"   "....XX.....XXX.."  
  "\n"   "....XX.....XXX.."  
  "\n"   "....XX....XXX..."  
  "\n"   "....XX...XXX...."  
  "\n"   "XXXXXXXXXXX....."  
  "\n"   "XXXXXXXXXX......" ,

  "À" /* UTF-8 C3 80 - Glyph 34 */

  "\n"   "XXXXXXXX........"  
  "\n"   "XXXXXXXXX......."  
  "\n"   "...XX..XXX.....X"  
  "\n"   "...XX...XXX...XX"  
  "\n"   "...XX....XXX..XX"  
  "\n"   "...XX....XXX.XX."  
  "\n"   "...XX...XXX..X.."  
  "\n"   "...XX..XXX......"  
  "\n"   "XXXXXXXXX......."  
  "\n"   "XXXXXXXX........" ,

  "Á" /* UTF-8 C3 81 - Glyph 35 */

  "\n"   "XXXXXXXX........"  
  "\n"   "XXXXXXXXX......."  
  "\n"   "...XX..XXX......"  
  "\n"   "...XX...XXX..X.."  
  "\n"   "...XX....XXX.XX."  
  "\n"   "...XX....XXX..XX"  
  "\n"   "...XX...XXX...XX"  
  "\n"   "...XX..XXX.....X"  
  "\n"   "XXXXXXXXX......."  
  "\n"   "XXXXXXXX........" ,

  "Â" /* UTF-8 C3 82 - Glyph 36 */

  "\n"   "XXXXXXXX........"  
  "\n"   "XXXXXXXXX......."  
  "\n"   "...XX..XXX...X.."  
  "\n"   "...XX...XXX..XX."  
  "\n"   "...XX....XXX..XX"  
  "\n"   "...XX....XXX..XX"  
  "\n"   "...XX...XXX..XX."  
  "\n"   "...XX..XXX...X.."  
  "\n"   "XXXXXXXXX......."  
  "\n"   "XXXXXXXX........" ,

  "Ä" /* UTF-8 C3 84 - Glyph 37 */

  "\n"   "XXXXXXXX........"  
  "\n"   "XXXXXXXXX......."  
  "\n"   "...XX..XXX....XX"  
  "\n"   "...XX...XXX...XX"  
  "\n"   "...XX....XXX...."  
  "\n"   "...XX....XXX...."  
  "\n"   "...XX...XXX...XX"  
  "\n"   "...XX..XXX....XX"  
  "\n"   "XXXXXXXXX......."  
  "\n"   "XXXXXXXX........" ,

  "B" /* UTF-8 42 - Glyph 38 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XXX..XXXX..XXX.."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "..XXXX..XXXX...." ,

  "C" /* UTF-8 43 - Glyph 39 */

  "\n"   "..XXXXXXXXXX...."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "XXX........XXX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XXX........XXX.."  
  "\n"   ".XXX......XXX..."  
  "\n"   "..XX......XX...." ,

  "D" /* UTF-8 44 - Glyph 40 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XXX........XXX.."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "..XXXXXXXXXX...." ,

  "E" /* UTF-8 45 - Glyph 41 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.." ,

  "È" /* UTF-8 C3 88 - Glyph 42 */

  "\n"   "XXXXXXXXXXXX...."  
  "\n"   "XXXXXXXXXXXX...."  
  "\n"   "XX...XX...XX...X"  
  "\n"   "XX...XX...XX..XX"  
  "\n"   "XX...XX...XX..XX"  
  "\n"   "XX...XX...XX.XX."  
  "\n"   "XX...XX...XX.X.."  
  "\n"   "XX...XX...XX...."  
  "\n"   "XX........XX...."  
  "\n"   "XX........XX...." ,

  "É" /* UTF-8 C3 89 - Glyph 43 */

  "\n"   "XXXXXXXXXXXX...."  
  "\n"   "XXXXXXXXXXXX...."  
  "\n"   "XX...XX...XX...."  
  "\n"   "XX...XX...XX.X.."  
  "\n"   "XX...XX...XX.XX."  
  "\n"   "XX...XX...XX..XX"  
  "\n"   "XX...XX...XX..XX"  
  "\n"   "XX...XX...XX...X"  
  "\n"   "XX........XX...."  
  "\n"   "XX........XX...." ,

  "Ê" /* UTF-8 C3 8A - Glyph 44 */

  "\n"   "XXXXXXXXXXXX...."  
  "\n"   "XXXXXXXXXXXX...."  
  "\n"   "XX...XX...XX.X.."  
  "\n"   "XX...XX...XX.XX."  
  "\n"   "XX...XX...XX..XX"  
  "\n"   "XX...XX...XX..XX"  
  "\n"   "XX...XX...XX.XX."  
  "\n"   "XX...XX...XX.X.."  
  "\n"   "XX........XX...."  
  "\n"   "XX........XX...." ,

  "F" /* UTF-8 46 - Glyph 45 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "......XX....XX.."  
  "\n"   "......XX....XX.."  
  "\n"   "......XX....XX.."  
  "\n"   "......XX....XX.."  
  "\n"   "......XX....XX.."  
  "\n"   "......XX....XX.."  
  "\n"   "............XX.."  
  "\n"   "............XX.." ,

  "G" /* UTF-8 47 - Glyph 46 */

  "\n"   "..XXXXXXXXXX...."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "XXX........XXX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XXX...XX...XXX.."  
  "\n"   ".XXXXXXX..XXX..."  
  "\n"   "..XXXXXX..XX...." ,

  "H" /* UTF-8 48 - Glyph 47 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "......XX........"  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.." ,

  "I" /* UTF-8 49 - Glyph 48 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.." ,

  "J" /* UTF-8 4A - Glyph 49 */

  "\n"   "..XX............"  
  "\n"   ".XXX............"  
  "\n"   "XXX............."  
  "\n"   "XX.............."  
  "\n"   "XX..........XX.."  
  "\n"   "XXX.........XX.."  
  "\n"   ".XXXXXXXXXXXXX.."  
  "\n"   "..XXXXXXXXXXXX.."  
  "\n"   "............XX.."  
  "\n"   "............XX.." ,

  "K" /* UTF-8 4B - Glyph 50 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "......XX........"  
  "\n"   ".....XXXX......."  
  "\n"   "....XXXXXX......"  
  "\n"   "...XXX..XXX....."  
  "\n"   "..XXX....XXX...."  
  "\n"   ".XXX......XXX..."  
  "\n"   "XXX........XXX.."  
  "\n"   "XX..........XX.." ,

  "L" /* UTF-8 4C - Glyph 51 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.............." ,

  "M" /* UTF-8 4D - Glyph 52 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   ".........XXX...."  
  "\n"   "........XXX....."  
  "\n"   "......XXXX......"  
  "\n"   "......XXXX......"  
  "\n"   "........XXX....."  
  "\n"   ".........XXX...."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.." ,

  "N" /* UTF-8 4E - Glyph 53 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "........XXX....."  
  "\n"   ".......XXX......"  
  "\n"   "......XXX......."  
  "\n"   ".....XXX........"  
  "\n"   "....XXX........."  
  "\n"   "...XXX.........."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.." ,

  "O" /* UTF-8 4F - Glyph 54 */

  "\n"   "..XXXXXXXXXX...."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "XXX........XXX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XXX........XXX.."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "..XXXXXXXXXX...." ,

  "Ö" /* UTF-8 C3 96 - Glyph 55 */

  "\n"   "..XXXXXXXX......"  
  "\n"   ".XXXXXXXXXX....."  
  "\n"   "XXX......XXX..XX"  
  "\n"   "XX........XX..XX"  
  "\n"   "XX........XX...."  
  "\n"   "XX........XX...."  
  "\n"   "XX........XX..XX"  
  "\n"   "XXX......XXX..XX"  
  "\n"   ".XXXXXXXXXX....."  
  "\n"   "..XXXXXXXX......" ,

  "P" /* UTF-8 50 - Glyph 56 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "......XX....XX.."  
  "\n"   "......XX....XX.."  
  "\n"   "......XX....XX.."  
  "\n"   "......XX....XX.."  
  "\n"   "......XX....XX.."  
  "\n"   "......XXX..XXX.."  
  "\n"   ".......XXXXXX..."  
  "\n"   "........XXXX...." ,

  "Q" /* UTF-8 51 - Glyph 57 */

  "\n"   "..XXXXXXXXXX...."  
  "\n"   ".XXXXXXXXXXXX..."  
  "\n"   "XXX........XXX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX..XX......XX.."  
  "\n"   "XX.XXX......XX.."  
  "\n"   ".XXXX.......XX.."  
  "\n"   ".XXX.......XXX.."  
  "\n"   "XXXXXXXXXXXXX..."  
  "\n"   "XX.XXXXXXXXX...." ,

  "R" /* UTF-8 52 - Glyph 58 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "......XX....XX.."  
  "\n"   ".....XXX....XX.."  
  "\n"   "....XXXX....XX.."  
  "\n"   "...XXXXX....XX.."  
  "\n"   "..XXX.XX....XX.."  
  "\n"   ".XXX..XXX..XXX.."  
  "\n"   "XXX....XXXXXX..."  
  "\n"   "XX......XXXX...." ,

  "S" /* UTF-8 53 - Glyph 59 */

  "\n"   "..XX....XXXX...."  
  "\n"   ".XXX...XXXXXX..."  
  "\n"   "XXX...XXX..XXX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XX....XX....XX.."  
  "\n"   "XXX..XXX...XXX.."  
  "\n"   ".XXXXXX...XXX..."  
  "\n"   "..XXXX....XX...." ,

  "T" /* UTF-8 54 - Glyph 60 */

  "\n"   "............XX.."  
  "\n"   "............XX.."  
  "\n"   "............XX.."  
  "\n"   "............XX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "............XX.."  
  "\n"   "............XX.."  
  "\n"   "............XX.."  
  "\n"   "............XX.." ,

  "U" /* UTF-8 55 - Glyph 61 */

  "\n"   "..XXXXXXXXXXXX.."  
  "\n"   ".XXXXXXXXXXXXX.."  
  "\n"   "XXX............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XXX............."  
  "\n"   ".XXXXXXXXXXXXX.."  
  "\n"   "..XXXXXXXXXXXX.." ,

  "Ü" /* UTF-8 C3 9C - Glyph 62 */

  "\n"   "..XXXXXXXXXX...."  
  "\n"   ".XXXXXXXXXXX...."  
  "\n"   "XXX...........XX"  
  "\n"   "XX............XX"  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX............XX"  
  "\n"   "XXX...........XX"  
  "\n"   ".XXXXXXXXXXX...."  
  "\n"   "..XXXXXXXXXX...." ,

  "V" /* UTF-8 56 - Glyph 63 */

  "\n"   "....XXXXXXXXXX.."  
  "\n"   "...XXXXXXXXXXX.."  
  "\n"   "..XXX..........."  
  "\n"   ".XXX............"  
  "\n"   "XXX............."  
  "\n"   "XXX............."  
  "\n"   ".XXX............"  
  "\n"   "..XXX..........."  
  "\n"   "...XXXXXXXXXXX.."  
  "\n"   "....XXXXXXXXXX.." ,

  "W" /* UTF-8 57 - Glyph 64 */

  "\n"   "..XXXXXXXXXXXX.."  
  "\n"   ".XXXXXXXXXXXXX.."  
  "\n"   "XXX............."  
  "\n"   "XXX............."  
  "\n"   ".XXXXXXX........"  
  "\n"   ".XXXXXXX........"  
  "\n"   "XXX............."  
  "\n"   "XXX............."  
  "\n"   ".XXXXXXXXXXXXX.."  
  "\n"   "..XXXXXXXXXXXX.." ,

  "X" /* UTF-8 58 - Glyph 65 */

  "\n"   "XXXX......XXXX.."  
  "\n"   "XXXXX....XXXXX.."  
  "\n"   "...XXX..XXX....."  
  "\n"   "....XXXXXX......"  
  "\n"   ".....XXXX......."  
  "\n"   ".....XXXX......."  
  "\n"   "....XXXXXX......"  
  "\n"   "...XXX..XXX....."  
  "\n"   "XXXXX....XXXXX.."  
  "\n"   "XXXX......XXXX.." ,

  "Y" /* UTF-8 59 - Glyph 66 */

  "\n"   "........XXXXXX.."  
  "\n"   ".......XXXXXXX.."  
  "\n"   "......XXX......."  
  "\n"   ".....XXX........"  
  "\n"   "XXXXXXX........."  
  "\n"   "XXXXXXX........."  
  "\n"   ".....XXX........"  
  "\n"   "......XXX......."  
  "\n"   ".......XXXXXXX.."  
  "\n"   "........XXXXXX.." ,

  "Z" /* UTF-8 5A - Glyph 67 */

  "\n"   "XXXX........XX.."  
  "\n"   "XXXXX.......XX.."  
  "\n"   "XX.XXX......XX.."  
  "\n"   "XX..XXX.....XX.."  
  "\n"   "XX...XXX....XX.."  
  "\n"   "XX....XXX...XX.."  
  "\n"   "XX.....XXX..XX.."  
  "\n"   "XX......XXX.XX.."  
  "\n"   "XX.......XXXXX.."  
  "\n"   "XX........XXXX.." ,

  "[" /* UTF-8 5B - Glyph 68 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "XXXXXXXXXXXXXXXX"  
  "\n"   "XXXXXXXXXXXXXXXX"  
  "\n"   "XX............XX"  
  "\n"   "XX............XX"  
  "\n"   "XX............XX"  
  "\n"   "XX............XX" ,

  "\\" /* UTF-8 5C - Glyph 69 */

  "\n"   "..........XXXX.."  
  "\n"   ".........XXXXX.."  
  "\n"   "........XXX....."  
  "\n"   ".......XXX......"  
  "\n"   "......XXX......."  
  "\n"   ".....XXX........"  
  "\n"   "....XXX........."  
  "\n"   "...XXX.........."  
  "\n"   "XXXXX..........."  
  "\n"   "XXXX............" ,

  "]" /* UTF-8 5D - Glyph 70 */

  "\n"   "................"  
  "\n"   "XX............XX"  
  "\n"   "XX............XX"  
  "\n"   "XX............XX"  
  "\n"   "XX............XX"  
  "\n"   "XXXXXXXXXXXXXXXX"  
  "\n"   "XXXXXXXXXXXXXXXX" ,

  "^" /* UTF-8 5E - Glyph 71 */

  "\n"   ".........X......"  
  "\n"   ".........XX....."  
  "\n"   ".........XXX...."  
  "\n"   "..........XXX..."  
  "\n"   "...........XXX.."  
  "\n"   "...........XXX.."  
  "\n"   "..........XXX..."  
  "\n"   ".........XXX...."  
  "\n"   ".........XX....."  
  "\n"   ".........X......" ,

  "_" /* UTF-8 5F - Glyph 72 */

  "\n"   "X..............."  
  "\n"   "X..............."  
  "\n"   "X..............."  
  "\n"   "X..............."  
  "\n"   "X..............."  
  "\n"   "X..............."  
  "\n"   "X..............."  
  "\n"   "X..............."  
  "\n"   "X..............."  
  "\n"   "X..............."  
  "\n"   "X..............." ,

  "`" /* UTF-8 60 - Glyph 73 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   ".............X.."  
  "\n"   "............XX.."  
  "\n"   "............XX.."  
  "\n"   "...........XX..."  
  "\n"   "...........X...." ,

  "a" /* UTF-8 61 - Glyph 74 */

  "\n"   "..XXXX.........."  
  "\n"   ".XXXXXX........."  
  "\n"   "XXX..XXX..XX...."  
  "\n"   "XX....XX..XX...."  
  "\n"   "XX....XX..XX...."  
  "\n"   "XX....XX..XX...."  
  "\n"   "XX....XX..XX...."  
  "\n"   ".XX..XX..XXX...."  
  "\n"   "XXXXXXXXXXX....."  
  "\n"   "XXXXXXXXXX......" ,

  "à" /* UTF-8 C3 A0 - Glyph 75 */

  "\n"   "..XXX..........."  
  "\n"   ".XXXXX.........."  
  "\n"   "XXX.XXX.XX...X.."  
  "\n"   "XX...XX.XX..XX.."  
  "\n"   "XX...XX.XX..XX.."  
  "\n"   "XX...XX.XX.XX..."  
  "\n"   "XX...XX.XX.X...."  
  "\n"   ".XX.XX..XX......"  
  "\n"   "XXXXXXXXX......."  
  "\n"   "XXXXXXXX........" ,

  "á" /* UTF-8 C3 A1 - Glyph 76 */

  "\n"   "..XXX..........."  
  "\n"   ".XXXXX.........."  
  "\n"   "XXX.XXX.XX......"  
  "\n"   "XX...XX.XX.X...."  
  "\n"   "XX...XX.XX.XX..."  
  "\n"   "XX...XX.XX..XX.."  
  "\n"   "XX...XX.XX..XX.."  
  "\n"   ".XX.XX..XX...X.."  
  "\n"   "XXXXXXXXX......."  
  "\n"   "XXXXXXXX........" ,

  "â" /* UTF-8 C3 A2 - Glyph 77 */

  "\n"   "..XXX..........."  
  "\n"   ".XXXXX.........."  
  "\n"   "XXX.XXX.XX.X...."  
  "\n"   "XX...XX.XX.XX..."  
  "\n"   "XX...XX.XX..XX.."  
  "\n"   "XX...XX.XX..XX.."  
  "\n"   "XX...XX.XX.XX..."  
  "\n"   ".XX.XX..XX.X...."  
  "\n"   "XXXXXXXXX......."  
  "\n"   "XXXXXXXX........" ,

  "ä" /* UTF-8 C3 A4 - Glyph 78 */

  "\n"   "..XXX..........."  
  "\n"   ".XXXXX.........."  
  "\n"   "XXX.XXX.XX..XX.."  
  "\n"   "XX...XX.XX..XX.."  
  "\n"   "XX...XX.XX......"  
  "\n"   "XX...XX.XX......"  
  "\n"   "XX...XX.XX..XX.."  
  "\n"   ".XX.XX..XX..XX.."  
  "\n"   "XXXXXXXXX......."  
  "\n"   "XXXXXXXX........" ,

  "b" /* UTF-8 62 - Glyph 79 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "..XXXXXXX......."  
  "\n"   ".XXX...XXX......"  
  "\n"   "XXX.....XXX....."  
  "\n"   "XX.......XX....."  
  "\n"   "XXX.....XXX....."  
  "\n"   ".XXX...XXX......"  
  "\n"   "..XXXXXXX......."  
  "\n"   "...XXXXX........" ,

  "c" /* UTF-8 63 - Glyph 80 */

  "\n"   "..XXXXXXX......."  
  "\n"   ".XXXXXXXXX......"  
  "\n"   "XXX.....XXX....."  
  "\n"   "XX.......XX....."  
  "\n"   "XX.......XX....."  
  "\n"   "XX.......XX....."  
  "\n"   "XX.......XX....."  
  "\n"   "XXX.....XXX....."  
  "\n"   ".XXX...XXX......"  
  "\n"   "..XX...XX......." ,

  "ç" /* UTF-8 C3 A7 - Glyph 81 */

  "\n"   ".....XXXXXX....."  
  "\n"   "....XXXXXXXX...."  
  "\n"   "X..XXX....XXX..."  
  "\n"   "XX.XX......XX..."  
  "\n"   "XXXXX......XX..."  
  "\n"   ".XXXX......XX..."  
  "\n"   "..XXX......XX..."  
  "\n"   "...XXX....XXX..."  
  "\n"   "....XXX..XXX...."  
  "\n"   ".....XX..XX....." ,

  "d" /* UTF-8 64 - Glyph 82 */

  "\n"   "...XXXXX........"  
  "\n"   "..XXXXXXX......."  
  "\n"   ".XXX...XXX......"  
  "\n"   "XXX.....XXX....."  
  "\n"   "XX.......XX....."  
  "\n"   "XXX.....XXX....."  
  "\n"   ".XXX...XXX......"  
  "\n"   "..XXXXXXX......."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.." ,

  "e" /* UTF-8 65 - Glyph 83 */

  "\n"   "..XXXXXXX......."  
  "\n"   ".XXXXXXXXX......"  
  "\n"   "XXX..XX.XXX....."  
  "\n"   "XX...XX..XX....."  
  "\n"   "XX...XX..XX....."  
  "\n"   "XX...XX..XX....."  
  "\n"   "XX...XX..XX....."  
  "\n"   "XXX..XX.XXX....."  
  "\n"   ".XX..XXXXX......"  
  "\n"   "..X...XXX......." ,

  "è" /* UTF-8 C3 A8 - Glyph 84 */

  "\n"   "..XXXXXX........"  
  "\n"   ".XXXXXXXX......."  
  "\n"   "XXX.XX.XXX...X.."  
  "\n"   "XX..XX..XX..XX.."  
  "\n"   "XX..XX..XX..XX.."  
  "\n"   "XX..XX..XX.XX..."  
  "\n"   "XX..XX..XX.X...."  
  "\n"   "XXX.XX.XXX......"  
  "\n"   ".XX.XXXXX......."  
  "\n"   "..X..XXX........" ,

  "é" /* UTF-8 C3 A9 - Glyph 85 */

  "\n"   "..XXXXXX........"  
  "\n"   ".XXXXXXXX......."  
  "\n"   "XXX.XX.XXX......"  
  "\n"   "XX..XX..XX.X...."  
  "\n"   "XX..XX..XX.XX..."  
  "\n"   "XX..XX..XX..XX.."  
  "\n"   "XX..XX..XX..XX.."  
  "\n"   "XXX.XX.XXX...X.."  
  "\n"   ".XX.XXXXX......."  
  "\n"   "..X..XXX........" ,

  "ê" /* UTF-8 C3 AA - Glyph 86 */

  "\n"   "..XXXXXX........"  
  "\n"   ".XXXXXXXX......."  
  "\n"   "XXX.XX.XXX.X...."  
  "\n"   "XX..XX..XX.XX..."  
  "\n"   "XX..XX..XX..XX.."  
  "\n"   "XX..XX..XX..XX.."  
  "\n"   "XX..XX..XX.XX..."  
  "\n"   "XXX.XX.XXX.X...."  
  "\n"   ".XX.XXXXX......."  
  "\n"   "..X..XXX........" ,

  "ë" /* UTF-8 C3 AB - Glyph 87 */

  "\n"   "..XXXXXX........"  
  "\n"   ".XXXXXXXX......."  
  "\n"   "XXX.XX.XXX..XX.."  
  "\n"   "XX..XX..XX..XX.."  
  "\n"   "XX..XX..XX......"  
  "\n"   "XX..XX..XX......"  
  "\n"   "XX..XX..XX..XX.."  
  "\n"   "XXX.XX.XXX..XX.."  
  "\n"   ".XX.XXXXX......."  
  "\n"   "..X..XXX........" ,

  "f" /* UTF-8 66 - Glyph 88 */

  "\n"   "................"  
  "\n"   ".........XX....."  
  "\n"   ".........XX....."  
  "\n"   ".........XX....."  
  "\n"   "XXXXXXXXXXXXX..."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   ".........XX.XX.."  
  "\n"   ".........XX.XX.."  
  "\n"   ".........XX.XX.." ,

  "g" /* UTF-8 67 - Glyph 89 */

  "\n"   ".......XXX......"  
  "\n"   ".XX...XXXXX....."  
  "\n"   "XXX..XXX.XXX...."  
  "\n"   "XX...XX...XX...."  
  "\n"   "XX...XX...XX...."  
  "\n"   "XX...XX...XX...."  
  "\n"   "XX...XX...XX...."  
  "\n"   "XXX...XX.XXX...."  
  "\n"   ".XXXXXXXXXX....."  
  "\n"   "..XXXXXXXX......" ,

  "h" /* UTF-8 68 - Glyph 90 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "......XXX......."  
  "\n"   ".......XXX......"  
  "\n"   "........XXX....."  
  "\n"   ".........XX....."  
  "\n"   "........XXX....."  
  "\n"   ".......XXX......"  
  "\n"   "XXXXXXXXX......."  
  "\n"   "XXXXXXXX........" ,

  "i" /* UTF-8 69 - Glyph 91 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   ".......XX......."  
  "\n"   ".......XX......."  
  "\n"   "..XXXXXXX..XX..."  
  "\n"   ".XXXXXXXX..XX..."  
  "\n"   "XXX............."  
  "\n"   "XX.............." ,

  "ì" /* UTF-8 C3 AC - Glyph 92 */

  "\n"   "................"  
  "\n"   ".............X.."  
  "\n"   ".......XX...XX.."  
  "\n"   ".......XX...XX.."  
  "\n"   "..XXXXXXX..XX..."  
  "\n"   ".XXXXXXXX..X...."  
  "\n"   "XXX............."  
  "\n"   "XX.............." ,

  "í" /* UTF-8 C3 AD - Glyph 93 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   ".......XX......."  
  "\n"   ".......XX..X...."  
  "\n"   "..XXXXXXX..XX..."  
  "\n"   ".XXXXXXXX...XX.."  
  "\n"   "XXX.........XX.."  
  "\n"   "XX...........X.." ,

  "î" /* UTF-8 C3 AE - Glyph 94 */

  "\n"   "................"  
  "\n"   "...........X...."  
  "\n"   ".......XX..XX..."  
  "\n"   ".......XX...XX.."  
  "\n"   "..XXXXXXX...XX.."  
  "\n"   ".XXXXXXXX..XX..."  
  "\n"   "XXX........X...."  
  "\n"   "XX.............." ,

  "ï" /* UTF-8 C3 AF - Glyph 95 */

  "\n"   "................"  
  "\n"   "............XX.."  
  "\n"   ".......XX...XX.."  
  "\n"   ".......XX......."  
  "\n"   "..XXXXXXX......."  
  "\n"   ".XXXXXXXX...XX.."  
  "\n"   "XXX.........XX.."  
  "\n"   "XX.............." ,

  "j" /* UTF-8 6A - Glyph 96 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.......XX....."  
  "\n"   "XXX......XX....."  
  "\n"   ".XXXXXXXXXX..XX."  
  "\n"   "..XXXXXXXXX..XX." ,

  "k" /* UTF-8 6B - Glyph 97 */

  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "..XXX..........."  
  "\n"   "...XXX.........."  
  "\n"   "....XXX........."  
  "\n"   "...XXXXX........"  
  "\n"   "..XXX.XXX......."  
  "\n"   ".XXX...XXX......"  
  "\n"   "XXX.....XXX....."  
  "\n"   "XX.......XX....." ,

  "l" /* UTF-8 6C - Glyph 98 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "XXXXXXXXXXXXXX.."  
  "\n"   "XXXXXXXXXXXXXX.." ,

  "m" /* UTF-8 6D - Glyph 99 */

  "\n"   "XXXXXXXXXXX....."  
  "\n"   "XXXXXXXXXXX....."  
  "\n"   "........XX......"  
  "\n"   ".........XX....."  
  "\n"   "XXXXXXXXXXX....."  
  "\n"   "XXXXXXXXXXX....."  
  "\n"   ".........XX....."  
  "\n"   "........XXX....."  
  "\n"   "XXXXXXXXXX......"  
  "\n"   "XXXXXXXXX......." ,

  "n" /* UTF-8 6E - Glyph 100 */

  "\n"   "XXXXXXXXXXX....."  
  "\n"   "XXXXXXXXXXX....."  
  "\n"   "........XX......"  
  "\n"   ".........XX....."  
  "\n"   ".........XX....."  
  "\n"   ".........XX....."  
  "\n"   ".........XX....."  
  "\n"   "........XXX....."  
  "\n"   "XXXXXXXXXX......"  
  "\n"   "XXXXXXXXX......." ,

  "o" /* UTF-8 6F - Glyph 101 */

  "\n"   "..XXXXXXX......."  
  "\n"   ".XXXXXXXXX......"  
  "\n"   "XXX.....XXX....."  
  "\n"   "XX.......XX....."  
  "\n"   "XX.......XX....."  
  "\n"   "XX.......XX....."  
  "\n"   "XX.......XX....."  
  "\n"   "XXX.....XXX....."  
  "\n"   ".XXXXXXXXX......"  
  "\n"   "..XXXXXXX......." ,

  "ö" /* UTF-8 C3 B6 - Glyph 102 */

  "\n"   "..XXXXXX........"  
  "\n"   ".XXXXXXXX......."  
  "\n"   "XXX....XXX..XX.."  
  "\n"   "XX......XX..XX.."  
  "\n"   "XX......XX......"  
  "\n"   "XX......XX......"  
  "\n"   "XX......XX..XX.."  
  "\n"   "XXX....XXX..XX.."  
  "\n"   ".XXXXXXXX......."  
  "\n"   "..XXXXXX........" ,

  "p" /* UTF-8 70 - Glyph 103 */

  "\n"   "XXXXXXXXXXXX...."  
  "\n"   "XXXXXXXXXXXX...."  
  "\n"   "....XXXXXXX....."  
  "\n"   "...XXX...XXX...."  
  "\n"   "...XX.....XX...."  
  "\n"   "...XX.....XX...."  
  "\n"   "...XX.....XX...."  
  "\n"   "...XXX...XXX...."  
  "\n"   "....XXXXXXX....."  
  "\n"   ".....XXXXX......" ,

  "placeholder" /* UTF-8 70 6C 61 63 65 68 6F 6C 64 65 72 - Glyph 104 */

  "\n"   "XXXXXXXXXXXXXXXX"  
  "\n"   "X..............X"  
  "\n"   "X..............X"  
  "\n"   "X..............X"  
  "\n"   "X..............X"  
  "\n"   "X..............X"  
  "\n"   "X..............X"  
  "\n"   "X..............X"  
  "\n"   "XXXXXXXXXXXXXXXX" ,

  "q" /* UTF-8 71 - Glyph 105 */

  "\n"   ".....XXXXX......"  
  "\n"   "....XXXXXXX....."  
  "\n"   "...XXX...XXX...."  
  "\n"   "...XX.....XX...."  
  "\n"   "...XX.....XX...."  
  "\n"   "...XX.....XX...."  
  "\n"   "....XX...XXX...."  
  "\n"   "...XXXXXXXX....."  
  "\n"   "XXXXXXXXXXXX...."  
  "\n"   "XXXXXXXXXXXX...." ,

  "r" /* UTF-8 72 - Glyph 106 */

  "\n"   "XXXXXXXXXXX....."  
  "\n"   "XXXXXXXXXXX....."  
  "\n"   "......XXX......."  
  "\n"   ".......XXX......"  
  "\n"   "........XXX....."  
  "\n"   ".........XX....."  
  "\n"   ".........XX....."  
  "\n"   "........XXX....."  
  "\n"   ".......XXX......"  
  "\n"   ".......XX......." ,

  "s" /* UTF-8 73 - Glyph 107 */

  "\n"   "..XX...XX......."  
  "\n"   ".XXX..XXXX......"  
  "\n"   "XXX...XXXXX....."  
  "\n"   "XX...XX..XX....."  
  "\n"   "XX...XX..XX....."  
  "\n"   "XX..XXX..XX....."  
  "\n"   "XX..XX...XX....."  
  "\n"   "XXXXXX..XXX....."  
  "\n"   ".XXXX..XXX......"  
  "\n"   "..XX...XX......." ,

  "t" /* UTF-8 74 - Glyph 108 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   ".........XX....."  
  "\n"   ".........XX....."  
  "\n"   "..XXXXXXXXXXXX.."  
  "\n"   ".XXXXXXXXXXXXX.."  
  "\n"   "XXX......XX....."  
  "\n"   "XX.......XX....." ,

  "u" /* UTF-8 75 - Glyph 109 */

  "\n"   "..XXXXXXXXX....."  
  "\n"   ".XXXXXXXXXX....."  
  "\n"   "XXX............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XXX............."  
  "\n"   ".XXXXXXXXXX....."  
  "\n"   "..XXXXXXXXX....." ,

  "ü" /* UTF-8 C3 BC - Glyph 110 */

  "\n"   "..XXXXXXXX......"  
  "\n"   ".XXXXXXXXX......"  
  "\n"   "XXX.........XX.."  
  "\n"   "XX..........XX.."  
  "\n"   "XX.............."  
  "\n"   "XX.............."  
  "\n"   "XX..........XX.."  
  "\n"   "XXX.........XX.."  
  "\n"   ".XXXXXXXXX......"  
  "\n"   "..XXXXXXXX......" ,

  "v" /* UTF-8 76 - Glyph 111 */

  "\n"   "....XXXXXXX....."  
  "\n"   "...XXXXXXXX....."  
  "\n"   "..XXX..........."  
  "\n"   ".XXX............"  
  "\n"   "XXX............."  
  "\n"   "XXX............."  
  "\n"   ".XXX............"  
  "\n"   "..XXX..........."  
  "\n"   "...XXXXXXXX....."  
  "\n"   "....XXXXXXX....." ,

  "w" /* UTF-8 77 - Glyph 112 */

  "\n"   "..XXXXXXXXX....."  
  "\n"   ".XXXXXXXXXX....."  
  "\n"   "XXX............."  
  "\n"   "XX.............."  
  "\n"   ".XXXXXX........."  
  "\n"   ".XXXXXX........."  
  "\n"   "XX.............."  
  "\n"   "XXX............."  
  "\n"   ".XXXXXXXXXX....."  
  "\n"   "..XXXXXXXXX....." ,

  "x" /* UTF-8 78 - Glyph 113 */

  "\n"   "XX.......XX....."  
  "\n"   "XXX.....XXX....."  
  "\n"   ".XXX...XXX......"  
  "\n"   "..XXX.XXX......."  
  "\n"   "...XXXXX........"  
  "\n"   "...XXXXX........"  
  "\n"   "..XXX.XXX......."  
  "\n"   ".XXX...XXX......"  
  "\n"   "XXX.....XXX....."  
  "\n"   "XX.......XX....." ,

  "y" /* UTF-8 79 - Glyph 114 */

  "\n"   "......XXXXXX...."  
  "\n"   ".....XXXXXXX...."  
  "\n"   "XX..XXX........."  
  "\n"   "XX..XX.........."  
  "\n"   "XX..XX.........."  
  "\n"   "XX..XXX........."  
  "\n"   "XX...XXX........"  
  "\n"   "XXX...XXXX......"  
  "\n"   ".XXXXXXXXXXX...."  
  "\n"   "..XXXXXXXXXX...." ,

  "z" /* UTF-8 7A - Glyph 115 */

  "\n"   "XX.......XX....."  
  "\n"   "XXX......XX....."  
  "\n"   "XXXX.....XX....."  
  "\n"   "XXXXX....XX....."  
  "\n"   "XX.XXX...XX....."  
  "\n"   "XX..XXX..XX....."  
  "\n"   "XX...XXX.XX....."  
  "\n"   "XX....XXXXX....."  
  "\n"   "XX.....XXXX....."  
  "\n"   "XX......XXX....." ,

  "{" /* UTF-8 7B - Glyph 116 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   ".......XX......."  
  "\n"   ".......XX......."  
  "\n"   "..XXXXXXXXXXXX.."  
  "\n"   "XXXXXXX..XXXXXXX"  
  "\n"   "XXX..........XXX"  
  "\n"   "XXX..........XXX" ,

  "|" /* UTF-8 7C - Glyph 117 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "................"  
  "\n"   "XXXXXXXXXXXXXXXX"  
  "\n"   "XXXXXXXXXXXXXXXX" ,

  "}" /* UTF-8 7D - Glyph 118 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "XXX..........XXX"  
  "\n"   "XXX..........XXX"  
  "\n"   "XXXXXXX..XXXXXXX"  
  "\n"   "..XXXXXXXXXXXX.."  
  "\n"   ".......XX......."  
  "\n"   ".......XX......." ,

  "~" /* UTF-8 7E - Glyph 119 */

  "\n"   ".....XX........."  
  "\n"   "......XX........"  
  "\n"   ".......XX......."  
  "\n"   ".......XX......."  
  "\n"   "......XXX......."  
  "\n"   ".....XXX........"  
  "\n"   ".....XX........."  
  "\n"   ".....XX........."  
  "\n"   "......XX........"  
  "\n"   ".......XX......." ,

  "–" /* UTF-8 E2 80 93 - Glyph 120 */

  "\n"   "....XX.........."  
  "\n"   "....XX.........."  
  "\n"   "....XX.........."  
  "\n"   "....XX.........."  
  "\n"   "....XX.........."  
  "\n"   "....XX.........."  
  "\n"   "....XX.........."  
  "\n"   "....XX.........."  
  "\n"   "....XX.........."  
  "\n"   "....XX.........."  
  "\n"   "....XX.........." ,

  "’" /* UTF-8 E2 80 99 - Glyph 121 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "........X..XXX.."  
  "\n"   ".........XXXXX.."  
  "\n"   "..........XXXX.." ,

  "•" /* UTF-8 E2 80 A2 - Glyph 122 */

  "\n"   "................"  
  "\n"   "................"  
  "\n"   "......XXX......."  
  "\n"   ".....XXXXX......"  
  "\n"   ".....XXXXX......"  
  "\n"   ".....XXXXX......"  
  "\n"   ".....XXXXX......"  
  "\n"   "......XXX......." ,

  nullptr // terminator
};

// MARK: - end of generated font verification data


#endif // GENERATE_FONT_SOURCE


// MARK: - 'vcr_osd_mono' generated font data

static const glyph_t font_vcr_osd_mono_glyphs[] = {
  {  9, "\xff\xff\x80\x01\x80\x01\x80\x01\x80\x01\x80\x01\x80\x01\x80\x01\xff\xff" },  // placeholder          (input # 6 -> glyph # 0)
  {  9, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" },  // ' ' UTF-8 20         (input # 49 -> glyph # 1)
  {  5, "\x00\x00\x00\x00\x00\x00\xcf\xfc\xcf\xfc" },  // '!' UTF-8 21         (input # 52 -> glyph # 2)
  {  9, "\x00\x00\x00\x1c\x00\x3c\x00\x1c\x00\x00\x00\x00\x00\x1c\x00\x3c\x00\x1c" },  // '"' UTF-8 22         (input # 55 -> glyph # 3)
  { 10, "\x18\xc0\x18\xc0\x7f\xf8\x7f\xf8\x0c\x60\x0c\x60\x3f\xfc\x3f\xfc\x06\x30\x06\x30" },  // '#' UTF-8 23         (input # 58 -> glyph # 4)
  { 10, "\x18\xe0\x39\xf0\x73\xb8\x63\x18\xff\xfc\xff\xfc\x63\x18\x77\x38\x3e\x70\x1c\x60" },  // '$' UTF-8 24         (input # 60 -> glyph # 5)
  { 10, "\xf0\x78\xf8\xfc\x1c\xcc\x0e\xfc\x07\x78\x7b\x80\xfd\xc0\xcc\xe0\xfc\x7c\x78\x3c" },  // '%' UTF-8 25         (input # 62 -> glyph # 6)
  { 10, "\x3e\x00\x7f\x3c\xe3\xfe\xc3\xc3\xc7\x83\xcf\xc3\xfc\xfe\x78\x3c\xfc\x00\xcc\x00" },  // '&' UTF-8 26         (input # 64 -> glyph # 7)
  {  6, "\x00\x00\x00\x00\x00\x00\x00\x1c\x00\x3c\x00\x1c" },  // ''' UTF-8 27         (input # 66 -> glyph # 8)
  {  7, "\x00\x00\x00\x00\x1f\xf8\x3f\xfc\x60\x06\xc0\x03\x80\x01" },  // '(' UTF-8 28         (input # 68 -> glyph # 9)
  {  8, "\x00\x00\x00\x00\x00\x00\x80\x01\xc0\x03\x60\x06\x3f\xfc\x1f\xf8" },  // ')' UTF-8 29         (input # 70 -> glyph # 10)
  {  9, "\x00\x00\x01\x8c\x00\xd8\x00\x70\x03\xfe\x03\xfe\x00\x70\x00\xd8\x01\x8c" },  // '*' UTF-8 2A         (input # 72 -> glyph # 11)
  { 10, "\x03\x00\x03\x00\x03\x00\x03\x00\x3f\xf0\x3f\xf0\x03\x00\x03\x00\x03\x00\x03\x00" },  // '+' UTF-8 2B         (input # 74 -> glyph # 12)
  {  6, "\x00\x00\x00\x00\x80\x00\xc0\x00\x70\x00\x30\x00" },  // ',' UTF-8 2C         (input # 75 -> glyph # 13)
  {  9, "\x00\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00" },  // '-' UTF-8 2D         (input # 76 -> glyph # 14)
  {  5, "\x00\x00\x00\x00\x00\x00\xc0\x00\xc0\x00" },  // '.' UTF-8 2E         (input # 77 -> glyph # 15)
  { 10, "\xf0\x00\xf8\x00\x1c\x00\x0e\x00\x07\x00\x03\x80\x01\xc0\x00\xe0\x00\x7c\x00\x3c" },  // '/' UTF-8 2F         (input # 79 -> glyph # 16)
  { 10, "\x3f\xf0\x7f\xf8\xec\x1c\xce\x0c\xc7\x0c\xc3\x8c\xc1\xcc\xe0\xdc\x7f\xf8\x3f\xf0" },  // '0' UTF-8 30         (input # 80 -> glyph # 17)
  {  8, "\x00\x00\x00\x00\xc0\x30\xc0\x38\xff\xfc\xff\xfc\xc0\x00\xc0\x00" },  // '1' UTF-8 31         (input # 81 -> glyph # 18)
  { 10, "\xfc\x30\xfe\x38\xc7\x1c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x9c\xc1\xf8\xc0\xf0" },  // '2' UTF-8 32         (input # 82 -> glyph # 19)
  { 10, "\x30\x30\x70\x38\xe0\x1c\xc0\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe7\x9c\x7f\xf8\x3c\xf0" },  // '3' UTF-8 33         (input # 83 -> glyph # 20)
  { 10, "\x0f\x00\x0f\x80\x0d\xc0\x0c\xe0\x0c\x70\x0c\x38\xff\xfc\xff\xfc\x0c\x00\x0c\x00" },  // '4' UTF-8 34         (input # 84 -> glyph # 21)
  { 10, "\x30\xfc\x70\xfc\xe0\xcc\xc0\xcc\xc0\xcc\xc0\xcc\xc0\xcc\xe1\xcc\x7f\x8c\x3f\x0c" },  // '5' UTF-8 35         (input # 86 -> glyph # 22)
  { 10, "\x3f\xf0\x7f\xf8\xe3\x1c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe7\x1c\x7e\x38\x3c\x30" },  // '6' UTF-8 36         (input # 87 -> glyph # 23)
  { 10, "\x00\x0c\x00\x0c\x00\x0c\x00\x0c\xfe\x0c\xff\x0c\x03\x8c\x01\xcc\x00\xfc\x00\x7c" },  // '7' UTF-8 37         (input # 88 -> glyph # 24)
  { 10, "\x3c\xf0\x7f\xf8\xe7\x9c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe7\x9c\x7f\xf8\x3c\xf0" },  // '8' UTF-8 38         (input # 89 -> glyph # 25)
  { 10, "\x30\xf0\x71\xf8\xe3\x9c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe3\x1c\x7f\xf8\x3f\xf0" },  // '9' UTF-8 39         (input # 91 -> glyph # 26)
  {  5, "\x00\x00\x00\x00\x00\x00\x30\x30\x30\x30" },  // ':' UTF-8 3A         (input # 93 -> glyph # 27)
  {  5, "\x00\x00\x80\x00\xc0\x00\x70\x30\x30\x30" },  // ';' UTF-8 3B         (input # 95 -> glyph # 28)
  {  9, "\x00\x00\x03\x80\x07\xc0\x0e\xe0\x1c\x70\x38\x38\x70\x1c\xe0\x0e\xc0\x06" },  // '<' UTF-8 3C         (input # 96 -> glyph # 29)
  { 10, "\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0" },  // '=' UTF-8 3D         (input # 98 -> glyph # 30)
  {  9, "\x00\x00\xc0\x06\xe0\x0e\x70\x1c\x38\x38\x1c\x70\x0e\xe0\x07\xc0\x03\x80" },  // '>' UTF-8 3E         (input # 99 -> glyph # 31)
  { 10, "\x00\x30\x00\x38\x00\x1c\x00\x0c\xcc\x0c\xce\x0c\x07\x0c\x03\x9c\x01\xf8\x00\xf0" },  // '?' UTF-8 3F         (input # 100 -> glyph # 32)
  { 10, "\x1f\xe0\x30\x30\x67\x98\x4f\xc8\x48\x48\x4f\x88\x47\xc8\x68\x18\x2c\x30\x07\xe0" },  // '@' UTF-8 40         (input # 102 -> glyph # 33)
  { 10, "\xff\xc0\xff\xe0\x0c\x70\x0c\x38\x0c\x1c\x0c\x1c\x0c\x38\x0c\x70\xff\xe0\xff\xc0" },  // 'A' UTF-8 41         (input # 104 -> glyph # 34)
  { 10, "\xff\xfc\xff\xfc\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe7\x9c\x7f\xf8\x3c\xf0" },  // 'B' UTF-8 42         (input # 106 -> glyph # 35)
  { 10, "\x3f\xf0\x7f\xf8\xe0\x1c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xe0\x1c\x70\x38\x30\x30" },  // 'C' UTF-8 43         (input # 108 -> glyph # 36)
  { 10, "\xff\xfc\xff\xfc\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xe0\x1c\x7f\xf8\x3f\xf0" },  // 'D' UTF-8 44         (input # 110 -> glyph # 37)
  { 10, "\xff\xfc\xff\xfc\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xc0\x0c\xc0\x0c" },  // 'E' UTF-8 45         (input # 112 -> glyph # 38)
  { 10, "\xff\xfc\xff\xfc\x03\x0c\x03\x0c\x03\x0c\x03\x0c\x03\x0c\x03\x0c\x00\x0c\x00\x0c" },  // 'F' UTF-8 46         (input # 114 -> glyph # 39)
  { 10, "\x3f\xf0\x7f\xf8\xe0\x1c\xc0\x0c\xc0\x0c\xc3\x0c\xc3\x0c\xe3\x1c\x7f\x38\x3f\x30" },  // 'G' UTF-8 47         (input # 116 -> glyph # 40)
  { 10, "\xff\xfc\xff\xfc\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\xff\xfc\xff\xfc" },  // 'H' UTF-8 48         (input # 118 -> glyph # 41)
  {  8, "\x00\x00\x00\x00\xc0\x0c\xc0\x0c\xff\xfc\xff\xfc\xc0\x0c\xc0\x0c" },  // 'I' UTF-8 49         (input # 119 -> glyph # 42)
  { 10, "\x30\x00\x70\x00\xe0\x00\xc0\x00\xc0\x0c\xe0\x0c\x7f\xfc\x3f\xfc\x00\x0c\x00\x0c" },  // 'J' UTF-8 4A         (input # 120 -> glyph # 43)
  { 10, "\xff\xfc\xff\xfc\x03\x00\x07\x80\x0f\xc0\x1c\xe0\x38\x70\x70\x38\xe0\x1c\xc0\x0c" },  // 'K' UTF-8 4B         (input # 121 -> glyph # 44)
  { 10, "\xff\xfc\xff\xfc\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00" },  // 'L' UTF-8 4C         (input # 122 -> glyph # 45)
  { 10, "\xff\xfc\xff\xfc\x00\x70\x00\xe0\x03\xc0\x03\xc0\x00\xe0\x00\x70\xff\xfc\xff\xfc" },  // 'M' UTF-8 4D         (input # 123 -> glyph # 46)
  { 10, "\xff\xfc\xff\xfc\x00\xe0\x01\xc0\x03\x80\x07\x00\x0e\x00\x1c\x00\xff\xfc\xff\xfc" },  // 'N' UTF-8 4E         (input # 1 -> glyph # 47)
  { 10, "\x3f\xf0\x7f\xf8\xe0\x1c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xe0\x1c\x7f\xf8\x3f\xf0" },  // 'O' UTF-8 4F         (input # 3 -> glyph # 48)
  { 10, "\xff\xfc\xff\xfc\x03\x0c\x03\x0c\x03\x0c\x03\x0c\x03\x0c\x03\x9c\x01\xf8\x00\xf0" },  // 'P' UTF-8 50         (input # 4 -> glyph # 49)
  { 10, "\x3f\xf0\x7f\xf8\xe0\x1c\xc0\x0c\xcc\x0c\xdc\x0c\x78\x0c\x70\x1c\xff\xf8\xdf\xf0" },  // 'Q' UTF-8 51         (input # 5 -> glyph # 50)
  { 10, "\xff\xfc\xff\xfc\x03\x0c\x07\x0c\x0f\x0c\x1f\x0c\x3b\x0c\x73\x9c\xe1\xf8\xc0\xf0" },  // 'R' UTF-8 52         (input # 7 -> glyph # 51)
  { 10, "\x30\xf0\x71\xf8\xe3\x9c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe7\x1c\x7e\x38\x3c\x30" },  // 'S' UTF-8 53         (input # 8 -> glyph # 52)
  { 10, "\x00\x0c\x00\x0c\x00\x0c\x00\x0c\xff\xfc\xff\xfc\x00\x0c\x00\x0c\x00\x0c\x00\x0c" },  // 'T' UTF-8 54         (input # 9 -> glyph # 53)
  { 10, "\x3f\xfc\x7f\xfc\xe0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xe0\x00\x7f\xfc\x3f\xfc" },  // 'U' UTF-8 55         (input # 11 -> glyph # 54)
  { 10, "\x0f\xfc\x1f\xfc\x38\x00\x70\x00\xe0\x00\xe0\x00\x70\x00\x38\x00\x1f\xfc\x0f\xfc" },  // 'V' UTF-8 56         (input # 12 -> glyph # 55)
  { 10, "\x3f\xfc\x7f\xfc\xe0\x00\xe0\x00\x7f\x00\x7f\x00\xe0\x00\xe0\x00\x7f\xfc\x3f\xfc" },  // 'W' UTF-8 57         (input # 13 -> glyph # 56)
  { 10, "\xf0\x3c\xf8\x7c\x1c\xe0\x0f\xc0\x07\x80\x07\x80\x0f\xc0\x1c\xe0\xf8\x7c\xf0\x3c" },  // 'X' UTF-8 58         (input # 14 -> glyph # 57)
  { 10, "\x00\xfc\x01\xfc\x03\x80\x07\x00\xfe\x00\xfe\x00\x07\x00\x03\x80\x01\xfc\x00\xfc" },  // 'Y' UTF-8 59         (input # 15 -> glyph # 58)
  { 10, "\xf0\x0c\xf8\x0c\xdc\x0c\xce\x0c\xc7\x0c\xc3\x8c\xc1\xcc\xc0\xec\xc0\x7c\xc0\x3c" },  // 'Z' UTF-8 5A         (input # 16 -> glyph # 59)
  {  9, "\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\xc0\x03\xc0\x03\xc0\x03\xc0\x03" },  // '[' UTF-8 5B         (input # 17 -> glyph # 60)
  { 10, "\x00\x3c\x00\x7c\x00\xe0\x01\xc0\x03\x80\x07\x00\x0e\x00\x1c\x00\xf8\x00\xf0\x00" },  // '\' UTF-8 5C         (input # 18 -> glyph # 61)
  {  7, "\x00\x00\xc0\x03\xc0\x03\xc0\x03\xc0\x03\xff\xff\xff\xff" },  // ']' UTF-8 5D         (input # 19 -> glyph # 62)
  { 10, "\x00\x40\x00\x60\x00\x70\x00\x38\x00\x1c\x00\x1c\x00\x38\x00\x70\x00\x60\x00\x40" },  // '^' UTF-8 5E         (input # 20 -> glyph # 63)
  { 11, "\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00" },  // '_' UTF-8 5F         (input # 21 -> glyph # 64)
  {  7, "\x00\x00\x00\x00\x00\x04\x00\x0c\x00\x0c\x00\x18\x00\x10" },  // '`' UTF-8 60         (input # 23 -> glyph # 65)
  { 10, "\x3c\x00\x7e\x00\xe7\x30\xc3\x30\xc3\x30\xc3\x30\xc3\x30\x66\x70\xff\xe0\xff\xc0" },  // 'a' UTF-8 61         (input # 24 -> glyph # 66)
  { 10, "\xff\xfc\xff\xfc\x3f\x80\x71\xc0\xe0\xe0\xc0\x60\xe0\xe0\x71\xc0\x3f\x80\x1f\x00" },  // 'b' UTF-8 62         (input # 25 -> glyph # 67)
  { 10, "\x3f\x80\x7f\xc0\xe0\xe0\xc0\x60\xc0\x60\xc0\x60\xc0\x60\xe0\xe0\x71\xc0\x31\x80" },  // 'c' UTF-8 63         (input # 26 -> glyph # 68)
  { 10, "\x1f\x00\x3f\x80\x71\xc0\xe0\xe0\xc0\x60\xe0\xe0\x71\xc0\x3f\x80\xff\xfc\xff\xfc" },  // 'd' UTF-8 64         (input # 27 -> glyph # 69)
  { 10, "\x3f\x80\x7f\xc0\xe6\xe0\xc6\x60\xc6\x60\xc6\x60\xc6\x60\xe6\xe0\x67\xc0\x23\x80" },  // 'e' UTF-8 65         (input # 28 -> glyph # 70)
  {  9, "\x00\x00\x00\x60\x00\x60\x00\x60\xff\xf8\xff\xfc\x00\x6c\x00\x6c\x00\x6c" },  // 'f' UTF-8 66         (input # 30 -> glyph # 71)
  { 10, "\x01\xc0\x63\xe0\xe7\x70\xc6\x30\xc6\x30\xc6\x30\xc6\x30\xe3\x70\x7f\xe0\x3f\xc0" },  // 'g' UTF-8 67         (input # 31 -> glyph # 72)
  { 10, "\xff\xfc\xff\xfc\x03\x80\x01\xc0\x00\xe0\x00\x60\x00\xe0\x01\xc0\xff\x80\xff\x00" },  // 'h' UTF-8 68         (input # 32 -> glyph # 73)
  {  8, "\x00\x00\x00\x00\x01\x80\x01\x80\x3f\x98\x7f\x98\xe0\x00\xc0\x00" },  // 'i' UTF-8 69         (input # 33 -> glyph # 74)
  {  8, "\x00\x00\x00\x00\xc0\x00\xc0\x00\xc0\x60\xe0\x60\x7f\xe6\x3f\xe6" },  // 'j' UTF-8 6A         (input # 34 -> glyph # 75)
  { 10, "\xff\xfc\xff\xfc\x38\x00\x1c\x00\x0e\x00\x1f\x00\x3b\x80\x71\xc0\xe0\xe0\xc0\x60" },  // 'k' UTF-8 6B         (input # 35 -> glyph # 76)
  {  6, "\x00\x00\x00\x00\x00\x00\x00\x00\xff\xfc\xff\xfc" },  // 'l' UTF-8 6C         (input # 36 -> glyph # 77)
  { 10, "\xff\xe0\xff\xe0\x00\xc0\x00\x60\xff\xe0\xff\xe0\x00\x60\x00\xe0\xff\xc0\xff\x80" },  // 'm' UTF-8 6D         (input # 38 -> glyph # 78)
  { 10, "\xff\xe0\xff\xe0\x00\xc0\x00\x60\x00\x60\x00\x60\x00\x60\x00\xe0\xff\xc0\xff\x80" },  // 'n' UTF-8 6E         (input # 40 -> glyph # 79)
  { 10, "\x3f\x80\x7f\xc0\xe0\xe0\xc0\x60\xc0\x60\xc0\x60\xc0\x60\xe0\xe0\x7f\xc0\x3f\x80" },  // 'o' UTF-8 6F         (input # 43 -> glyph # 80)
  { 10, "\xff\xf0\xff\xf0\x0f\xe0\x1c\x70\x18\x30\x18\x30\x18\x30\x1c\x70\x0f\xe0\x07\xc0" },  // 'p' UTF-8 70         (input # 44 -> glyph # 81)
  { 10, "\x07\xc0\x0f\xe0\x1c\x70\x18\x30\x18\x30\x18\x30\x0c\x70\x1f\xe0\xff\xf0\xff\xf0" },  // 'q' UTF-8 71         (input # 46 -> glyph # 82)
  { 10, "\xff\xe0\xff\xe0\x03\x80\x01\xc0\x00\xe0\x00\x60\x00\x60\x00\xe0\x01\xc0\x01\x80" },  // 'r' UTF-8 72         (input # 47 -> glyph # 83)
  { 10, "\x31\x80\x73\xc0\xe3\xe0\xc6\x60\xc6\x60\xce\x60\xcc\x60\xfc\xe0\x79\xc0\x31\x80" },  // 's' UTF-8 73         (input # 48 -> glyph # 84)
  {  8, "\x00\x00\x00\x00\x00\x60\x00\x60\x3f\xfc\x7f\xfc\xe0\x60\xc0\x60" },  // 't' UTF-8 74         (input # 50 -> glyph # 85)
  { 10, "\x3f\xe0\x7f\xe0\xe0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xe0\x00\x7f\xe0\x3f\xe0" },  // 'u' UTF-8 75         (input # 53 -> glyph # 86)
  { 10, "\x0f\xe0\x1f\xe0\x38\x00\x70\x00\xe0\x00\xe0\x00\x70\x00\x38\x00\x1f\xe0\x0f\xe0" },  // 'v' UTF-8 76         (input # 56 -> glyph # 87)
  { 10, "\x3f\xe0\x7f\xe0\xe0\x00\xc0\x00\x7e\x00\x7e\x00\xc0\x00\xe0\x00\x7f\xe0\x3f\xe0" },  // 'w' UTF-8 77         (input # 59 -> glyph # 88)
  { 10, "\xc0\x60\xe0\xe0\x71\xc0\x3b\x80\x1f\x00\x1f\x00\x3b\x80\x71\xc0\xe0\xe0\xc0\x60" },  // 'x' UTF-8 78         (input # 61 -> glyph # 89)
  { 10, "\x03\xf0\x07\xf0\xce\x00\xcc\x00\xcc\x00\xce\x00\xc7\x00\xe3\xc0\x7f\xf0\x3f\xf0" },  // 'y' UTF-8 79         (input # 63 -> glyph # 90)
  { 10, "\xc0\x60\xe0\x60\xf0\x60\xf8\x60\xdc\x60\xce\x60\xc7\x60\xc3\xe0\xc1\xe0\xc0\xe0" },  // 'z' UTF-8 7A         (input # 65 -> glyph # 91)
  {  8, "\x00\x00\x00\x00\x01\x80\x01\x80\x3f\xfc\xfe\x7f\xe0\x07\xe0\x07" },  // '{' UTF-8 7B         (input # 67 -> glyph # 92)
  {  6, "\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff" },  // '|' UTF-8 7C         (input # 69 -> glyph # 93)
  {  8, "\x00\x00\x00\x00\xe0\x07\xe0\x07\xfe\x7f\x3f\xfc\x01\x80\x01\x80" },  // '}' UTF-8 7D         (input # 71 -> glyph # 94)
  { 10, "\x06\x00\x03\x00\x01\x80\x01\x80\x03\x80\x07\x00\x06\x00\x06\x00\x03\x00\x01\x80" },  // '~' UTF-8 7E         (input # 73 -> glyph # 95)
  { 10, "\xff\x00\xff\x80\x19\xc1\x18\xe3\x18\x73\x18\x76\x18\xe4\x19\xc0\xff\x80\xff\x00" },  // 'À' UTF-8 C3 80     (input # 37 -> glyph # 96)
  { 10, "\xff\x00\xff\x80\x19\xc0\x18\xe4\x18\x76\x18\x73\x18\xe3\x19\xc1\xff\x80\xff\x00" },  // 'Á' UTF-8 C3 81     (input # 39 -> glyph # 97)
  { 10, "\xff\x00\xff\x80\x19\xc4\x18\xe6\x18\x73\x18\x73\x18\xe6\x19\xc4\xff\x80\xff\x00" },  // 'Â' UTF-8 C3 82     (input # 41 -> glyph # 98)
  { 10, "\xff\x00\xff\x80\x19\xc3\x18\xe3\x18\x70\x18\x70\x18\xe3\x19\xc3\xff\x80\xff\x00" },  // 'Ä' UTF-8 C3 84     (input # 45 -> glyph # 99)
  { 10, "\xff\xf0\xff\xf0\xc6\x31\xc6\x33\xc6\x33\xc6\x36\xc6\x34\xc6\x30\xc0\x30\xc0\x30" },  // 'È' UTF-8 C3 88     (input # 51 -> glyph # 100)
  { 10, "\xff\xf0\xff\xf0\xc6\x30\xc6\x34\xc6\x36\xc6\x33\xc6\x33\xc6\x31\xc0\x30\xc0\x30" },  // 'É' UTF-8 C3 89     (input # 54 -> glyph # 101)
  { 10, "\xff\xf0\xff\xf0\xc6\x34\xc6\x36\xc6\x33\xc6\x33\xc6\x36\xc6\x34\xc0\x30\xc0\x30" },  // 'Ê' UTF-8 C3 8A     (input # 57 -> glyph # 102)
  { 10, "\x3f\xc0\x7f\xe0\xe0\x73\xc0\x33\xc0\x30\xc0\x30\xc0\x33\xe0\x73\x7f\xe0\x3f\xc0" },  // 'Ö' UTF-8 C3 96     (input # 78 -> glyph # 103)
  { 10, "\x3f\xf0\x7f\xf0\xe0\x03\xc0\x03\xc0\x00\xc0\x00\xc0\x03\xe0\x03\x7f\xf0\x3f\xf0" },  // 'Ü' UTF-8 C3 9C     (input # 85 -> glyph # 104)
  { 10, "\x38\x00\x7c\x00\xee\xc4\xc6\xcc\xc6\xcc\xc6\xd8\xc6\xd0\x6c\xc0\xff\x80\xff\x00" },  // 'à' UTF-8 C3 A0     (input # 90 -> glyph # 105)
  { 10, "\x38\x00\x7c\x00\xee\xc0\xc6\xd0\xc6\xd8\xc6\xcc\xc6\xcc\x6c\xc4\xff\x80\xff\x00" },  // 'á' UTF-8 C3 A1     (input # 92 -> glyph # 106)
  { 10, "\x38\x00\x7c\x00\xee\xd0\xc6\xd8\xc6\xcc\xc6\xcc\xc6\xd8\x6c\xd0\xff\x80\xff\x00" },  // 'â' UTF-8 C3 A2     (input # 94 -> glyph # 107)
  { 10, "\x38\x00\x7c\x00\xee\xcc\xc6\xcc\xc6\xc0\xc6\xc0\xc6\xcc\x6c\xcc\xff\x80\xff\x00" },  // 'ä' UTF-8 C3 A4     (input # 97 -> glyph # 108)
  { 10, "\x07\xe0\x0f\xf0\x9c\x38\xd8\x18\xf8\x18\x78\x18\x38\x18\x1c\x38\x0e\x70\x06\x60" },  // 'ç' UTF-8 C3 A7     (input # 101 -> glyph # 109)
  { 10, "\x3f\x00\x7f\x80\xed\xc4\xcc\xcc\xcc\xcc\xcc\xd8\xcc\xd0\xed\xc0\x6f\x80\x27\x00" },  // 'è' UTF-8 C3 A8     (input # 103 -> glyph # 110)
  { 10, "\x3f\x00\x7f\x80\xed\xc0\xcc\xd0\xcc\xd8\xcc\xcc\xcc\xcc\xed\xc4\x6f\x80\x27\x00" },  // 'é' UTF-8 C3 A9     (input # 105 -> glyph # 111)
  { 10, "\x3f\x00\x7f\x80\xed\xd0\xcc\xd8\xcc\xcc\xcc\xcc\xcc\xd8\xed\xd0\x6f\x80\x27\x00" },  // 'ê' UTF-8 C3 AA     (input # 107 -> glyph # 112)
  { 10, "\x3f\x00\x7f\x80\xed\xcc\xcc\xcc\xcc\xc0\xcc\xc0\xcc\xcc\xed\xcc\x6f\x80\x27\x00" },  // 'ë' UTF-8 C3 AB     (input # 109 -> glyph # 113)
  {  8, "\x00\x00\x00\x04\x01\x8c\x01\x8c\x3f\x98\x7f\x90\xe0\x00\xc0\x00" },  // 'ì' UTF-8 C3 AC     (input # 111 -> glyph # 114)
  {  8, "\x00\x00\x00\x00\x01\x80\x01\x90\x3f\x98\x7f\x8c\xe0\x0c\xc0\x04" },  // 'í' UTF-8 C3 AD     (input # 113 -> glyph # 115)
  {  8, "\x00\x00\x00\x10\x01\x98\x01\x8c\x3f\x8c\x7f\x98\xe0\x10\xc0\x00" },  // 'î' UTF-8 C3 AE     (input # 115 -> glyph # 116)
  {  8, "\x00\x00\x00\x0c\x01\x8c\x01\x80\x3f\x80\x7f\x8c\xe0\x0c\xc0\x00" },  // 'ï' UTF-8 C3 AF     (input # 117 -> glyph # 117)
  { 10, "\x3f\x00\x7f\x80\xe1\xcc\xc0\xcc\xc0\xc0\xc0\xc0\xc0\xcc\xe1\xcc\x7f\x80\x3f\x00" },  // 'ö' UTF-8 C3 B6     (input # 2 -> glyph # 118)
  { 10, "\x3f\xc0\x7f\xc0\xe0\x0c\xc0\x0c\xc0\x00\xc0\x00\xc0\x0c\xe0\x0c\x7f\xc0\x3f\xc0" },  // 'ü' UTF-8 C3 BC     (input # 10 -> glyph # 119)
  { 11, "\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00" },  // '–' UTF-8 E2 80 93 (input # 22 -> glyph # 120)
  {  5, "\x00\x00\x00\x00\x00\x9c\x00\x7c\x00\x3c" },  // '’' UTF-8 E2 80 99 (input # 29 -> glyph # 121)
  {  8, "\x00\x00\x00\x00\x03\x80\x07\xc0\x07\xc0\x07\xc0\x07\xc0\x03\x80" },  // '•' UTF-8 E2 80 A2 (input # 42 -> glyph # 122)
};

static const GlyphRange font_vcr_osd_mono_ranges[] = {
  { "", 0x20, 0x7E, 1 }, //  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
  { "\xc3", 0x80, 0x82, 96 }, // ÀÁÂ
  { "\xc3", 0x84, 0x84, 99 }, // Ä
  { "\xc3", 0x88, 0x8A, 100 }, // ÈÉÊ
  { "\xc3", 0x96, 0x96, 103 }, // Ö
  { "\xc3", 0x9C, 0x9C, 104 }, // Ü
  { "\xc3", 0xA0, 0xA2, 105 }, // àáâ
  { "\xc3", 0xA4, 0xA4, 108 }, // ä
  { "\xc3", 0xA7, 0xAF, 109 }, // çèéêëìíîï
  { "\xc3", 0xB6, 0xB6, 118 }, // ö
  { "\xc3", 0xBC, 0xBC, 119 }, // ü
  { "\xe2\x80", 0x93, 0x93, 120 }, // –
  { "\xe2\x80", 0x99, 0x99, 121 }, // ’
  { "\xe2\x80", 0xA2, 0xA2, 122 }, // •
  { NULL, 0, 0, 0 }
};

static const font_t font_vcr_osd_mono = {
  .fontName = "vcr_osd_mono",
  .glyphHeight = 16,
  .numGlyphs = 123,
  .glyphRanges = font_vcr_osd_mono_ranges,
  .glyphs = font_vcr_osd_mono_glyphs
};

// MARK: - end of generated font data

