//  SPDX-License-Identifier: GPL-3.0-or-later
//
//  Autogenerated by p44lrgraphics font generator
//
//  You should have received a copy of the GNU General Public License
//  along with p44lrgraphics. If not, see <http://www.gnu.org/licenses/>.
//

// Include this file into a p44lrgraphics build to define a built-in font

#include "fonts.hpp"

using namespace p44;

#ifdef GENERATE_FONT_SOURCE

// MARK: - 'vcr_osd_mono' generated font verification data

static const char * font_vcr_osd_mono_glyphstrings[] = {
  "placeholder" /* 0x00 - Glyph 0 */

  "\n"   "XXXXXXXXXXXXXXXX"   // FF FF
  "\n"   "X..............X"   // 80 01
  "\n"   "X..............X"   // 80 01
  "\n"   "X..............X"   // 80 01
  "\n"   "X..............X"   // 80 01
  "\n"   "X..............X"   // 80 01
  "\n"   "X..............X"   // 80 01
  "\n"   "X..............X"   // 80 01
  "\n"   "XXXXXXXXXXXXXXXX" , // FF FF

  " " /* UTF-8 20 - Glyph 1 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................" , // 00 00

  "!" /* UTF-8 21 - Glyph 2 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "XX..XXXXXXXXXX.."   // CF FC
  "\n"   "XX..XXXXXXXXXX.." , // CF FC

  "\"" /* UTF-8 22 - Glyph 3 */

  "\n"   "................"   // 00 00
  "\n"   "...........XXX.."   // 00 1C
  "\n"   "..........XXXX.."   // 00 3C
  "\n"   "...........XXX.."   // 00 1C
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "...........XXX.."   // 00 1C
  "\n"   "..........XXXX.."   // 00 3C
  "\n"   "...........XXX.." , // 00 1C

  "#" /* UTF-8 23 - Glyph 4 */

  "\n"   "...XX...XX......"   // 18 C0
  "\n"   "...XX...XX......"   // 18 C0
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "....XX...XX....."   // 0C 60
  "\n"   "....XX...XX....."   // 0C 60
  "\n"   "..XXXXXXXXXXXX.."   // 3F FC
  "\n"   "..XXXXXXXXXXXX.."   // 3F FC
  "\n"   ".....XX...XX...."   // 06 30
  "\n"   ".....XX...XX...." , // 06 30

  "$" /* UTF-8 24 - Glyph 5 */

  "\n"   "...XX...XXX....."   // 18 E0
  "\n"   "..XXX..XXXXX...."   // 39 F0
  "\n"   ".XXX..XXX.XXX..."   // 73 B8
  "\n"   ".XX...XX...XX..."   // 63 18
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   ".XX...XX...XX..."   // 63 18
  "\n"   ".XXX.XXX..XXX..."   // 77 38
  "\n"   "..XXXXX..XXX...."   // 3E 70
  "\n"   "...XXX...XX....." , // 1C 60

  "%" /* UTF-8 25 - Glyph 6 */

  "\n"   "XXXX.....XXXX..."   // F0 78
  "\n"   "XXXXX...XXXXXX.."   // F8 FC
  "\n"   "...XXX..XX..XX.."   // 1C CC
  "\n"   "....XXX.XXXXXX.."   // 0E FC
  "\n"   ".....XXX.XXXX..."   // 07 78
  "\n"   ".XXXX.XXX......."   // 7B 80
  "\n"   "XXXXXX.XXX......"   // FD C0
  "\n"   "XX..XX..XXX....."   // CC E0
  "\n"   "XXXXXX...XXXXX.."   // FC 7C
  "\n"   ".XXXX.....XXXX.." , // 78 3C

  "&" /* UTF-8 26 - Glyph 7 */

  "\n"   "..XXXXX........."   // 3E 00
  "\n"   ".XXXXXXX..XXXX.."   // 7F 3C
  "\n"   "XXX...XXXXXXXXX."   // E3 FE
  "\n"   "XX....XXXX....XX"   // C3 C3
  "\n"   "XX...XXXX.....XX"   // C7 83
  "\n"   "XX..XXXXXX....XX"   // CF C3
  "\n"   "XXXXXX..XXXXXXX."   // FC FE
  "\n"   ".XXXX.....XXXX.."   // 78 3C
  "\n"   "XXXXXX.........."   // FC 00
  "\n"   "XX..XX.........." , // CC 00

  "'" /* UTF-8 27 - Glyph 8 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "...........XXX.."   // 00 1C
  "\n"   "..........XXXX.."   // 00 3C
  "\n"   "...........XXX.." , // 00 1C

  "(" /* UTF-8 28 - Glyph 9 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "...XXXXXXXXXX..."   // 1F F8
  "\n"   "..XXXXXXXXXXXX.."   // 3F FC
  "\n"   ".XX..........XX."   // 60 06
  "\n"   "XX............XX"   // C0 03
  "\n"   "X..............X" , // 80 01

  ")" /* UTF-8 29 - Glyph 10 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "X..............X"   // 80 01
  "\n"   "XX............XX"   // C0 03
  "\n"   ".XX..........XX."   // 60 06
  "\n"   "..XXXXXXXXXXXX.."   // 3F FC
  "\n"   "...XXXXXXXXXX..." , // 1F F8

  "*" /* UTF-8 2A - Glyph 11 */

  "\n"   "................"   // 00 00
  "\n"   ".......XX...XX.."   // 01 8C
  "\n"   "........XX.XX..."   // 00 D8
  "\n"   ".........XXX...."   // 00 70
  "\n"   "......XXXXXXXXX."   // 03 FE
  "\n"   "......XXXXXXXXX."   // 03 FE
  "\n"   ".........XXX...."   // 00 70
  "\n"   "........XX.XX..."   // 00 D8
  "\n"   ".......XX...XX.." , // 01 8C

  "+" /* UTF-8 2B - Glyph 12 */

  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "..XXXXXXXXXX...."   // 3F F0
  "\n"   "..XXXXXXXXXX...."   // 3F F0
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........" , // 03 00

  "," /* UTF-8 2C - Glyph 13 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "X..............."   // 80 00
  "\n"   "XX.............."   // C0 00
  "\n"   ".XXX............"   // 70 00
  "\n"   "..XX............" , // 30 00

  "-" /* UTF-8 2D - Glyph 14 */

  "\n"   "................"   // 00 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........" , // 03 00

  "." /* UTF-8 2E - Glyph 15 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............." , // C0 00

  "/" /* UTF-8 2F - Glyph 16 */

  "\n"   "XXXX............"   // F0 00
  "\n"   "XXXXX..........."   // F8 00
  "\n"   "...XXX.........."   // 1C 00
  "\n"   "....XXX........."   // 0E 00
  "\n"   ".....XXX........"   // 07 00
  "\n"   "......XXX......."   // 03 80
  "\n"   ".......XXX......"   // 01 C0
  "\n"   "........XXX....."   // 00 E0
  "\n"   ".........XXXXX.."   // 00 7C
  "\n"   "..........XXXX.." , // 00 3C

  "0" /* UTF-8 30 - Glyph 17 */

  "\n"   "..XXXXXXXXXX...."   // 3F F0
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "XXX.XX.....XXX.."   // EC 1C
  "\n"   "XX..XXX.....XX.."   // CE 0C
  "\n"   "XX...XXX....XX.."   // C7 0C
  "\n"   "XX....XXX...XX.."   // C3 8C
  "\n"   "XX.....XXX..XX.."   // C1 CC
  "\n"   "XXX.....XX.XXX.."   // E0 DC
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "..XXXXXXXXXX...." , // 3F F0

  "1" /* UTF-8 31 - Glyph 18 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "XX........XX...."   // C0 30
  "\n"   "XX........XXX..."   // C0 38
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............." , // C0 00

  "2" /* UTF-8 32 - Glyph 19 */

  "\n"   "XXXXXX....XX...."   // FC 30
  "\n"   "XXXXXXX...XXX..."   // FE 38
  "\n"   "XX...XXX...XXX.."   // C7 1C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XXX..XXX.."   // C3 9C
  "\n"   "XX.....XXXXXX..."   // C1 F8
  "\n"   "XX......XXXX...." , // C0 F0

  "3" /* UTF-8 33 - Glyph 20 */

  "\n"   "..XX......XX...."   // 30 30
  "\n"   ".XXX......XXX..."   // 70 38
  "\n"   "XXX........XXX.."   // E0 1C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XXX..XXXX..XXX.."   // E7 9C
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "..XXXX..XXXX...." , // 3C F0

  "4" /* UTF-8 34 - Glyph 21 */

  "\n"   "....XXXX........"   // 0F 00
  "\n"   "....XXXXX......."   // 0F 80
  "\n"   "....XX.XXX......"   // 0D C0
  "\n"   "....XX..XXX....."   // 0C E0
  "\n"   "....XX...XXX...."   // 0C 70
  "\n"   "....XX....XXX..."   // 0C 38
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........." , // 0C 00

  "5" /* UTF-8 35 - Glyph 22 */

  "\n"   "..XX....XXXXXX.."   // 30 FC
  "\n"   ".XXX....XXXXXX.."   // 70 FC
  "\n"   "XXX.....XX..XX.."   // E0 CC
  "\n"   "XX......XX..XX.."   // C0 CC
  "\n"   "XX......XX..XX.."   // C0 CC
  "\n"   "XX......XX..XX.."   // C0 CC
  "\n"   "XX......XX..XX.."   // C0 CC
  "\n"   "XXX....XXX..XX.."   // E1 CC
  "\n"   ".XXXXXXXX...XX.."   // 7F 8C
  "\n"   "..XXXXXX....XX.." , // 3F 0C

  "6" /* UTF-8 36 - Glyph 23 */

  "\n"   "..XXXXXXXXXX...."   // 3F F0
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "XXX...XX...XXX.."   // E3 1C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XXX..XXX...XXX.."   // E7 1C
  "\n"   ".XXXXXX...XXX..."   // 7E 38
  "\n"   "..XXXX....XX...." , // 3C 30

  "7" /* UTF-8 37 - Glyph 24 */

  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.."   // 00 0C
  "\n"   "XXXXXXX.....XX.."   // FE 0C
  "\n"   "XXXXXXXX....XX.."   // FF 0C
  "\n"   "......XXX...XX.."   // 03 8C
  "\n"   ".......XXX..XX.."   // 01 CC
  "\n"   "........XXXXXX.."   // 00 FC
  "\n"   ".........XXXXX.." , // 00 7C

  "8" /* UTF-8 38 - Glyph 25 */

  "\n"   "..XXXX..XXXX...."   // 3C F0
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "XXX..XXXX..XXX.."   // E7 9C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XXX..XXXX..XXX.."   // E7 9C
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "..XXXX..XXXX...." , // 3C F0

  "9" /* UTF-8 39 - Glyph 26 */

  "\n"   "..XX....XXXX...."   // 30 F0
  "\n"   ".XXX...XXXXXX..."   // 71 F8
  "\n"   "XXX...XXX..XXX.."   // E3 9C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XXX...XX...XXX.."   // E3 1C
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "..XXXXXXXXXX...." , // 3F F0

  ":" /* UTF-8 3A - Glyph 27 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "..XX......XX...."   // 30 30
  "\n"   "..XX......XX...." , // 30 30

  ";" /* UTF-8 3B - Glyph 28 */

  "\n"   "................"   // 00 00
  "\n"   "X..............."   // 80 00
  "\n"   "XX.............."   // C0 00
  "\n"   ".XXX......XX...."   // 70 30
  "\n"   "..XX......XX...." , // 30 30

  "<" /* UTF-8 3C - Glyph 29 */

  "\n"   "................"   // 00 00
  "\n"   "......XXX......."   // 03 80
  "\n"   ".....XXXXX......"   // 07 C0
  "\n"   "....XXX.XXX....."   // 0E E0
  "\n"   "...XXX...XXX...."   // 1C 70
  "\n"   "..XXX.....XXX..."   // 38 38
  "\n"   ".XXX.......XXX.."   // 70 1C
  "\n"   "XXX.........XXX."   // E0 0E
  "\n"   "XX...........XX." , // C0 06

  "=" /* UTF-8 3D - Glyph 30 */

  "\n"   "....XX..XX......"   // 0C C0
  "\n"   "....XX..XX......"   // 0C C0
  "\n"   "....XX..XX......"   // 0C C0
  "\n"   "....XX..XX......"   // 0C C0
  "\n"   "....XX..XX......"   // 0C C0
  "\n"   "....XX..XX......"   // 0C C0
  "\n"   "....XX..XX......"   // 0C C0
  "\n"   "....XX..XX......"   // 0C C0
  "\n"   "....XX..XX......"   // 0C C0
  "\n"   "....XX..XX......" , // 0C C0

  ">" /* UTF-8 3E - Glyph 31 */

  "\n"   "................"   // 00 00
  "\n"   "XX...........XX."   // C0 06
  "\n"   "XXX.........XXX."   // E0 0E
  "\n"   ".XXX.......XXX.."   // 70 1C
  "\n"   "..XXX.....XXX..."   // 38 38
  "\n"   "...XXX...XXX...."   // 1C 70
  "\n"   "....XXX.XXX....."   // 0E E0
  "\n"   ".....XXXXX......"   // 07 C0
  "\n"   "......XXX......." , // 03 80

  "?" /* UTF-8 3F - Glyph 32 */

  "\n"   "..........XX...."   // 00 30
  "\n"   "..........XXX..."   // 00 38
  "\n"   "...........XXX.."   // 00 1C
  "\n"   "............XX.."   // 00 0C
  "\n"   "XX..XX......XX.."   // CC 0C
  "\n"   "XX..XXX.....XX.."   // CE 0C
  "\n"   ".....XXX....XX.."   // 07 0C
  "\n"   "......XXX..XXX.."   // 03 9C
  "\n"   ".......XXXXXX..."   // 01 F8
  "\n"   "........XXXX...." , // 00 F0

  "@" /* UTF-8 40 - Glyph 33 */

  "\n"   "...XXXXXXXX....."   // 1F E0
  "\n"   "..XX......XX...."   // 30 30
  "\n"   ".XX..XXXX..XX..."   // 67 98
  "\n"   ".X..XXXXXX..X..."   // 4F C8
  "\n"   ".X..X....X..X..."   // 48 48
  "\n"   ".X..XXXXX...X..."   // 4F 88
  "\n"   ".X...XXXXX..X..."   // 47 C8
  "\n"   ".XX.X......XX..."   // 68 18
  "\n"   "..X.XX....XX...."   // 2C 30
  "\n"   ".....XXXXXX....." , // 07 E0

  "A" /* UTF-8 41 - Glyph 34 */

  "\n"   "XXXXXXXXXX......"   // FF C0
  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   "....XX...XXX...."   // 0C 70
  "\n"   "....XX....XXX..."   // 0C 38
  "\n"   "....XX.....XXX.."   // 0C 1C
  "\n"   "....XX.....XXX.."   // 0C 1C
  "\n"   "....XX....XXX..."   // 0C 38
  "\n"   "....XX...XXX...."   // 0C 70
  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   "XXXXXXXXXX......" , // FF C0

  "B" /* UTF-8 42 - Glyph 35 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XXX..XXXX..XXX.."   // E7 9C
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "..XXXX..XXXX...." , // 3C F0

  "C" /* UTF-8 43 - Glyph 36 */

  "\n"   "..XXXXXXXXXX...."   // 3F F0
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "XXX........XXX.."   // E0 1C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XXX........XXX.."   // E0 1C
  "\n"   ".XXX......XXX..."   // 70 38
  "\n"   "..XX......XX...." , // 30 30

  "D" /* UTF-8 44 - Glyph 37 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XXX........XXX.."   // E0 1C
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "..XXXXXXXXXX...." , // 3F F0

  "E" /* UTF-8 45 - Glyph 38 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.." , // C0 0C

  "F" /* UTF-8 46 - Glyph 39 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.." , // 00 0C

  "G" /* UTF-8 47 - Glyph 40 */

  "\n"   "..XXXXXXXXXX...."   // 3F F0
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "XXX........XXX.."   // E0 1C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XXX...XX...XXX.."   // E3 1C
  "\n"   ".XXXXXXX..XXX..."   // 7F 38
  "\n"   "..XXXXXX..XX...." , // 3F 30

  "H" /* UTF-8 48 - Glyph 41 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "......XX........"   // 03 00
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.." , // FF FC

  "I" /* UTF-8 49 - Glyph 42 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.." , // C0 0C

  "J" /* UTF-8 4A - Glyph 43 */

  "\n"   "..XX............"   // 30 00
  "\n"   ".XXX............"   // 70 00
  "\n"   "XXX............."   // E0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XXX.........XX.."   // E0 0C
  "\n"   ".XXXXXXXXXXXXX.."   // 7F FC
  "\n"   "..XXXXXXXXXXXX.."   // 3F FC
  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.." , // 00 0C

  "K" /* UTF-8 4B - Glyph 44 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "......XX........"   // 03 00
  "\n"   ".....XXXX......."   // 07 80
  "\n"   "....XXXXXX......"   // 0F C0
  "\n"   "...XXX..XXX....."   // 1C E0
  "\n"   "..XXX....XXX...."   // 38 70
  "\n"   ".XXX......XXX..."   // 70 38
  "\n"   "XXX........XXX.."   // E0 1C
  "\n"   "XX..........XX.." , // C0 0C

  "L" /* UTF-8 4C - Glyph 45 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............." , // C0 00

  "M" /* UTF-8 4D - Glyph 46 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   ".........XXX...."   // 00 70
  "\n"   "........XXX....."   // 00 E0
  "\n"   "......XXXX......"   // 03 C0
  "\n"   "......XXXX......"   // 03 C0
  "\n"   "........XXX....."   // 00 E0
  "\n"   ".........XXX...."   // 00 70
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.." , // FF FC

  "N" /* UTF-8 4E - Glyph 47 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "........XXX....."   // 00 E0
  "\n"   ".......XXX......"   // 01 C0
  "\n"   "......XXX......."   // 03 80
  "\n"   ".....XXX........"   // 07 00
  "\n"   "....XXX........."   // 0E 00
  "\n"   "...XXX.........."   // 1C 00
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.." , // FF FC

  "O" /* UTF-8 4F - Glyph 48 */

  "\n"   "..XXXXXXXXXX...."   // 3F F0
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "XXX........XXX.."   // E0 1C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XXX........XXX.."   // E0 1C
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "..XXXXXXXXXX...." , // 3F F0

  "P" /* UTF-8 50 - Glyph 49 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   "......XXX..XXX.."   // 03 9C
  "\n"   ".......XXXXXX..."   // 01 F8
  "\n"   "........XXXX...." , // 00 F0

  "Q" /* UTF-8 51 - Glyph 50 */

  "\n"   "..XXXXXXXXXX...."   // 3F F0
  "\n"   ".XXXXXXXXXXXX..."   // 7F F8
  "\n"   "XXX........XXX.."   // E0 1C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX..XX......XX.."   // CC 0C
  "\n"   "XX.XXX......XX.."   // DC 0C
  "\n"   ".XXXX.......XX.."   // 78 0C
  "\n"   ".XXX.......XXX.."   // 70 1C
  "\n"   "XXXXXXXXXXXXX..."   // FF F8
  "\n"   "XX.XXXXXXXXX...." , // DF F0

  "R" /* UTF-8 52 - Glyph 51 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "......XX....XX.."   // 03 0C
  "\n"   ".....XXX....XX.."   // 07 0C
  "\n"   "....XXXX....XX.."   // 0F 0C
  "\n"   "...XXXXX....XX.."   // 1F 0C
  "\n"   "..XXX.XX....XX.."   // 3B 0C
  "\n"   ".XXX..XXX..XXX.."   // 73 9C
  "\n"   "XXX....XXXXXX..."   // E1 F8
  "\n"   "XX......XXXX...." , // C0 F0

  "S" /* UTF-8 53 - Glyph 52 */

  "\n"   "..XX....XXXX...."   // 30 F0
  "\n"   ".XXX...XXXXXX..."   // 71 F8
  "\n"   "XXX...XXX..XXX.."   // E3 9C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XX....XX....XX.."   // C3 0C
  "\n"   "XXX..XXX...XXX.."   // E7 1C
  "\n"   ".XXXXXX...XXX..."   // 7E 38
  "\n"   "..XXXX....XX...." , // 3C 30

  "T" /* UTF-8 54 - Glyph 53 */

  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.."   // 00 0C
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.." , // 00 0C

  "U" /* UTF-8 55 - Glyph 54 */

  "\n"   "..XXXXXXXXXXXX.."   // 3F FC
  "\n"   ".XXXXXXXXXXXXX.."   // 7F FC
  "\n"   "XXX............."   // E0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XXX............."   // E0 00
  "\n"   ".XXXXXXXXXXXXX.."   // 7F FC
  "\n"   "..XXXXXXXXXXXX.." , // 3F FC

  "V" /* UTF-8 56 - Glyph 55 */

  "\n"   "....XXXXXXXXXX.."   // 0F FC
  "\n"   "...XXXXXXXXXXX.."   // 1F FC
  "\n"   "..XXX..........."   // 38 00
  "\n"   ".XXX............"   // 70 00
  "\n"   "XXX............."   // E0 00
  "\n"   "XXX............."   // E0 00
  "\n"   ".XXX............"   // 70 00
  "\n"   "..XXX..........."   // 38 00
  "\n"   "...XXXXXXXXXXX.."   // 1F FC
  "\n"   "....XXXXXXXXXX.." , // 0F FC

  "W" /* UTF-8 57 - Glyph 56 */

  "\n"   "..XXXXXXXXXXXX.."   // 3F FC
  "\n"   ".XXXXXXXXXXXXX.."   // 7F FC
  "\n"   "XXX............."   // E0 00
  "\n"   "XXX............."   // E0 00
  "\n"   ".XXXXXXX........"   // 7F 00
  "\n"   ".XXXXXXX........"   // 7F 00
  "\n"   "XXX............."   // E0 00
  "\n"   "XXX............."   // E0 00
  "\n"   ".XXXXXXXXXXXXX.."   // 7F FC
  "\n"   "..XXXXXXXXXXXX.." , // 3F FC

  "X" /* UTF-8 58 - Glyph 57 */

  "\n"   "XXXX......XXXX.."   // F0 3C
  "\n"   "XXXXX....XXXXX.."   // F8 7C
  "\n"   "...XXX..XXX....."   // 1C E0
  "\n"   "....XXXXXX......"   // 0F C0
  "\n"   ".....XXXX......."   // 07 80
  "\n"   ".....XXXX......."   // 07 80
  "\n"   "....XXXXXX......"   // 0F C0
  "\n"   "...XXX..XXX....."   // 1C E0
  "\n"   "XXXXX....XXXXX.."   // F8 7C
  "\n"   "XXXX......XXXX.." , // F0 3C

  "Y" /* UTF-8 59 - Glyph 58 */

  "\n"   "........XXXXXX.."   // 00 FC
  "\n"   ".......XXXXXXX.."   // 01 FC
  "\n"   "......XXX......."   // 03 80
  "\n"   ".....XXX........"   // 07 00
  "\n"   "XXXXXXX........."   // FE 00
  "\n"   "XXXXXXX........."   // FE 00
  "\n"   ".....XXX........"   // 07 00
  "\n"   "......XXX......."   // 03 80
  "\n"   ".......XXXXXXX.."   // 01 FC
  "\n"   "........XXXXXX.." , // 00 FC

  "Z" /* UTF-8 5A - Glyph 59 */

  "\n"   "XXXX........XX.."   // F0 0C
  "\n"   "XXXXX.......XX.."   // F8 0C
  "\n"   "XX.XXX......XX.."   // DC 0C
  "\n"   "XX..XXX.....XX.."   // CE 0C
  "\n"   "XX...XXX....XX.."   // C7 0C
  "\n"   "XX....XXX...XX.."   // C3 8C
  "\n"   "XX.....XXX..XX.."   // C1 CC
  "\n"   "XX......XXX.XX.."   // C0 EC
  "\n"   "XX.......XXXXX.."   // C0 7C
  "\n"   "XX........XXXX.." , // C0 3C

  "[" /* UTF-8 5B - Glyph 60 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "XXXXXXXXXXXXXXXX"   // FF FF
  "\n"   "XXXXXXXXXXXXXXXX"   // FF FF
  "\n"   "XX............XX"   // C0 03
  "\n"   "XX............XX"   // C0 03
  "\n"   "XX............XX"   // C0 03
  "\n"   "XX............XX" , // C0 03

  "\\" /* UTF-8 5C - Glyph 61 */

  "\n"   "..........XXXX.."   // 00 3C
  "\n"   ".........XXXXX.."   // 00 7C
  "\n"   "........XXX....."   // 00 E0
  "\n"   ".......XXX......"   // 01 C0
  "\n"   "......XXX......."   // 03 80
  "\n"   ".....XXX........"   // 07 00
  "\n"   "....XXX........."   // 0E 00
  "\n"   "...XXX.........."   // 1C 00
  "\n"   "XXXXX..........."   // F8 00
  "\n"   "XXXX............" , // F0 00

  "]" /* UTF-8 5D - Glyph 62 */

  "\n"   "................"   // 00 00
  "\n"   "XX............XX"   // C0 03
  "\n"   "XX............XX"   // C0 03
  "\n"   "XX............XX"   // C0 03
  "\n"   "XX............XX"   // C0 03
  "\n"   "XXXXXXXXXXXXXXXX"   // FF FF
  "\n"   "XXXXXXXXXXXXXXXX" , // FF FF

  "^" /* UTF-8 5E - Glyph 63 */

  "\n"   ".........X......"   // 00 40
  "\n"   ".........XX....."   // 00 60
  "\n"   ".........XXX...."   // 00 70
  "\n"   "..........XXX..."   // 00 38
  "\n"   "...........XXX.."   // 00 1C
  "\n"   "...........XXX.."   // 00 1C
  "\n"   "..........XXX..."   // 00 38
  "\n"   ".........XXX...."   // 00 70
  "\n"   ".........XX....."   // 00 60
  "\n"   ".........X......" , // 00 40

  "_" /* UTF-8 5F - Glyph 64 */

  "\n"   "X..............."   // 80 00
  "\n"   "X..............."   // 80 00
  "\n"   "X..............."   // 80 00
  "\n"   "X..............."   // 80 00
  "\n"   "X..............."   // 80 00
  "\n"   "X..............."   // 80 00
  "\n"   "X..............."   // 80 00
  "\n"   "X..............."   // 80 00
  "\n"   "X..............."   // 80 00
  "\n"   "X..............."   // 80 00
  "\n"   "X..............." , // 80 00

  "`" /* UTF-8 60 - Glyph 65 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   ".............X.."   // 00 04
  "\n"   "............XX.."   // 00 0C
  "\n"   "............XX.."   // 00 0C
  "\n"   "...........XX..."   // 00 18
  "\n"   "...........X...." , // 00 10

  "a" /* UTF-8 61 - Glyph 66 */

  "\n"   "..XXXX.........."   // 3C 00
  "\n"   ".XXXXXX........."   // 7E 00
  "\n"   "XXX..XXX..XX...."   // E7 30
  "\n"   "XX....XX..XX...."   // C3 30
  "\n"   "XX....XX..XX...."   // C3 30
  "\n"   "XX....XX..XX...."   // C3 30
  "\n"   "XX....XX..XX...."   // C3 30
  "\n"   ".XX..XX..XXX...."   // 66 70
  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   "XXXXXXXXXX......" , // FF C0

  "b" /* UTF-8 62 - Glyph 67 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "..XXXXXXX......."   // 3F 80
  "\n"   ".XXX...XXX......"   // 71 C0
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   ".XXX...XXX......"   // 71 C0
  "\n"   "..XXXXXXX......."   // 3F 80
  "\n"   "...XXXXX........" , // 1F 00

  "c" /* UTF-8 63 - Glyph 68 */

  "\n"   "..XXXXXXX......."   // 3F 80
  "\n"   ".XXXXXXXXX......"   // 7F C0
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   ".XXX...XXX......"   // 71 C0
  "\n"   "..XX...XX......." , // 31 80

  "d" /* UTF-8 64 - Glyph 69 */

  "\n"   "...XXXXX........"   // 1F 00
  "\n"   "..XXXXXXX......."   // 3F 80
  "\n"   ".XXX...XXX......"   // 71 C0
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   ".XXX...XXX......"   // 71 C0
  "\n"   "..XXXXXXX......."   // 3F 80
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.." , // FF FC

  "e" /* UTF-8 65 - Glyph 70 */

  "\n"   "..XXXXXXX......."   // 3F 80
  "\n"   ".XXXXXXXXX......"   // 7F C0
  "\n"   "XXX..XX.XXX....."   // E6 E0
  "\n"   "XX...XX..XX....."   // C6 60
  "\n"   "XX...XX..XX....."   // C6 60
  "\n"   "XX...XX..XX....."   // C6 60
  "\n"   "XX...XX..XX....."   // C6 60
  "\n"   "XXX..XX.XXX....."   // E6 E0
  "\n"   ".XX..XXXXX......"   // 67 C0
  "\n"   "..X...XXX......." , // 23 80

  "f" /* UTF-8 66 - Glyph 71 */

  "\n"   "................"   // 00 00
  "\n"   ".........XX....."   // 00 60
  "\n"   ".........XX....."   // 00 60
  "\n"   ".........XX....."   // 00 60
  "\n"   "XXXXXXXXXXXXX..."   // FF F8
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   ".........XX.XX.."   // 00 6C
  "\n"   ".........XX.XX.."   // 00 6C
  "\n"   ".........XX.XX.." , // 00 6C

  "g" /* UTF-8 67 - Glyph 72 */

  "\n"   ".......XXX......"   // 01 C0
  "\n"   ".XX...XXXXX....."   // 63 E0
  "\n"   "XXX..XXX.XXX...."   // E7 70
  "\n"   "XX...XX...XX...."   // C6 30
  "\n"   "XX...XX...XX...."   // C6 30
  "\n"   "XX...XX...XX...."   // C6 30
  "\n"   "XX...XX...XX...."   // C6 30
  "\n"   "XXX...XX.XXX...."   // E3 70
  "\n"   ".XXXXXXXXXX....."   // 7F E0
  "\n"   "..XXXXXXXX......" , // 3F C0

  "h" /* UTF-8 68 - Glyph 73 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "......XXX......."   // 03 80
  "\n"   ".......XXX......"   // 01 C0
  "\n"   "........XXX....."   // 00 E0
  "\n"   ".........XX....."   // 00 60
  "\n"   "........XXX....."   // 00 E0
  "\n"   ".......XXX......"   // 01 C0
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "XXXXXXXX........" , // FF 00

  "i" /* UTF-8 69 - Glyph 74 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   ".......XX......."   // 01 80
  "\n"   ".......XX......."   // 01 80
  "\n"   "..XXXXXXX..XX..."   // 3F 98
  "\n"   ".XXXXXXXX..XX..."   // 7F 98
  "\n"   "XXX............."   // E0 00
  "\n"   "XX.............." , // C0 00

  "j" /* UTF-8 6A - Glyph 75 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XXX......XX....."   // E0 60
  "\n"   ".XXXXXXXXXX..XX."   // 7F E6
  "\n"   "..XXXXXXXXX..XX." , // 3F E6

  "k" /* UTF-8 6B - Glyph 76 */

  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "..XXX..........."   // 38 00
  "\n"   "...XXX.........."   // 1C 00
  "\n"   "....XXX........."   // 0E 00
  "\n"   "...XXXXX........"   // 1F 00
  "\n"   "..XXX.XXX......."   // 3B 80
  "\n"   ".XXX...XXX......"   // 71 C0
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   "XX.......XX....." , // C0 60

  "l" /* UTF-8 6C - Glyph 77 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "XXXXXXXXXXXXXX.."   // FF FC
  "\n"   "XXXXXXXXXXXXXX.." , // FF FC

  "m" /* UTF-8 6D - Glyph 78 */

  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   "........XX......"   // 00 C0
  "\n"   ".........XX....."   // 00 60
  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   ".........XX....."   // 00 60
  "\n"   "........XXX....."   // 00 E0
  "\n"   "XXXXXXXXXX......"   // FF C0
  "\n"   "XXXXXXXXX......." , // FF 80

  "n" /* UTF-8 6E - Glyph 79 */

  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   "........XX......"   // 00 C0
  "\n"   ".........XX....."   // 00 60
  "\n"   ".........XX....."   // 00 60
  "\n"   ".........XX....."   // 00 60
  "\n"   ".........XX....."   // 00 60
  "\n"   "........XXX....."   // 00 E0
  "\n"   "XXXXXXXXXX......"   // FF C0
  "\n"   "XXXXXXXXX......." , // FF 80

  "o" /* UTF-8 6F - Glyph 80 */

  "\n"   "..XXXXXXX......."   // 3F 80
  "\n"   ".XXXXXXXXX......"   // 7F C0
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   ".XXXXXXXXX......"   // 7F C0
  "\n"   "..XXXXXXX......." , // 3F 80

  "p" /* UTF-8 70 - Glyph 81 */

  "\n"   "XXXXXXXXXXXX...."   // FF F0
  "\n"   "XXXXXXXXXXXX...."   // FF F0
  "\n"   "....XXXXXXX....."   // 0F E0
  "\n"   "...XXX...XXX...."   // 1C 70
  "\n"   "...XX.....XX...."   // 18 30
  "\n"   "...XX.....XX...."   // 18 30
  "\n"   "...XX.....XX...."   // 18 30
  "\n"   "...XXX...XXX...."   // 1C 70
  "\n"   "....XXXXXXX....."   // 0F E0
  "\n"   ".....XXXXX......" , // 07 C0

  "q" /* UTF-8 71 - Glyph 82 */

  "\n"   ".....XXXXX......"   // 07 C0
  "\n"   "....XXXXXXX....."   // 0F E0
  "\n"   "...XXX...XXX...."   // 1C 70
  "\n"   "...XX.....XX...."   // 18 30
  "\n"   "...XX.....XX...."   // 18 30
  "\n"   "...XX.....XX...."   // 18 30
  "\n"   "....XX...XXX...."   // 0C 70
  "\n"   "...XXXXXXXX....."   // 1F E0
  "\n"   "XXXXXXXXXXXX...."   // FF F0
  "\n"   "XXXXXXXXXXXX...." , // FF F0

  "r" /* UTF-8 72 - Glyph 83 */

  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   "XXXXXXXXXXX....."   // FF E0
  "\n"   "......XXX......."   // 03 80
  "\n"   ".......XXX......"   // 01 C0
  "\n"   "........XXX....."   // 00 E0
  "\n"   ".........XX....."   // 00 60
  "\n"   ".........XX....."   // 00 60
  "\n"   "........XXX....."   // 00 E0
  "\n"   ".......XXX......"   // 01 C0
  "\n"   ".......XX......." , // 01 80

  "s" /* UTF-8 73 - Glyph 84 */

  "\n"   "..XX...XX......."   // 31 80
  "\n"   ".XXX..XXXX......"   // 73 C0
  "\n"   "XXX...XXXXX....."   // E3 E0
  "\n"   "XX...XX..XX....."   // C6 60
  "\n"   "XX...XX..XX....."   // C6 60
  "\n"   "XX..XXX..XX....."   // CE 60
  "\n"   "XX..XX...XX....."   // CC 60
  "\n"   "XXXXXX..XXX....."   // FC E0
  "\n"   ".XXXX..XXX......"   // 79 C0
  "\n"   "..XX...XX......." , // 31 80

  "t" /* UTF-8 74 - Glyph 85 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   ".........XX....."   // 00 60
  "\n"   ".........XX....."   // 00 60
  "\n"   "..XXXXXXXXXXXX.."   // 3F FC
  "\n"   ".XXXXXXXXXXXXX.."   // 7F FC
  "\n"   "XXX......XX....."   // E0 60
  "\n"   "XX.......XX....." , // C0 60

  "u" /* UTF-8 75 - Glyph 86 */

  "\n"   "..XXXXXXXXX....."   // 3F E0
  "\n"   ".XXXXXXXXXX....."   // 7F E0
  "\n"   "XXX............."   // E0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XXX............."   // E0 00
  "\n"   ".XXXXXXXXXX....."   // 7F E0
  "\n"   "..XXXXXXXXX....." , // 3F E0

  "v" /* UTF-8 76 - Glyph 87 */

  "\n"   "....XXXXXXX....."   // 0F E0
  "\n"   "...XXXXXXXX....."   // 1F E0
  "\n"   "..XXX..........."   // 38 00
  "\n"   ".XXX............"   // 70 00
  "\n"   "XXX............."   // E0 00
  "\n"   "XXX............."   // E0 00
  "\n"   ".XXX............"   // 70 00
  "\n"   "..XXX..........."   // 38 00
  "\n"   "...XXXXXXXX....."   // 1F E0
  "\n"   "....XXXXXXX....." , // 0F E0

  "w" /* UTF-8 77 - Glyph 88 */

  "\n"   "..XXXXXXXXX....."   // 3F E0
  "\n"   ".XXXXXXXXXX....."   // 7F E0
  "\n"   "XXX............."   // E0 00
  "\n"   "XX.............."   // C0 00
  "\n"   ".XXXXXX........."   // 7E 00
  "\n"   ".XXXXXX........."   // 7E 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XXX............."   // E0 00
  "\n"   ".XXXXXXXXXX....."   // 7F E0
  "\n"   "..XXXXXXXXX....." , // 3F E0

  "x" /* UTF-8 78 - Glyph 89 */

  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   ".XXX...XXX......"   // 71 C0
  "\n"   "..XXX.XXX......."   // 3B 80
  "\n"   "...XXXXX........"   // 1F 00
  "\n"   "...XXXXX........"   // 1F 00
  "\n"   "..XXX.XXX......."   // 3B 80
  "\n"   ".XXX...XXX......"   // 71 C0
  "\n"   "XXX.....XXX....."   // E0 E0
  "\n"   "XX.......XX....." , // C0 60

  "y" /* UTF-8 79 - Glyph 90 */

  "\n"   "......XXXXXX...."   // 03 F0
  "\n"   ".....XXXXXXX...."   // 07 F0
  "\n"   "XX..XXX........."   // CE 00
  "\n"   "XX..XX.........."   // CC 00
  "\n"   "XX..XX.........."   // CC 00
  "\n"   "XX..XXX........."   // CE 00
  "\n"   "XX...XXX........"   // C7 00
  "\n"   "XXX...XXXX......"   // E3 C0
  "\n"   ".XXXXXXXXXXX...."   // 7F F0
  "\n"   "..XXXXXXXXXX...." , // 3F F0

  "z" /* UTF-8 7A - Glyph 91 */

  "\n"   "XX.......XX....."   // C0 60
  "\n"   "XXX......XX....."   // E0 60
  "\n"   "XXXX.....XX....."   // F0 60
  "\n"   "XXXXX....XX....."   // F8 60
  "\n"   "XX.XXX...XX....."   // DC 60
  "\n"   "XX..XXX..XX....."   // CE 60
  "\n"   "XX...XXX.XX....."   // C7 60
  "\n"   "XX....XXXXX....."   // C3 E0
  "\n"   "XX.....XXXX....."   // C1 E0
  "\n"   "XX......XXX....." , // C0 E0

  "{" /* UTF-8 7B - Glyph 92 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   ".......XX......."   // 01 80
  "\n"   ".......XX......."   // 01 80
  "\n"   "..XXXXXXXXXXXX.."   // 3F FC
  "\n"   "XXXXXXX..XXXXXXX"   // FE 7F
  "\n"   "XXX..........XXX"   // E0 07
  "\n"   "XXX..........XXX" , // E0 07

  "|" /* UTF-8 7C - Glyph 93 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "XXXXXXXXXXXXXXXX"   // FF FF
  "\n"   "XXXXXXXXXXXXXXXX" , // FF FF

  "}" /* UTF-8 7D - Glyph 94 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "XXX..........XXX"   // E0 07
  "\n"   "XXX..........XXX"   // E0 07
  "\n"   "XXXXXXX..XXXXXXX"   // FE 7F
  "\n"   "..XXXXXXXXXXXX.."   // 3F FC
  "\n"   ".......XX......."   // 01 80
  "\n"   ".......XX......." , // 01 80

  "~" /* UTF-8 7E - Glyph 95 */

  "\n"   ".....XX........."   // 06 00
  "\n"   "......XX........"   // 03 00
  "\n"   ".......XX......."   // 01 80
  "\n"   ".......XX......."   // 01 80
  "\n"   "......XXX......."   // 03 80
  "\n"   ".....XXX........"   // 07 00
  "\n"   ".....XX........."   // 06 00
  "\n"   ".....XX........."   // 06 00
  "\n"   "......XX........"   // 03 00
  "\n"   ".......XX......." , // 01 80

  "À" /* UTF-8 C3 80 - Glyph 96 */

  "\n"   "XXXXXXXX........"   // FF 00
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "...XX..XXX.....X"   // 19 C1
  "\n"   "...XX...XXX...XX"   // 18 E3
  "\n"   "...XX....XXX..XX"   // 18 73
  "\n"   "...XX....XXX.XX."   // 18 76
  "\n"   "...XX...XXX..X.."   // 18 E4
  "\n"   "...XX..XXX......"   // 19 C0
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "XXXXXXXX........" , // FF 00

  "Á" /* UTF-8 C3 81 - Glyph 97 */

  "\n"   "XXXXXXXX........"   // FF 00
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "...XX..XXX......"   // 19 C0
  "\n"   "...XX...XXX..X.."   // 18 E4
  "\n"   "...XX....XXX.XX."   // 18 76
  "\n"   "...XX....XXX..XX"   // 18 73
  "\n"   "...XX...XXX...XX"   // 18 E3
  "\n"   "...XX..XXX.....X"   // 19 C1
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "XXXXXXXX........" , // FF 00

  "Â" /* UTF-8 C3 82 - Glyph 98 */

  "\n"   "XXXXXXXX........"   // FF 00
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "...XX..XXX...X.."   // 19 C4
  "\n"   "...XX...XXX..XX."   // 18 E6
  "\n"   "...XX....XXX..XX"   // 18 73
  "\n"   "...XX....XXX..XX"   // 18 73
  "\n"   "...XX...XXX..XX."   // 18 E6
  "\n"   "...XX..XXX...X.."   // 19 C4
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "XXXXXXXX........" , // FF 00

  "Ä" /* UTF-8 C3 84 - Glyph 99 */

  "\n"   "XXXXXXXX........"   // FF 00
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "...XX..XXX....XX"   // 19 C3
  "\n"   "...XX...XXX...XX"   // 18 E3
  "\n"   "...XX....XXX...."   // 18 70
  "\n"   "...XX....XXX...."   // 18 70
  "\n"   "...XX...XXX...XX"   // 18 E3
  "\n"   "...XX..XXX....XX"   // 19 C3
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "XXXXXXXX........" , // FF 00

  "È" /* UTF-8 C3 88 - Glyph 100 */

  "\n"   "XXXXXXXXXXXX...."   // FF F0
  "\n"   "XXXXXXXXXXXX...."   // FF F0
  "\n"   "XX...XX...XX...X"   // C6 31
  "\n"   "XX...XX...XX..XX"   // C6 33
  "\n"   "XX...XX...XX..XX"   // C6 33
  "\n"   "XX...XX...XX.XX."   // C6 36
  "\n"   "XX...XX...XX.X.."   // C6 34
  "\n"   "XX...XX...XX...."   // C6 30
  "\n"   "XX........XX...."   // C0 30
  "\n"   "XX........XX...." , // C0 30

  "É" /* UTF-8 C3 89 - Glyph 101 */

  "\n"   "XXXXXXXXXXXX...."   // FF F0
  "\n"   "XXXXXXXXXXXX...."   // FF F0
  "\n"   "XX...XX...XX...."   // C6 30
  "\n"   "XX...XX...XX.X.."   // C6 34
  "\n"   "XX...XX...XX.XX."   // C6 36
  "\n"   "XX...XX...XX..XX"   // C6 33
  "\n"   "XX...XX...XX..XX"   // C6 33
  "\n"   "XX...XX...XX...X"   // C6 31
  "\n"   "XX........XX...."   // C0 30
  "\n"   "XX........XX...." , // C0 30

  "Ê" /* UTF-8 C3 8A - Glyph 102 */

  "\n"   "XXXXXXXXXXXX...."   // FF F0
  "\n"   "XXXXXXXXXXXX...."   // FF F0
  "\n"   "XX...XX...XX.X.."   // C6 34
  "\n"   "XX...XX...XX.XX."   // C6 36
  "\n"   "XX...XX...XX..XX"   // C6 33
  "\n"   "XX...XX...XX..XX"   // C6 33
  "\n"   "XX...XX...XX.XX."   // C6 36
  "\n"   "XX...XX...XX.X.."   // C6 34
  "\n"   "XX........XX...."   // C0 30
  "\n"   "XX........XX...." , // C0 30

  "Ö" /* UTF-8 C3 96 - Glyph 103 */

  "\n"   "..XXXXXXXX......"   // 3F C0
  "\n"   ".XXXXXXXXXX....."   // 7F E0
  "\n"   "XXX......XXX..XX"   // E0 73
  "\n"   "XX........XX..XX"   // C0 33
  "\n"   "XX........XX...."   // C0 30
  "\n"   "XX........XX...."   // C0 30
  "\n"   "XX........XX..XX"   // C0 33
  "\n"   "XXX......XXX..XX"   // E0 73
  "\n"   ".XXXXXXXXXX....."   // 7F E0
  "\n"   "..XXXXXXXX......" , // 3F C0

  "Ü" /* UTF-8 C3 9C - Glyph 104 */

  "\n"   "..XXXXXXXXXX...."   // 3F F0
  "\n"   ".XXXXXXXXXXX...."   // 7F F0
  "\n"   "XXX...........XX"   // E0 03
  "\n"   "XX............XX"   // C0 03
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX............XX"   // C0 03
  "\n"   "XXX...........XX"   // E0 03
  "\n"   ".XXXXXXXXXXX...."   // 7F F0
  "\n"   "..XXXXXXXXXX...." , // 3F F0

  "à" /* UTF-8 C3 A0 - Glyph 105 */

  "\n"   "..XXX..........."   // 38 00
  "\n"   ".XXXXX.........."   // 7C 00
  "\n"   "XXX.XXX.XX...X.."   // EE C4
  "\n"   "XX...XX.XX..XX.."   // C6 CC
  "\n"   "XX...XX.XX..XX.."   // C6 CC
  "\n"   "XX...XX.XX.XX..."   // C6 D8
  "\n"   "XX...XX.XX.X...."   // C6 D0
  "\n"   ".XX.XX..XX......"   // 6C C0
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "XXXXXXXX........" , // FF 00

  "á" /* UTF-8 C3 A1 - Glyph 106 */

  "\n"   "..XXX..........."   // 38 00
  "\n"   ".XXXXX.........."   // 7C 00
  "\n"   "XXX.XXX.XX......"   // EE C0
  "\n"   "XX...XX.XX.X...."   // C6 D0
  "\n"   "XX...XX.XX.XX..."   // C6 D8
  "\n"   "XX...XX.XX..XX.."   // C6 CC
  "\n"   "XX...XX.XX..XX.."   // C6 CC
  "\n"   ".XX.XX..XX...X.."   // 6C C4
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "XXXXXXXX........" , // FF 00

  "â" /* UTF-8 C3 A2 - Glyph 107 */

  "\n"   "..XXX..........."   // 38 00
  "\n"   ".XXXXX.........."   // 7C 00
  "\n"   "XXX.XXX.XX.X...."   // EE D0
  "\n"   "XX...XX.XX.XX..."   // C6 D8
  "\n"   "XX...XX.XX..XX.."   // C6 CC
  "\n"   "XX...XX.XX..XX.."   // C6 CC
  "\n"   "XX...XX.XX.XX..."   // C6 D8
  "\n"   ".XX.XX..XX.X...."   // 6C D0
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "XXXXXXXX........" , // FF 00

  "ä" /* UTF-8 C3 A4 - Glyph 108 */

  "\n"   "..XXX..........."   // 38 00
  "\n"   ".XXXXX.........."   // 7C 00
  "\n"   "XXX.XXX.XX..XX.."   // EE CC
  "\n"   "XX...XX.XX..XX.."   // C6 CC
  "\n"   "XX...XX.XX......"   // C6 C0
  "\n"   "XX...XX.XX......"   // C6 C0
  "\n"   "XX...XX.XX..XX.."   // C6 CC
  "\n"   ".XX.XX..XX..XX.."   // 6C CC
  "\n"   "XXXXXXXXX......."   // FF 80
  "\n"   "XXXXXXXX........" , // FF 00

  "ç" /* UTF-8 C3 A7 - Glyph 109 */

  "\n"   ".....XXXXXX....."   // 07 E0
  "\n"   "....XXXXXXXX...."   // 0F F0
  "\n"   "X..XXX....XXX..."   // 9C 38
  "\n"   "XX.XX......XX..."   // D8 18
  "\n"   "XXXXX......XX..."   // F8 18
  "\n"   ".XXXX......XX..."   // 78 18
  "\n"   "..XXX......XX..."   // 38 18
  "\n"   "...XXX....XXX..."   // 1C 38
  "\n"   "....XXX..XXX...."   // 0E 70
  "\n"   ".....XX..XX....." , // 06 60

  "è" /* UTF-8 C3 A8 - Glyph 110 */

  "\n"   "..XXXXXX........"   // 3F 00
  "\n"   ".XXXXXXXX......."   // 7F 80
  "\n"   "XXX.XX.XXX...X.."   // ED C4
  "\n"   "XX..XX..XX..XX.."   // CC CC
  "\n"   "XX..XX..XX..XX.."   // CC CC
  "\n"   "XX..XX..XX.XX..."   // CC D8
  "\n"   "XX..XX..XX.X...."   // CC D0
  "\n"   "XXX.XX.XXX......"   // ED C0
  "\n"   ".XX.XXXXX......."   // 6F 80
  "\n"   "..X..XXX........" , // 27 00

  "é" /* UTF-8 C3 A9 - Glyph 111 */

  "\n"   "..XXXXXX........"   // 3F 00
  "\n"   ".XXXXXXXX......."   // 7F 80
  "\n"   "XXX.XX.XXX......"   // ED C0
  "\n"   "XX..XX..XX.X...."   // CC D0
  "\n"   "XX..XX..XX.XX..."   // CC D8
  "\n"   "XX..XX..XX..XX.."   // CC CC
  "\n"   "XX..XX..XX..XX.."   // CC CC
  "\n"   "XXX.XX.XXX...X.."   // ED C4
  "\n"   ".XX.XXXXX......."   // 6F 80
  "\n"   "..X..XXX........" , // 27 00

  "ê" /* UTF-8 C3 AA - Glyph 112 */

  "\n"   "..XXXXXX........"   // 3F 00
  "\n"   ".XXXXXXXX......."   // 7F 80
  "\n"   "XXX.XX.XXX.X...."   // ED D0
  "\n"   "XX..XX..XX.XX..."   // CC D8
  "\n"   "XX..XX..XX..XX.."   // CC CC
  "\n"   "XX..XX..XX..XX.."   // CC CC
  "\n"   "XX..XX..XX.XX..."   // CC D8
  "\n"   "XXX.XX.XXX.X...."   // ED D0
  "\n"   ".XX.XXXXX......."   // 6F 80
  "\n"   "..X..XXX........" , // 27 00

  "ë" /* UTF-8 C3 AB - Glyph 113 */

  "\n"   "..XXXXXX........"   // 3F 00
  "\n"   ".XXXXXXXX......."   // 7F 80
  "\n"   "XXX.XX.XXX..XX.."   // ED CC
  "\n"   "XX..XX..XX..XX.."   // CC CC
  "\n"   "XX..XX..XX......"   // CC C0
  "\n"   "XX..XX..XX......"   // CC C0
  "\n"   "XX..XX..XX..XX.."   // CC CC
  "\n"   "XXX.XX.XXX..XX.."   // ED CC
  "\n"   ".XX.XXXXX......."   // 6F 80
  "\n"   "..X..XXX........" , // 27 00

  "ì" /* UTF-8 C3 AC - Glyph 114 */

  "\n"   "................"   // 00 00
  "\n"   ".............X.."   // 00 04
  "\n"   ".......XX...XX.."   // 01 8C
  "\n"   ".......XX...XX.."   // 01 8C
  "\n"   "..XXXXXXX..XX..."   // 3F 98
  "\n"   ".XXXXXXXX..X...."   // 7F 90
  "\n"   "XXX............."   // E0 00
  "\n"   "XX.............." , // C0 00

  "í" /* UTF-8 C3 AD - Glyph 115 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   ".......XX......."   // 01 80
  "\n"   ".......XX..X...."   // 01 90
  "\n"   "..XXXXXXX..XX..."   // 3F 98
  "\n"   ".XXXXXXXX...XX.."   // 7F 8C
  "\n"   "XXX.........XX.."   // E0 0C
  "\n"   "XX...........X.." , // C0 04

  "î" /* UTF-8 C3 AE - Glyph 116 */

  "\n"   "................"   // 00 00
  "\n"   "...........X...."   // 00 10
  "\n"   ".......XX..XX..."   // 01 98
  "\n"   ".......XX...XX.."   // 01 8C
  "\n"   "..XXXXXXX...XX.."   // 3F 8C
  "\n"   ".XXXXXXXX..XX..."   // 7F 98
  "\n"   "XXX........X...."   // E0 10
  "\n"   "XX.............." , // C0 00

  "ï" /* UTF-8 C3 AF - Glyph 117 */

  "\n"   "................"   // 00 00
  "\n"   "............XX.."   // 00 0C
  "\n"   ".......XX...XX.."   // 01 8C
  "\n"   ".......XX......."   // 01 80
  "\n"   "..XXXXXXX......."   // 3F 80
  "\n"   ".XXXXXXXX...XX.."   // 7F 8C
  "\n"   "XXX.........XX.."   // E0 0C
  "\n"   "XX.............." , // C0 00

  "ö" /* UTF-8 C3 B6 - Glyph 118 */

  "\n"   "..XXXXXX........"   // 3F 00
  "\n"   ".XXXXXXXX......."   // 7F 80
  "\n"   "XXX....XXX..XX.."   // E1 CC
  "\n"   "XX......XX..XX.."   // C0 CC
  "\n"   "XX......XX......"   // C0 C0
  "\n"   "XX......XX......"   // C0 C0
  "\n"   "XX......XX..XX.."   // C0 CC
  "\n"   "XXX....XXX..XX.."   // E1 CC
  "\n"   ".XXXXXXXX......."   // 7F 80
  "\n"   "..XXXXXX........" , // 3F 00

  "ü" /* UTF-8 C3 BC - Glyph 119 */

  "\n"   "..XXXXXXXX......"   // 3F C0
  "\n"   ".XXXXXXXXX......"   // 7F C0
  "\n"   "XXX.........XX.."   // E0 0C
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XX.............."   // C0 00
  "\n"   "XX.............."   // C0 00
  "\n"   "XX..........XX.."   // C0 0C
  "\n"   "XXX.........XX.."   // E0 0C
  "\n"   ".XXXXXXXXX......"   // 7F C0
  "\n"   "..XXXXXXXX......" , // 3F C0

  "–" /* UTF-8 E2 80 93 - Glyph 120 */

  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........."   // 0C 00
  "\n"   "....XX.........." , // 0C 00

  "’" /* UTF-8 E2 80 99 - Glyph 121 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "........X..XXX.."   // 00 9C
  "\n"   ".........XXXXX.."   // 00 7C
  "\n"   "..........XXXX.." , // 00 3C

  "•" /* UTF-8 E2 80 A2 - Glyph 122 */

  "\n"   "................"   // 00 00
  "\n"   "................"   // 00 00
  "\n"   "......XXX......."   // 03 80
  "\n"   ".....XXXXX......"   // 07 C0
  "\n"   ".....XXXXX......"   // 07 C0
  "\n"   ".....XXXXX......"   // 07 C0
  "\n"   ".....XXXXX......"   // 07 C0
  "\n"   "......XXX......." , // 03 80

  nullptr // terminator
};

// MARK: - end of generated font verification data


#endif // GENERATE_FONT_SOURCE


// MARK: - 'vcr_osd_mono' generated font data

static const glyph_t font_vcr_osd_mono_glyphs[] = {
  {  9, "\xff\xff\x80\x01\x80\x01\x80\x01\x80\x01\x80\x01\x80\x01\x80\x01\xff\xff" },  // placeholder          (input # 0 -> glyph # 0)
  {  9, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" },  // ' ' UTF-8 20         (input # 1 -> glyph # 1)
  {  5, "\x00\x00\x00\x00\x00\x00\xcf\xfc\xcf\xfc" },  // '!' UTF-8 21         (input # 2 -> glyph # 2)
  {  9, "\x00\x00\x00\x1c\x00\x3c\x00\x1c\x00\x00\x00\x00\x00\x1c\x00\x3c\x00\x1c" },  // '"' UTF-8 22         (input # 3 -> glyph # 3)
  { 10, "\x18\xc0\x18\xc0\x7f\xf8\x7f\xf8\x0c\x60\x0c\x60\x3f\xfc\x3f\xfc\x06\x30\x06\x30" },  // '#' UTF-8 23         (input # 4 -> glyph # 4)
  { 10, "\x18\xe0\x39\xf0\x73\xb8\x63\x18\xff\xfc\xff\xfc\x63\x18\x77\x38\x3e\x70\x1c\x60" },  // '$' UTF-8 24         (input # 5 -> glyph # 5)
  { 10, "\xf0\x78\xf8\xfc\x1c\xcc\x0e\xfc\x07\x78\x7b\x80\xfd\xc0\xcc\xe0\xfc\x7c\x78\x3c" },  // '%' UTF-8 25         (input # 6 -> glyph # 6)
  { 10, "\x3e\x00\x7f\x3c\xe3\xfe\xc3\xc3\xc7\x83\xcf\xc3\xfc\xfe\x78\x3c\xfc\x00\xcc\x00" },  // '&' UTF-8 26         (input # 7 -> glyph # 7)
  {  6, "\x00\x00\x00\x00\x00\x00\x00\x1c\x00\x3c\x00\x1c" },  // ''' UTF-8 27         (input # 8 -> glyph # 8)
  {  7, "\x00\x00\x00\x00\x1f\xf8\x3f\xfc\x60\x06\xc0\x03\x80\x01" },  // '(' UTF-8 28         (input # 9 -> glyph # 9)
  {  8, "\x00\x00\x00\x00\x00\x00\x80\x01\xc0\x03\x60\x06\x3f\xfc\x1f\xf8" },  // ')' UTF-8 29         (input # 10 -> glyph # 10)
  {  9, "\x00\x00\x01\x8c\x00\xd8\x00\x70\x03\xfe\x03\xfe\x00\x70\x00\xd8\x01\x8c" },  // '*' UTF-8 2A         (input # 11 -> glyph # 11)
  { 10, "\x03\x00\x03\x00\x03\x00\x03\x00\x3f\xf0\x3f\xf0\x03\x00\x03\x00\x03\x00\x03\x00" },  // '+' UTF-8 2B         (input # 12 -> glyph # 12)
  {  6, "\x00\x00\x00\x00\x80\x00\xc0\x00\x70\x00\x30\x00" },  // ',' UTF-8 2C         (input # 13 -> glyph # 13)
  {  9, "\x00\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00" },  // '-' UTF-8 2D         (input # 14 -> glyph # 14)
  {  5, "\x00\x00\x00\x00\x00\x00\xc0\x00\xc0\x00" },  // '.' UTF-8 2E         (input # 15 -> glyph # 15)
  { 10, "\xf0\x00\xf8\x00\x1c\x00\x0e\x00\x07\x00\x03\x80\x01\xc0\x00\xe0\x00\x7c\x00\x3c" },  // '/' UTF-8 2F         (input # 16 -> glyph # 16)
  { 10, "\x3f\xf0\x7f\xf8\xec\x1c\xce\x0c\xc7\x0c\xc3\x8c\xc1\xcc\xe0\xdc\x7f\xf8\x3f\xf0" },  // '0' UTF-8 30         (input # 17 -> glyph # 17)
  {  8, "\x00\x00\x00\x00\xc0\x30\xc0\x38\xff\xfc\xff\xfc\xc0\x00\xc0\x00" },  // '1' UTF-8 31         (input # 18 -> glyph # 18)
  { 10, "\xfc\x30\xfe\x38\xc7\x1c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x9c\xc1\xf8\xc0\xf0" },  // '2' UTF-8 32         (input # 19 -> glyph # 19)
  { 10, "\x30\x30\x70\x38\xe0\x1c\xc0\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe7\x9c\x7f\xf8\x3c\xf0" },  // '3' UTF-8 33         (input # 20 -> glyph # 20)
  { 10, "\x0f\x00\x0f\x80\x0d\xc0\x0c\xe0\x0c\x70\x0c\x38\xff\xfc\xff\xfc\x0c\x00\x0c\x00" },  // '4' UTF-8 34         (input # 21 -> glyph # 21)
  { 10, "\x30\xfc\x70\xfc\xe0\xcc\xc0\xcc\xc0\xcc\xc0\xcc\xc0\xcc\xe1\xcc\x7f\x8c\x3f\x0c" },  // '5' UTF-8 35         (input # 22 -> glyph # 22)
  { 10, "\x3f\xf0\x7f\xf8\xe3\x1c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe7\x1c\x7e\x38\x3c\x30" },  // '6' UTF-8 36         (input # 23 -> glyph # 23)
  { 10, "\x00\x0c\x00\x0c\x00\x0c\x00\x0c\xfe\x0c\xff\x0c\x03\x8c\x01\xcc\x00\xfc\x00\x7c" },  // '7' UTF-8 37         (input # 24 -> glyph # 24)
  { 10, "\x3c\xf0\x7f\xf8\xe7\x9c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe7\x9c\x7f\xf8\x3c\xf0" },  // '8' UTF-8 38         (input # 25 -> glyph # 25)
  { 10, "\x30\xf0\x71\xf8\xe3\x9c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe3\x1c\x7f\xf8\x3f\xf0" },  // '9' UTF-8 39         (input # 26 -> glyph # 26)
  {  5, "\x00\x00\x00\x00\x00\x00\x30\x30\x30\x30" },  // ':' UTF-8 3A         (input # 27 -> glyph # 27)
  {  5, "\x00\x00\x80\x00\xc0\x00\x70\x30\x30\x30" },  // ';' UTF-8 3B         (input # 28 -> glyph # 28)
  {  9, "\x00\x00\x03\x80\x07\xc0\x0e\xe0\x1c\x70\x38\x38\x70\x1c\xe0\x0e\xc0\x06" },  // '<' UTF-8 3C         (input # 29 -> glyph # 29)
  { 10, "\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0" },  // '=' UTF-8 3D         (input # 30 -> glyph # 30)
  {  9, "\x00\x00\xc0\x06\xe0\x0e\x70\x1c\x38\x38\x1c\x70\x0e\xe0\x07\xc0\x03\x80" },  // '>' UTF-8 3E         (input # 31 -> glyph # 31)
  { 10, "\x00\x30\x00\x38\x00\x1c\x00\x0c\xcc\x0c\xce\x0c\x07\x0c\x03\x9c\x01\xf8\x00\xf0" },  // '?' UTF-8 3F         (input # 32 -> glyph # 32)
  { 10, "\x1f\xe0\x30\x30\x67\x98\x4f\xc8\x48\x48\x4f\x88\x47\xc8\x68\x18\x2c\x30\x07\xe0" },  // '@' UTF-8 40         (input # 33 -> glyph # 33)
  { 10, "\xff\xc0\xff\xe0\x0c\x70\x0c\x38\x0c\x1c\x0c\x1c\x0c\x38\x0c\x70\xff\xe0\xff\xc0" },  // 'A' UTF-8 41         (input # 34 -> glyph # 34)
  { 10, "\xff\xfc\xff\xfc\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe7\x9c\x7f\xf8\x3c\xf0" },  // 'B' UTF-8 42         (input # 35 -> glyph # 35)
  { 10, "\x3f\xf0\x7f\xf8\xe0\x1c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xe0\x1c\x70\x38\x30\x30" },  // 'C' UTF-8 43         (input # 36 -> glyph # 36)
  { 10, "\xff\xfc\xff\xfc\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xe0\x1c\x7f\xf8\x3f\xf0" },  // 'D' UTF-8 44         (input # 37 -> glyph # 37)
  { 10, "\xff\xfc\xff\xfc\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xc0\x0c\xc0\x0c" },  // 'E' UTF-8 45         (input # 38 -> glyph # 38)
  { 10, "\xff\xfc\xff\xfc\x03\x0c\x03\x0c\x03\x0c\x03\x0c\x03\x0c\x03\x0c\x00\x0c\x00\x0c" },  // 'F' UTF-8 46         (input # 39 -> glyph # 39)
  { 10, "\x3f\xf0\x7f\xf8\xe0\x1c\xc0\x0c\xc0\x0c\xc3\x0c\xc3\x0c\xe3\x1c\x7f\x38\x3f\x30" },  // 'G' UTF-8 47         (input # 40 -> glyph # 40)
  { 10, "\xff\xfc\xff\xfc\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\xff\xfc\xff\xfc" },  // 'H' UTF-8 48         (input # 41 -> glyph # 41)
  {  8, "\x00\x00\x00\x00\xc0\x0c\xc0\x0c\xff\xfc\xff\xfc\xc0\x0c\xc0\x0c" },  // 'I' UTF-8 49         (input # 42 -> glyph # 42)
  { 10, "\x30\x00\x70\x00\xe0\x00\xc0\x00\xc0\x0c\xe0\x0c\x7f\xfc\x3f\xfc\x00\x0c\x00\x0c" },  // 'J' UTF-8 4A         (input # 43 -> glyph # 43)
  { 10, "\xff\xfc\xff\xfc\x03\x00\x07\x80\x0f\xc0\x1c\xe0\x38\x70\x70\x38\xe0\x1c\xc0\x0c" },  // 'K' UTF-8 4B         (input # 44 -> glyph # 44)
  { 10, "\xff\xfc\xff\xfc\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00" },  // 'L' UTF-8 4C         (input # 45 -> glyph # 45)
  { 10, "\xff\xfc\xff\xfc\x00\x70\x00\xe0\x03\xc0\x03\xc0\x00\xe0\x00\x70\xff\xfc\xff\xfc" },  // 'M' UTF-8 4D         (input # 46 -> glyph # 46)
  { 10, "\xff\xfc\xff\xfc\x00\xe0\x01\xc0\x03\x80\x07\x00\x0e\x00\x1c\x00\xff\xfc\xff\xfc" },  // 'N' UTF-8 4E         (input # 47 -> glyph # 47)
  { 10, "\x3f\xf0\x7f\xf8\xe0\x1c\xc0\x0c\xc0\x0c\xc0\x0c\xc0\x0c\xe0\x1c\x7f\xf8\x3f\xf0" },  // 'O' UTF-8 4F         (input # 48 -> glyph # 48)
  { 10, "\xff\xfc\xff\xfc\x03\x0c\x03\x0c\x03\x0c\x03\x0c\x03\x0c\x03\x9c\x01\xf8\x00\xf0" },  // 'P' UTF-8 50         (input # 49 -> glyph # 49)
  { 10, "\x3f\xf0\x7f\xf8\xe0\x1c\xc0\x0c\xcc\x0c\xdc\x0c\x78\x0c\x70\x1c\xff\xf8\xdf\xf0" },  // 'Q' UTF-8 51         (input # 50 -> glyph # 50)
  { 10, "\xff\xfc\xff\xfc\x03\x0c\x07\x0c\x0f\x0c\x1f\x0c\x3b\x0c\x73\x9c\xe1\xf8\xc0\xf0" },  // 'R' UTF-8 52         (input # 51 -> glyph # 51)
  { 10, "\x30\xf0\x71\xf8\xe3\x9c\xc3\x0c\xc3\x0c\xc3\x0c\xc3\x0c\xe7\x1c\x7e\x38\x3c\x30" },  // 'S' UTF-8 53         (input # 52 -> glyph # 52)
  { 10, "\x00\x0c\x00\x0c\x00\x0c\x00\x0c\xff\xfc\xff\xfc\x00\x0c\x00\x0c\x00\x0c\x00\x0c" },  // 'T' UTF-8 54         (input # 53 -> glyph # 53)
  { 10, "\x3f\xfc\x7f\xfc\xe0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xe0\x00\x7f\xfc\x3f\xfc" },  // 'U' UTF-8 55         (input # 54 -> glyph # 54)
  { 10, "\x0f\xfc\x1f\xfc\x38\x00\x70\x00\xe0\x00\xe0\x00\x70\x00\x38\x00\x1f\xfc\x0f\xfc" },  // 'V' UTF-8 56         (input # 55 -> glyph # 55)
  { 10, "\x3f\xfc\x7f\xfc\xe0\x00\xe0\x00\x7f\x00\x7f\x00\xe0\x00\xe0\x00\x7f\xfc\x3f\xfc" },  // 'W' UTF-8 57         (input # 56 -> glyph # 56)
  { 10, "\xf0\x3c\xf8\x7c\x1c\xe0\x0f\xc0\x07\x80\x07\x80\x0f\xc0\x1c\xe0\xf8\x7c\xf0\x3c" },  // 'X' UTF-8 58         (input # 57 -> glyph # 57)
  { 10, "\x00\xfc\x01\xfc\x03\x80\x07\x00\xfe\x00\xfe\x00\x07\x00\x03\x80\x01\xfc\x00\xfc" },  // 'Y' UTF-8 59         (input # 58 -> glyph # 58)
  { 10, "\xf0\x0c\xf8\x0c\xdc\x0c\xce\x0c\xc7\x0c\xc3\x8c\xc1\xcc\xc0\xec\xc0\x7c\xc0\x3c" },  // 'Z' UTF-8 5A         (input # 59 -> glyph # 59)
  {  9, "\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\xc0\x03\xc0\x03\xc0\x03\xc0\x03" },  // '[' UTF-8 5B         (input # 60 -> glyph # 60)
  { 10, "\x00\x3c\x00\x7c\x00\xe0\x01\xc0\x03\x80\x07\x00\x0e\x00\x1c\x00\xf8\x00\xf0\x00" },  // '\' UTF-8 5C         (input # 61 -> glyph # 61)
  {  7, "\x00\x00\xc0\x03\xc0\x03\xc0\x03\xc0\x03\xff\xff\xff\xff" },  // ']' UTF-8 5D         (input # 62 -> glyph # 62)
  { 10, "\x00\x40\x00\x60\x00\x70\x00\x38\x00\x1c\x00\x1c\x00\x38\x00\x70\x00\x60\x00\x40" },  // '^' UTF-8 5E         (input # 63 -> glyph # 63)
  { 11, "\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00\x80\x00" },  // '_' UTF-8 5F         (input # 64 -> glyph # 64)
  {  7, "\x00\x00\x00\x00\x00\x04\x00\x0c\x00\x0c\x00\x18\x00\x10" },  // '`' UTF-8 60         (input # 65 -> glyph # 65)
  { 10, "\x3c\x00\x7e\x00\xe7\x30\xc3\x30\xc3\x30\xc3\x30\xc3\x30\x66\x70\xff\xe0\xff\xc0" },  // 'a' UTF-8 61         (input # 66 -> glyph # 66)
  { 10, "\xff\xfc\xff\xfc\x3f\x80\x71\xc0\xe0\xe0\xc0\x60\xe0\xe0\x71\xc0\x3f\x80\x1f\x00" },  // 'b' UTF-8 62         (input # 67 -> glyph # 67)
  { 10, "\x3f\x80\x7f\xc0\xe0\xe0\xc0\x60\xc0\x60\xc0\x60\xc0\x60\xe0\xe0\x71\xc0\x31\x80" },  // 'c' UTF-8 63         (input # 68 -> glyph # 68)
  { 10, "\x1f\x00\x3f\x80\x71\xc0\xe0\xe0\xc0\x60\xe0\xe0\x71\xc0\x3f\x80\xff\xfc\xff\xfc" },  // 'd' UTF-8 64         (input # 69 -> glyph # 69)
  { 10, "\x3f\x80\x7f\xc0\xe6\xe0\xc6\x60\xc6\x60\xc6\x60\xc6\x60\xe6\xe0\x67\xc0\x23\x80" },  // 'e' UTF-8 65         (input # 70 -> glyph # 70)
  {  9, "\x00\x00\x00\x60\x00\x60\x00\x60\xff\xf8\xff\xfc\x00\x6c\x00\x6c\x00\x6c" },  // 'f' UTF-8 66         (input # 71 -> glyph # 71)
  { 10, "\x01\xc0\x63\xe0\xe7\x70\xc6\x30\xc6\x30\xc6\x30\xc6\x30\xe3\x70\x7f\xe0\x3f\xc0" },  // 'g' UTF-8 67         (input # 72 -> glyph # 72)
  { 10, "\xff\xfc\xff\xfc\x03\x80\x01\xc0\x00\xe0\x00\x60\x00\xe0\x01\xc0\xff\x80\xff\x00" },  // 'h' UTF-8 68         (input # 73 -> glyph # 73)
  {  8, "\x00\x00\x00\x00\x01\x80\x01\x80\x3f\x98\x7f\x98\xe0\x00\xc0\x00" },  // 'i' UTF-8 69         (input # 74 -> glyph # 74)
  {  8, "\x00\x00\x00\x00\xc0\x00\xc0\x00\xc0\x60\xe0\x60\x7f\xe6\x3f\xe6" },  // 'j' UTF-8 6A         (input # 75 -> glyph # 75)
  { 10, "\xff\xfc\xff\xfc\x38\x00\x1c\x00\x0e\x00\x1f\x00\x3b\x80\x71\xc0\xe0\xe0\xc0\x60" },  // 'k' UTF-8 6B         (input # 76 -> glyph # 76)
  {  6, "\x00\x00\x00\x00\x00\x00\x00\x00\xff\xfc\xff\xfc" },  // 'l' UTF-8 6C         (input # 77 -> glyph # 77)
  { 10, "\xff\xe0\xff\xe0\x00\xc0\x00\x60\xff\xe0\xff\xe0\x00\x60\x00\xe0\xff\xc0\xff\x80" },  // 'm' UTF-8 6D         (input # 78 -> glyph # 78)
  { 10, "\xff\xe0\xff\xe0\x00\xc0\x00\x60\x00\x60\x00\x60\x00\x60\x00\xe0\xff\xc0\xff\x80" },  // 'n' UTF-8 6E         (input # 79 -> glyph # 79)
  { 10, "\x3f\x80\x7f\xc0\xe0\xe0\xc0\x60\xc0\x60\xc0\x60\xc0\x60\xe0\xe0\x7f\xc0\x3f\x80" },  // 'o' UTF-8 6F         (input # 80 -> glyph # 80)
  { 10, "\xff\xf0\xff\xf0\x0f\xe0\x1c\x70\x18\x30\x18\x30\x18\x30\x1c\x70\x0f\xe0\x07\xc0" },  // 'p' UTF-8 70         (input # 81 -> glyph # 81)
  { 10, "\x07\xc0\x0f\xe0\x1c\x70\x18\x30\x18\x30\x18\x30\x0c\x70\x1f\xe0\xff\xf0\xff\xf0" },  // 'q' UTF-8 71         (input # 82 -> glyph # 82)
  { 10, "\xff\xe0\xff\xe0\x03\x80\x01\xc0\x00\xe0\x00\x60\x00\x60\x00\xe0\x01\xc0\x01\x80" },  // 'r' UTF-8 72         (input # 83 -> glyph # 83)
  { 10, "\x31\x80\x73\xc0\xe3\xe0\xc6\x60\xc6\x60\xce\x60\xcc\x60\xfc\xe0\x79\xc0\x31\x80" },  // 's' UTF-8 73         (input # 84 -> glyph # 84)
  {  8, "\x00\x00\x00\x00\x00\x60\x00\x60\x3f\xfc\x7f\xfc\xe0\x60\xc0\x60" },  // 't' UTF-8 74         (input # 85 -> glyph # 85)
  { 10, "\x3f\xe0\x7f\xe0\xe0\x00\xc0\x00\xc0\x00\xc0\x00\xc0\x00\xe0\x00\x7f\xe0\x3f\xe0" },  // 'u' UTF-8 75         (input # 86 -> glyph # 86)
  { 10, "\x0f\xe0\x1f\xe0\x38\x00\x70\x00\xe0\x00\xe0\x00\x70\x00\x38\x00\x1f\xe0\x0f\xe0" },  // 'v' UTF-8 76         (input # 87 -> glyph # 87)
  { 10, "\x3f\xe0\x7f\xe0\xe0\x00\xc0\x00\x7e\x00\x7e\x00\xc0\x00\xe0\x00\x7f\xe0\x3f\xe0" },  // 'w' UTF-8 77         (input # 88 -> glyph # 88)
  { 10, "\xc0\x60\xe0\xe0\x71\xc0\x3b\x80\x1f\x00\x1f\x00\x3b\x80\x71\xc0\xe0\xe0\xc0\x60" },  // 'x' UTF-8 78         (input # 89 -> glyph # 89)
  { 10, "\x03\xf0\x07\xf0\xce\x00\xcc\x00\xcc\x00\xce\x00\xc7\x00\xe3\xc0\x7f\xf0\x3f\xf0" },  // 'y' UTF-8 79         (input # 90 -> glyph # 90)
  { 10, "\xc0\x60\xe0\x60\xf0\x60\xf8\x60\xdc\x60\xce\x60\xc7\x60\xc3\xe0\xc1\xe0\xc0\xe0" },  // 'z' UTF-8 7A         (input # 91 -> glyph # 91)
  {  8, "\x00\x00\x00\x00\x01\x80\x01\x80\x3f\xfc\xfe\x7f\xe0\x07\xe0\x07" },  // '{' UTF-8 7B         (input # 92 -> glyph # 92)
  {  6, "\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff" },  // '|' UTF-8 7C         (input # 93 -> glyph # 93)
  {  8, "\x00\x00\x00\x00\xe0\x07\xe0\x07\xfe\x7f\x3f\xfc\x01\x80\x01\x80" },  // '}' UTF-8 7D         (input # 94 -> glyph # 94)
  { 10, "\x06\x00\x03\x00\x01\x80\x01\x80\x03\x80\x07\x00\x06\x00\x06\x00\x03\x00\x01\x80" },  // '~' UTF-8 7E         (input # 95 -> glyph # 95)
  { 10, "\xff\x00\xff\x80\x19\xc1\x18\xe3\x18\x73\x18\x76\x18\xe4\x19\xc0\xff\x80\xff\x00" },  // 'À' UTF-8 C3 80     (input # 96 -> glyph # 96)
  { 10, "\xff\x00\xff\x80\x19\xc0\x18\xe4\x18\x76\x18\x73\x18\xe3\x19\xc1\xff\x80\xff\x00" },  // 'Á' UTF-8 C3 81     (input # 97 -> glyph # 97)
  { 10, "\xff\x00\xff\x80\x19\xc4\x18\xe6\x18\x73\x18\x73\x18\xe6\x19\xc4\xff\x80\xff\x00" },  // 'Â' UTF-8 C3 82     (input # 98 -> glyph # 98)
  { 10, "\xff\x00\xff\x80\x19\xc3\x18\xe3\x18\x70\x18\x70\x18\xe3\x19\xc3\xff\x80\xff\x00" },  // 'Ä' UTF-8 C3 84     (input # 99 -> glyph # 99)
  { 10, "\xff\xf0\xff\xf0\xc6\x31\xc6\x33\xc6\x33\xc6\x36\xc6\x34\xc6\x30\xc0\x30\xc0\x30" },  // 'È' UTF-8 C3 88     (input # 100 -> glyph # 100)
  { 10, "\xff\xf0\xff\xf0\xc6\x30\xc6\x34\xc6\x36\xc6\x33\xc6\x33\xc6\x31\xc0\x30\xc0\x30" },  // 'É' UTF-8 C3 89     (input # 101 -> glyph # 101)
  { 10, "\xff\xf0\xff\xf0\xc6\x34\xc6\x36\xc6\x33\xc6\x33\xc6\x36\xc6\x34\xc0\x30\xc0\x30" },  // 'Ê' UTF-8 C3 8A     (input # 102 -> glyph # 102)
  { 10, "\x3f\xc0\x7f\xe0\xe0\x73\xc0\x33\xc0\x30\xc0\x30\xc0\x33\xe0\x73\x7f\xe0\x3f\xc0" },  // 'Ö' UTF-8 C3 96     (input # 103 -> glyph # 103)
  { 10, "\x3f\xf0\x7f\xf0\xe0\x03\xc0\x03\xc0\x00\xc0\x00\xc0\x03\xe0\x03\x7f\xf0\x3f\xf0" },  // 'Ü' UTF-8 C3 9C     (input # 104 -> glyph # 104)
  { 10, "\x38\x00\x7c\x00\xee\xc4\xc6\xcc\xc6\xcc\xc6\xd8\xc6\xd0\x6c\xc0\xff\x80\xff\x00" },  // 'à' UTF-8 C3 A0     (input # 105 -> glyph # 105)
  { 10, "\x38\x00\x7c\x00\xee\xc0\xc6\xd0\xc6\xd8\xc6\xcc\xc6\xcc\x6c\xc4\xff\x80\xff\x00" },  // 'á' UTF-8 C3 A1     (input # 106 -> glyph # 106)
  { 10, "\x38\x00\x7c\x00\xee\xd0\xc6\xd8\xc6\xcc\xc6\xcc\xc6\xd8\x6c\xd0\xff\x80\xff\x00" },  // 'â' UTF-8 C3 A2     (input # 107 -> glyph # 107)
  { 10, "\x38\x00\x7c\x00\xee\xcc\xc6\xcc\xc6\xc0\xc6\xc0\xc6\xcc\x6c\xcc\xff\x80\xff\x00" },  // 'ä' UTF-8 C3 A4     (input # 108 -> glyph # 108)
  { 10, "\x07\xe0\x0f\xf0\x9c\x38\xd8\x18\xf8\x18\x78\x18\x38\x18\x1c\x38\x0e\x70\x06\x60" },  // 'ç' UTF-8 C3 A7     (input # 109 -> glyph # 109)
  { 10, "\x3f\x00\x7f\x80\xed\xc4\xcc\xcc\xcc\xcc\xcc\xd8\xcc\xd0\xed\xc0\x6f\x80\x27\x00" },  // 'è' UTF-8 C3 A8     (input # 110 -> glyph # 110)
  { 10, "\x3f\x00\x7f\x80\xed\xc0\xcc\xd0\xcc\xd8\xcc\xcc\xcc\xcc\xed\xc4\x6f\x80\x27\x00" },  // 'é' UTF-8 C3 A9     (input # 111 -> glyph # 111)
  { 10, "\x3f\x00\x7f\x80\xed\xd0\xcc\xd8\xcc\xcc\xcc\xcc\xcc\xd8\xed\xd0\x6f\x80\x27\x00" },  // 'ê' UTF-8 C3 AA     (input # 112 -> glyph # 112)
  { 10, "\x3f\x00\x7f\x80\xed\xcc\xcc\xcc\xcc\xc0\xcc\xc0\xcc\xcc\xed\xcc\x6f\x80\x27\x00" },  // 'ë' UTF-8 C3 AB     (input # 113 -> glyph # 113)
  {  8, "\x00\x00\x00\x04\x01\x8c\x01\x8c\x3f\x98\x7f\x90\xe0\x00\xc0\x00" },  // 'ì' UTF-8 C3 AC     (input # 114 -> glyph # 114)
  {  8, "\x00\x00\x00\x00\x01\x80\x01\x90\x3f\x98\x7f\x8c\xe0\x0c\xc0\x04" },  // 'í' UTF-8 C3 AD     (input # 115 -> glyph # 115)
  {  8, "\x00\x00\x00\x10\x01\x98\x01\x8c\x3f\x8c\x7f\x98\xe0\x10\xc0\x00" },  // 'î' UTF-8 C3 AE     (input # 116 -> glyph # 116)
  {  8, "\x00\x00\x00\x0c\x01\x8c\x01\x80\x3f\x80\x7f\x8c\xe0\x0c\xc0\x00" },  // 'ï' UTF-8 C3 AF     (input # 117 -> glyph # 117)
  { 10, "\x3f\x00\x7f\x80\xe1\xcc\xc0\xcc\xc0\xc0\xc0\xc0\xc0\xcc\xe1\xcc\x7f\x80\x3f\x00" },  // 'ö' UTF-8 C3 B6     (input # 118 -> glyph # 118)
  { 10, "\x3f\xc0\x7f\xc0\xe0\x0c\xc0\x0c\xc0\x00\xc0\x00\xc0\x0c\xe0\x0c\x7f\xc0\x3f\xc0" },  // 'ü' UTF-8 C3 BC     (input # 119 -> glyph # 119)
  { 11, "\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00" },  // '–' UTF-8 E2 80 93 (input # 120 -> glyph # 120)
  {  5, "\x00\x00\x00\x00\x00\x9c\x00\x7c\x00\x3c" },  // '’' UTF-8 E2 80 99 (input # 121 -> glyph # 121)
  {  8, "\x00\x00\x00\x00\x03\x80\x07\xc0\x07\xc0\x07\xc0\x07\xc0\x03\x80" },  // '•' UTF-8 E2 80 A2 (input # 122 -> glyph # 122)
};

static const GlyphRange font_vcr_osd_mono_ranges[] = {
  { "", 0x20, 0x7E, 1 }, //  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
  { "\xc3", 0x80, 0x82, 96 }, // ÀÁÂ
  { "\xc3", 0x84, 0x84, 99 }, // Ä
  { "\xc3", 0x88, 0x8A, 100 }, // ÈÉÊ
  { "\xc3", 0x96, 0x96, 103 }, // Ö
  { "\xc3", 0x9C, 0x9C, 104 }, // Ü
  { "\xc3", 0xA0, 0xA2, 105 }, // àáâ
  { "\xc3", 0xA4, 0xA4, 108 }, // ä
  { "\xc3", 0xA7, 0xAF, 109 }, // çèéêëìíîï
  { "\xc3", 0xB6, 0xB6, 118 }, // ö
  { "\xc3", 0xBC, 0xBC, 119 }, // ü
  { "\xe2\x80", 0x93, 0x93, 120 }, // –
  { "\xe2\x80", 0x99, 0x99, 121 }, // ’
  { "\xe2\x80", 0xA2, 0xA2, 122 }, // •
  { NULL, 0, 0, 0 }
};

static const font_t font_vcr_osd_mono = {
  .fontName = "vcr_osd_mono",
  .glyphHeight = 16,
  .numGlyphs = 123,
  .glyphRanges = font_vcr_osd_mono_ranges,
  .glyphs = font_vcr_osd_mono_glyphs
   #ifdef GENERATE_FONT_SOURCE
   , .glyphstrings = font_vcr_osd_mono_glyphstrings
   #endif
};

static BuiltinFontRegistrar r(font_vcr_osd_mono);

// MARK: - end of generated font data

