//  SPDX-License-Identifier: GPL-3.0-or-later
//
//  Autogenerated by p44lrgraphics font generator
//
//  Unknown (c) - font may be embedded in documents and temporarily loaded on
//                the remote system. Documents containing this font may be editable.

//  Include this file into a p44lrgraphics build to define a built-in font

#include "fonts.hpp"

using namespace p44;

#ifdef GENERATE_FONT_SOURCE

// Font author's copyright
static const char * font_5x5_copyright =
  "Unknown (c) - font may be embedded in documents and temporarily loaded on"
  " the remote system. Documents containing this font may be editable.";

// MARK: - '5x5' generated font verification data

static const char * font_5x5_glyphstrings[] = {
  "placeholder" /* 0x00 - Glyph 0 */

  "\n"   "XXXXXXXX"   // FF
  "\n"   "X......X"   // 81
  "\n"   "X......X"   // 81
  "\n"   "XXXXXXXX" , // FF

  " " /* UTF-8 20 - Glyph 1 */

  "\n"   "........"   // 00
  "\n"   "........"   // 00
  "\n"   "........"   // 00
  "\n"   "........" , // 00

  "!" /* UTF-8 21 - Glyph 2 */

  "\n"   "X.XXX..." , // B8

  "\"" /* UTF-8 22 - Glyph 3 */

  "\n"   "....XX.."   // 0C
  "\n"   "........"   // 00
  "\n"   "....XX.." , // 0C

  "#" /* UTF-8 23 - Glyph 4 */

  "\n"   ".X.X...."   // 50
  "\n"   "XXXXX..."   // F8
  "\n"   ".X.X...."   // 50
  "\n"   "XXXXX..."   // F8
  "\n"   ".X.X...." , // 50

  "$" /* UTF-8 24 - Glyph 5 */

  "\n"   "X.XXX..."   // B8
  "\n"   "X.X.X..."   // A8
  "\n"   "XXXXXX.."   // FC
  "\n"   "X.X.X..."   // A8
  "\n"   "XXX.X..." , // E8

  "%" /* UTF-8 25 - Glyph 6 */

  "\n"   "X...X..."   // 88
  "\n"   ".X......"   // 40
  "\n"   "..X....."   // 20
  "\n"   "...X...."   // 10
  "\n"   "X...X..." , // 88

  "&" /* UTF-8 26 - Glyph 7 */

  "\n"   ".X.X...."   // 50
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   ".X......"   // 40
  "\n"   "X.X....." , // A0

  "'" /* UTF-8 27 - Glyph 8 */

  "\n"   "....XX.." , // 0C

  "(" /* UTF-8 28 - Glyph 9 */

  "\n"   ".XXX...."   // 70
  "\n"   "X...X..." , // 88

  ")" /* UTF-8 29 - Glyph 10 */

  "\n"   "X...X..."   // 88
  "\n"   ".XXX...." , // 70

  "*" /* UTF-8 2A - Glyph 11 */

  "\n"   ".....X.."   // 04
  "\n"   "....XXX."   // 0E
  "\n"   ".....X.." , // 04

  "+" /* UTF-8 2B - Glyph 12 */

  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "XXXXX..."   // F8
  "\n"   "..X....."   // 20
  "\n"   "..X....." , // 20

  "," /* UTF-8 2C - Glyph 13 */

  "\n"   "X......." , // 80

  "-" /* UTF-8 2D - Glyph 14 */

  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....." , // 20

  "." /* UTF-8 2E - Glyph 15 */

  "\n"   "X......." , // 80

  "/" /* UTF-8 2F - Glyph 16 */

  "\n"   "XX......"   // C0
  "\n"   "..X....."   // 20
  "\n"   "...XX..." , // 18

  "0" /* UTF-8 30 - Glyph 17 */

  "\n"   "XXXXX..."   // F8
  "\n"   "XX..X..."   // C8
  "\n"   "X.X.X..."   // A8
  "\n"   "X..XX..."   // 98
  "\n"   "XXXXX..." , // F8

  "1" /* UTF-8 31 - Glyph 18 */

  "\n"   "X..X...."   // 90
  "\n"   "XXXXX..."   // F8
  "\n"   "X......." , // 80

  "2" /* UTF-8 32 - Glyph 19 */

  "\n"   "XX..X..."   // C8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X..X...." , // 90

  "3" /* UTF-8 33 - Glyph 20 */

  "\n"   "X...X..."   // 88
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "XX.XX..." , // D8

  "4" /* UTF-8 34 - Glyph 21 */

  "\n"   ".XXXX..."   // 78
  "\n"   ".X......"   // 40
  "\n"   "XXX....."   // E0
  "\n"   ".X......"   // 40
  "\n"   ".X......" , // 40

  "5" /* UTF-8 35 - Glyph 22 */

  "\n"   "X.XXX..."   // B8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   ".X..X..." , // 48

  "6" /* UTF-8 36 - Glyph 23 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "XXX.X..." , // E8

  "7" /* UTF-8 37 - Glyph 24 */

  "\n"   "....X..."   // 08
  "\n"   "....X..."   // 08
  "\n"   "XX..X..."   // C8
  "\n"   "..X.X..."   // 28
  "\n"   "...XX..." , // 18

  "8" /* UTF-8 38 - Glyph 25 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "XXXXX..." , // F8

  "9" /* UTF-8 39 - Glyph 26 */

  "\n"   "X.XXX..."   // B8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "XXXXX..." , // F8

  ":" /* UTF-8 3A - Glyph 27 */

  "\n"   "X...X..." , // 88

  ";" /* UTF-8 3B - Glyph 28 */

  "\n"   "X...X..." , // 88

  "<" /* UTF-8 3C - Glyph 29 */

  "\n"   "..X....."   // 20
  "\n"   ".X.X...."   // 50
  "\n"   "X...X..." , // 88

  "=" /* UTF-8 3D - Glyph 30 */

  "\n"   ".X.X...."   // 50
  "\n"   ".X.X...."   // 50
  "\n"   ".X.X...."   // 50
  "\n"   ".X.X...."   // 50
  "\n"   ".X.X...." , // 50

  ">" /* UTF-8 3E - Glyph 31 */

  "\n"   "X...X..."   // 88
  "\n"   ".X.X...."   // 50
  "\n"   "..X....." , // 20

  "?" /* UTF-8 3F - Glyph 32 */

  "\n"   "...X...."   // 10
  "\n"   "....X..."   // 08
  "\n"   "X.X.X..."   // A8
  "\n"   "...X...." , // 10

  "@" /* UTF-8 40 - Glyph 33 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..."   // 88
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.XXX..." , // B8

  "A" /* UTF-8 41 - Glyph 34 */

  "\n"   "XXXXX..."   // F8
  "\n"   ".X..X..."   // 48
  "\n"   ".X..X..."   // 48
  "\n"   ".X..X..."   // 48
  "\n"   "XXXXX..." , // F8

  "B" /* UTF-8 42 - Glyph 35 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "XX.XX..." , // D8

  "C" /* UTF-8 43 - Glyph 36 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X...X..." , // 88

  "D" /* UTF-8 44 - Glyph 37 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   ".XXX...." , // 70

  "E" /* UTF-8 45 - Glyph 38 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X...X..." , // 88

  "F" /* UTF-8 46 - Glyph 39 */

  "\n"   "XXXXX..."   // F8
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "....X..." , // 08

  "G" /* UTF-8 47 - Glyph 40 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X.X.X..."   // A8
  "\n"   "XXX.X..." , // E8

  "H" /* UTF-8 48 - Glyph 41 */

  "\n"   "XXXXX..."   // F8
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "XXXXX..." , // F8

  "I" /* UTF-8 49 - Glyph 42 */

  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..."   // 88
  "\n"   "X...X..." , // 88

  "J" /* UTF-8 4A - Glyph 43 */

  "\n"   "XX......"   // C0
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X...X..."   // 88
  "\n"   "XXXXX..." , // F8

  "K" /* UTF-8 4B - Glyph 44 */

  "\n"   "XXXXX..."   // F8
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   ".X.X...."   // 50
  "\n"   "X...X..." , // 88

  "L" /* UTF-8 4C - Glyph 45 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X......." , // 80

  "M" /* UTF-8 4D - Glyph 46 */

  "\n"   "XXXXX..."   // F8
  "\n"   "...X...."   // 10
  "\n"   "..X....."   // 20
  "\n"   "...X...."   // 10
  "\n"   "XXXXX..." , // F8

  "N" /* UTF-8 4E - Glyph 47 */

  "\n"   "XXXXX..."   // F8
  "\n"   "...X...."   // 10
  "\n"   "..X....."   // 20
  "\n"   ".X......"   // 40
  "\n"   "XXXXX..." , // F8

  "O" /* UTF-8 4F - Glyph 48 */

  "\n"   ".XXX...."   // 70
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   ".XXX...." , // 70

  "P" /* UTF-8 50 - Glyph 49 */

  "\n"   "XXXXX..."   // F8
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "...X...." , // 10

  "Q" /* UTF-8 51 - Glyph 50 */

  "\n"   ".XXXX..."   // 78
  "\n"   ".X..X..."   // 48
  "\n"   "XX..X..."   // C8
  "\n"   ".X..X..."   // 48
  "\n"   ".XXXX..." , // 78

  "R" /* UTF-8 52 - Glyph 51 */

  "\n"   "XXXXX..."   // F8
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "XX.X...." , // D0

  "S" /* UTF-8 53 - Glyph 52 */

  "\n"   "X.XXX..."   // B8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "XXX.X..." , // E8

  "T" /* UTF-8 54 - Glyph 53 */

  "\n"   "....X..."   // 08
  "\n"   "....X..."   // 08
  "\n"   "XXXXX..."   // F8
  "\n"   "....X..."   // 08
  "\n"   "....X..." , // 08

  "U" /* UTF-8 55 - Glyph 54 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "XXXXX..." , // F8

  "V" /* UTF-8 56 - Glyph 55 */

  "\n"   "...XX..."   // 18
  "\n"   ".XX....."   // 60
  "\n"   "X......."   // 80
  "\n"   ".XX....."   // 60
  "\n"   "...XX..." , // 18

  "W" /* UTF-8 57 - Glyph 56 */

  "\n"   ".XXXX..."   // 78
  "\n"   "X......."   // 80
  "\n"   ".XX....."   // 60
  "\n"   "X......."   // 80
  "\n"   ".XXXX..." , // 78

  "X" /* UTF-8 58 - Glyph 57 */

  "\n"   "X...X..."   // 88
  "\n"   ".X.X...."   // 50
  "\n"   "..X....."   // 20
  "\n"   ".X.X...."   // 50
  "\n"   "X...X..." , // 88

  "Y" /* UTF-8 59 - Glyph 58 */

  "\n"   "...XX..."   // 18
  "\n"   "..X....."   // 20
  "\n"   "XX......"   // C0
  "\n"   "..X....."   // 20
  "\n"   "...XX..." , // 18

  "Z" /* UTF-8 5A - Glyph 59 */

  "\n"   "X...X..."   // 88
  "\n"   "XX..X..."   // C8
  "\n"   "X.X.X..."   // A8
  "\n"   "X..XX..."   // 98
  "\n"   "X...X..." , // 88

  "[" /* UTF-8 5B - Glyph 60 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..." , // 88

  "\\" /* UTF-8 5C - Glyph 61 */

  "\n"   "...XX..."   // 18
  "\n"   "..X....."   // 20
  "\n"   "XX......" , // C0

  "]" /* UTF-8 5D - Glyph 62 */

  "\n"   "X...X..."   // 88
  "\n"   "XXXXX..." , // F8

  "^" /* UTF-8 5E - Glyph 63 */

  "\n"   "........"   // 00
  "\n"   "......X."   // 02
  "\n"   ".......X"   // 01
  "\n"   "......X." , // 02

  "_" /* UTF-8 5F - Glyph 64 */

  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X......." , // 80

  "`" /* UTF-8 60 - Glyph 65 */

  "\n"   ".......X"   // 01
  "\n"   "......X." , // 02

  "a" /* UTF-8 61 - Glyph 66 */

  "\n"   "XXXXX..."   // F8
  "\n"   ".X..X..."   // 48
  "\n"   ".X..X..."   // 48
  "\n"   ".X..X..."   // 48
  "\n"   "XXXXX..." , // F8

  "b" /* UTF-8 62 - Glyph 67 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "XX.XX..." , // D8

  "c" /* UTF-8 63 - Glyph 68 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X...X..." , // 88

  "d" /* UTF-8 64 - Glyph 69 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   ".XXX...." , // 70

  "e" /* UTF-8 65 - Glyph 70 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X...X..." , // 88

  "f" /* UTF-8 66 - Glyph 71 */

  "\n"   "XXXXX..."   // F8
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "....X..." , // 08

  "g" /* UTF-8 67 - Glyph 72 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X.X.X..."   // A8
  "\n"   "XXX.X..." , // E8

  "h" /* UTF-8 68 - Glyph 73 */

  "\n"   "XXXXX..."   // F8
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "XXXXX..." , // F8

  "i" /* UTF-8 69 - Glyph 74 */

  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..."   // 88
  "\n"   "X...X..." , // 88

  "j" /* UTF-8 6A - Glyph 75 */

  "\n"   "XX......"   // C0
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X...X..."   // 88
  "\n"   "XXXXX..." , // F8

  "k" /* UTF-8 6B - Glyph 76 */

  "\n"   "XXXXX..."   // F8
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   ".X.X...."   // 50
  "\n"   "X...X..." , // 88

  "l" /* UTF-8 6C - Glyph 77 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X......." , // 80

  "m" /* UTF-8 6D - Glyph 78 */

  "\n"   "XXXXX..."   // F8
  "\n"   "...X...."   // 10
  "\n"   "..X....."   // 20
  "\n"   "...X...."   // 10
  "\n"   "XXXXX..." , // F8

  "n" /* UTF-8 6E - Glyph 79 */

  "\n"   "XXXXX..."   // F8
  "\n"   "...X...."   // 10
  "\n"   "..X....."   // 20
  "\n"   ".X......"   // 40
  "\n"   "XXXXX..." , // F8

  "o" /* UTF-8 6F - Glyph 80 */

  "\n"   ".XXX...."   // 70
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   ".XXX...." , // 70

  "p" /* UTF-8 70 - Glyph 81 */

  "\n"   "XXXXX..."   // F8
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "...X...." , // 10

  "q" /* UTF-8 71 - Glyph 82 */

  "\n"   ".XXXX..."   // 78
  "\n"   ".X..X..."   // 48
  "\n"   "XX..X..."   // C8
  "\n"   ".X..X..."   // 48
  "\n"   ".XXXX..." , // 78

  "r" /* UTF-8 72 - Glyph 83 */

  "\n"   "XXXXX..."   // F8
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "..X.X..."   // 28
  "\n"   "XX.X...." , // D0

  "s" /* UTF-8 73 - Glyph 84 */

  "\n"   "X.XXX..."   // B8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X..."   // A8
  "\n"   "XXX.X..." , // E8

  "t" /* UTF-8 74 - Glyph 85 */

  "\n"   "....X..."   // 08
  "\n"   "....X..."   // 08
  "\n"   "XXXXX..."   // F8
  "\n"   "....X..."   // 08
  "\n"   "....X..." , // 08

  "u" /* UTF-8 75 - Glyph 86 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "X......."   // 80
  "\n"   "XXXXX..." , // F8

  "v" /* UTF-8 76 - Glyph 87 */

  "\n"   "...XX..."   // 18
  "\n"   ".XX....."   // 60
  "\n"   "X......."   // 80
  "\n"   ".XX....."   // 60
  "\n"   "...XX..." , // 18

  "w" /* UTF-8 77 - Glyph 88 */

  "\n"   ".XXXX..."   // 78
  "\n"   "X......."   // 80
  "\n"   ".XX....."   // 60
  "\n"   "X......."   // 80
  "\n"   ".XXXX..." , // 78

  "x" /* UTF-8 78 - Glyph 89 */

  "\n"   "X...X..."   // 88
  "\n"   ".X.X...."   // 50
  "\n"   "..X....."   // 20
  "\n"   ".X.X...."   // 50
  "\n"   "X...X..." , // 88

  "y" /* UTF-8 79 - Glyph 90 */

  "\n"   "...XX..."   // 18
  "\n"   "..X....."   // 20
  "\n"   "XX......"   // C0
  "\n"   "..X....."   // 20
  "\n"   "...XX..." , // 18

  "z" /* UTF-8 7A - Glyph 91 */

  "\n"   "X...X..."   // 88
  "\n"   "XX..X..."   // C8
  "\n"   "X.X.X..."   // A8
  "\n"   "X..XX..."   // 98
  "\n"   "X...X..." , // 88

  "{" /* UTF-8 7B - Glyph 92 */

  "\n"   "..X....."   // 20
  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..." , // 88

  "|" /* UTF-8 7C - Glyph 93 */

  "\n"   "XX.XX..." , // D8

  "}" /* UTF-8 7D - Glyph 94 */

  "\n"   "X...X..."   // 88
  "\n"   "XXXXX..."   // F8
  "\n"   "..X....." , // 20

  "~" /* UTF-8 7E - Glyph 95 */

  "\n"   ".....X.."   // 04
  "\n"   "......X."   // 02
  "\n"   ".....X.."   // 04
  "\n"   "......X." , // 02

  "À" /* UTF-8 C3 80 - Glyph 96 */

  "\n"   "XXXXX..."   // F8
  "\n"   ".X..X..X"   // 49
  "\n"   ".X..X.X."   // 4A
  "\n"   ".X..X..."   // 48
  "\n"   "XXXXX..." , // F8

  "Á" /* UTF-8 C3 81 - Glyph 97 */

  "\n"   "XXXXX..."   // F8
  "\n"   ".X..X..."   // 48
  "\n"   ".X..X.X."   // 4A
  "\n"   ".X..X..X"   // 49
  "\n"   "XXXXX..." , // F8

  "Â" /* UTF-8 C3 82 - Glyph 98 */

  "\n"   "XXXXX..."   // F8
  "\n"   ".X..X.X."   // 4A
  "\n"   ".X..X..X"   // 49
  "\n"   ".X..X.X."   // 4A
  "\n"   "XXXXX..." , // F8

  "Ä" /* UTF-8 C3 84 - Glyph 99 */

  "\n"   "XXXXX..."   // F8
  "\n"   ".X..X.X."   // 4A
  "\n"   ".X..X..."   // 48
  "\n"   ".X..X.X."   // 4A
  "\n"   "XXXXX..." , // F8

  "È" /* UTF-8 C3 88 - Glyph 100 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X..X"   // A9
  "\n"   "X.X.X.X."   // AA
  "\n"   "X.X.X..."   // A8
  "\n"   "X...X..." , // 88

  "É" /* UTF-8 C3 89 - Glyph 101 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X.X."   // AA
  "\n"   "X.X.X..X"   // A9
  "\n"   "X...X..." , // 88

  "Ê" /* UTF-8 C3 8A - Glyph 102 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X.X."   // AA
  "\n"   "X.X.X..X"   // A9
  "\n"   "X.X.X.X."   // AA
  "\n"   "X...X..." , // 88

  "Ö" /* UTF-8 C3 96 - Glyph 103 */

  "\n"   ".XXX...."   // 70
  "\n"   "X...X.X."   // 8A
  "\n"   "X...X..."   // 88
  "\n"   "X...X.X."   // 8A
  "\n"   ".XXX...." , // 70

  "Ü" /* UTF-8 C3 9C - Glyph 104 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.....X."   // 82
  "\n"   "X......."   // 80
  "\n"   "X.....X."   // 82
  "\n"   "XXXXX..." , // F8

  "à" /* UTF-8 C3 A0 - Glyph 105 */

  "\n"   "XXXXX..."   // F8
  "\n"   ".X..X..X"   // 49
  "\n"   ".X..X.X."   // 4A
  "\n"   ".X..X..."   // 48
  "\n"   "XXXXX..." , // F8

  "á" /* UTF-8 C3 A1 - Glyph 106 */

  "\n"   "XXXXX..."   // F8
  "\n"   ".X..X..."   // 48
  "\n"   ".X..X.X."   // 4A
  "\n"   ".X..X..X"   // 49
  "\n"   "XXXXX..." , // F8

  "â" /* UTF-8 C3 A2 - Glyph 107 */

  "\n"   "XXXXX..."   // F8
  "\n"   ".X..X.X."   // 4A
  "\n"   ".X..X..X"   // 49
  "\n"   ".X..X.X."   // 4A
  "\n"   "XXXXX..." , // F8

  "ä" /* UTF-8 C3 A4 - Glyph 108 */

  "\n"   "XXXXX..."   // F8
  "\n"   ".X..X.X."   // 4A
  "\n"   ".X..X..."   // 48
  "\n"   ".X..X.X."   // 4A
  "\n"   "XXXXX..." , // F8

  "ç" /* UTF-8 C3 A7 - Glyph 109 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "X...X..." , // 88

  "è" /* UTF-8 C3 A8 - Glyph 110 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X..X"   // A9
  "\n"   "X.X.X.X."   // AA
  "\n"   "X.X.X..."   // A8
  "\n"   "X...X..." , // 88

  "é" /* UTF-8 C3 A9 - Glyph 111 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X.X."   // AA
  "\n"   "X.X.X..X"   // A9
  "\n"   "X...X..." , // 88

  "ê" /* UTF-8 C3 AA - Glyph 112 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X.X."   // AA
  "\n"   "X.X.X..X"   // A9
  "\n"   "X.X.X.X."   // AA
  "\n"   "X...X..." , // 88

  "ë" /* UTF-8 C3 AB - Glyph 113 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.X.X.X."   // AA
  "\n"   "X.X.X..."   // A8
  "\n"   "X.X.X.X."   // AA
  "\n"   "X...X..." , // 88

  "ì" /* UTF-8 C3 AC - Glyph 114 */

  "\n"   "X...X..."   // 88
  "\n"   "X...X..X"   // 89
  "\n"   "XXXXX.X."   // FA
  "\n"   "X...X..."   // 88
  "\n"   "X...X..." , // 88

  "í" /* UTF-8 C3 AD - Glyph 115 */

  "\n"   "X...X..."   // 88
  "\n"   "X...X..."   // 88
  "\n"   "XXXXX.X."   // FA
  "\n"   "X...X..X"   // 89
  "\n"   "X...X..." , // 88

  "î" /* UTF-8 C3 AE - Glyph 116 */

  "\n"   "X...X..."   // 88
  "\n"   "X...X.X."   // 8A
  "\n"   "XXXXX..X"   // F9
  "\n"   "X...X.X."   // 8A
  "\n"   "X...X..." , // 88

  "ï" /* UTF-8 C3 AF - Glyph 117 */

  "\n"   "X...X..."   // 88
  "\n"   "X...X.X."   // 8A
  "\n"   "XXXXX..."   // F8
  "\n"   "X...X.X."   // 8A
  "\n"   "X...X..." , // 88

  "ö" /* UTF-8 C3 B6 - Glyph 118 */

  "\n"   ".XXX...."   // 70
  "\n"   "X...X.X."   // 8A
  "\n"   "X...X..."   // 88
  "\n"   "X...X.X."   // 8A
  "\n"   ".XXX...." , // 70

  "ü" /* UTF-8 C3 BC - Glyph 119 */

  "\n"   "XXXXX..."   // F8
  "\n"   "X.....X."   // 82
  "\n"   "X......."   // 80
  "\n"   "X.....X."   // 82
  "\n"   "XXXXX..." , // F8

  "–" /* UTF-8 E2 80 93 - Glyph 120 */

  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....."   // 20
  "\n"   "..X....." , // 20

  "’" /* UTF-8 E2 80 99 - Glyph 121 */

  "\n"   "....XX.." , // 0C

  "•" /* UTF-8 E2 80 A2 - Glyph 122 */

  "\n"   "........"   // 00
  "\n"   "........"   // 00
  "\n"   "..XX...."   // 30
  "\n"   "..XX...." , // 30

  nullptr // terminator
};

// MARK: - end of generated font verification data


#endif // GENERATE_FONT_SOURCE


// MARK: - '5x5' generated font data

static const glyph_t font_5x5_glyphs[] = {
  {  4, "\xff\x81\x81\xff"                         },  // placeholder          (input # 0 -> glyph # 0)
  {  4, "\x00\x00\x00\x00"                         },  // ' ' UTF-8 20         (input # 1 -> glyph # 1)
  {  1, "\xb8"                                     },  // '!' UTF-8 21         (input # 2 -> glyph # 2)
  {  3, "\x0c\x00\x0c"                             },  // '"' UTF-8 22         (input # 3 -> glyph # 3)
  {  5, "\x50\xf8\x50\xf8\x50"                     },  // '#' UTF-8 23         (input # 4 -> glyph # 4)
  {  5, "\xb8\xa8\xfc\xa8\xe8"                     },  // '$' UTF-8 24         (input # 5 -> glyph # 5)
  {  5, "\x88\x40\x20\x10\x88"                     },  // '%' UTF-8 25         (input # 6 -> glyph # 6)
  {  5, "\x50\xa8\xa8\x40\xa0"                     },  // '&' UTF-8 26         (input # 7 -> glyph # 7)
  {  1, "\x0c"                                     },  // ''' UTF-8 27         (input # 8 -> glyph # 8)
  {  2, "\x70\x88"                                 },  // '(' UTF-8 28         (input # 9 -> glyph # 9)
  {  2, "\x88\x70"                                 },  // ')' UTF-8 29         (input # 10 -> glyph # 10)
  {  3, "\x04\x0e\x04"                             },  // '*' UTF-8 2A         (input # 11 -> glyph # 11)
  {  5, "\x20\x20\xf8\x20\x20"                     },  // '+' UTF-8 2B         (input # 12 -> glyph # 12)
  {  1, "\x80"                                     },  // ',' UTF-8 2C         (input # 13 -> glyph # 13)
  {  5, "\x20\x20\x20\x20\x20"                     },  // '-' UTF-8 2D         (input # 14 -> glyph # 14)
  {  1, "\x80"                                     },  // '.' UTF-8 2E         (input # 15 -> glyph # 15)
  {  3, "\xc0\x20\x18"                             },  // '/' UTF-8 2F         (input # 16 -> glyph # 16)
  {  5, "\xf8\xc8\xa8\x98\xf8"                     },  // '0' UTF-8 30         (input # 17 -> glyph # 17)
  {  3, "\x90\xf8\x80"                             },  // '1' UTF-8 31         (input # 18 -> glyph # 18)
  {  5, "\xc8\xa8\xa8\xa8\x90"                     },  // '2' UTF-8 32         (input # 19 -> glyph # 19)
  {  5, "\x88\xa8\xa8\xa8\xd8"                     },  // '3' UTF-8 33         (input # 20 -> glyph # 20)
  {  5, "\x78\x40\xe0\x40\x40"                     },  // '4' UTF-8 34         (input # 21 -> glyph # 21)
  {  5, "\xb8\xa8\xa8\xa8\x48"                     },  // '5' UTF-8 35         (input # 22 -> glyph # 22)
  {  5, "\xf8\xa8\xa8\xa8\xe8"                     },  // '6' UTF-8 36         (input # 23 -> glyph # 23)
  {  5, "\x08\x08\xc8\x28\x18"                     },  // '7' UTF-8 37         (input # 24 -> glyph # 24)
  {  5, "\xf8\xa8\xa8\xa8\xf8"                     },  // '8' UTF-8 38         (input # 25 -> glyph # 25)
  {  5, "\xb8\xa8\xa8\xa8\xf8"                     },  // '9' UTF-8 39         (input # 26 -> glyph # 26)
  {  1, "\x88"                                     },  // ':' UTF-8 3A         (input # 27 -> glyph # 27)
  {  1, "\x88"                                     },  // ';' UTF-8 3B         (input # 28 -> glyph # 28)
  {  3, "\x20\x50\x88"                             },  // '<' UTF-8 3C         (input # 29 -> glyph # 29)
  {  5, "\x50\x50\x50\x50\x50"                     },  // '=' UTF-8 3D         (input # 30 -> glyph # 30)
  {  3, "\x88\x50\x20"                             },  // '>' UTF-8 3E         (input # 31 -> glyph # 31)
  {  4, "\x10\x08\xa8\x10"                         },  // '?' UTF-8 3F         (input # 32 -> glyph # 32)
  {  5, "\xf8\x88\xa8\xa8\xb8"                     },  // '@' UTF-8 40         (input # 33 -> glyph # 33)
  {  5, "\xf8\x48\x48\x48\xf8"                     },  // 'A' UTF-8 41         (input # 34 -> glyph # 34)
  {  5, "\xf8\xa8\xa8\xa8\xd8"                     },  // 'B' UTF-8 42         (input # 35 -> glyph # 35)
  {  5, "\xf8\x88\x88\x88\x88"                     },  // 'C' UTF-8 43         (input # 36 -> glyph # 36)
  {  5, "\xf8\x88\x88\x88\x70"                     },  // 'D' UTF-8 44         (input # 37 -> glyph # 37)
  {  5, "\xf8\xa8\xa8\xa8\x88"                     },  // 'E' UTF-8 45         (input # 38 -> glyph # 38)
  {  5, "\xf8\x28\x28\x28\x08"                     },  // 'F' UTF-8 46         (input # 39 -> glyph # 39)
  {  5, "\xf8\x88\x88\xa8\xe8"                     },  // 'G' UTF-8 47         (input # 40 -> glyph # 40)
  {  5, "\xf8\x20\x20\x20\xf8"                     },  // 'H' UTF-8 48         (input # 41 -> glyph # 41)
  {  5, "\x88\x88\xf8\x88\x88"                     },  // 'I' UTF-8 49         (input # 42 -> glyph # 42)
  {  5, "\xc0\x80\x80\x88\xf8"                     },  // 'J' UTF-8 4A         (input # 43 -> glyph # 43)
  {  5, "\xf8\x20\x20\x50\x88"                     },  // 'K' UTF-8 4B         (input # 44 -> glyph # 44)
  {  5, "\xf8\x80\x80\x80\x80"                     },  // 'L' UTF-8 4C         (input # 45 -> glyph # 45)
  {  5, "\xf8\x10\x20\x10\xf8"                     },  // 'M' UTF-8 4D         (input # 46 -> glyph # 46)
  {  5, "\xf8\x10\x20\x40\xf8"                     },  // 'N' UTF-8 4E         (input # 47 -> glyph # 47)
  {  5, "\x70\x88\x88\x88\x70"                     },  // 'O' UTF-8 4F         (input # 48 -> glyph # 48)
  {  5, "\xf8\x28\x28\x28\x10"                     },  // 'P' UTF-8 50         (input # 49 -> glyph # 49)
  {  5, "\x78\x48\xc8\x48\x78"                     },  // 'Q' UTF-8 51         (input # 50 -> glyph # 50)
  {  5, "\xf8\x28\x28\x28\xd0"                     },  // 'R' UTF-8 52         (input # 51 -> glyph # 51)
  {  5, "\xb8\xa8\xa8\xa8\xe8"                     },  // 'S' UTF-8 53         (input # 52 -> glyph # 52)
  {  5, "\x08\x08\xf8\x08\x08"                     },  // 'T' UTF-8 54         (input # 53 -> glyph # 53)
  {  5, "\xf8\x80\x80\x80\xf8"                     },  // 'U' UTF-8 55         (input # 54 -> glyph # 54)
  {  5, "\x18\x60\x80\x60\x18"                     },  // 'V' UTF-8 56         (input # 55 -> glyph # 55)
  {  5, "\x78\x80\x60\x80\x78"                     },  // 'W' UTF-8 57         (input # 56 -> glyph # 56)
  {  5, "\x88\x50\x20\x50\x88"                     },  // 'X' UTF-8 58         (input # 57 -> glyph # 57)
  {  5, "\x18\x20\xc0\x20\x18"                     },  // 'Y' UTF-8 59         (input # 58 -> glyph # 58)
  {  5, "\x88\xc8\xa8\x98\x88"                     },  // 'Z' UTF-8 5A         (input # 59 -> glyph # 59)
  {  2, "\xf8\x88"                                 },  // '[' UTF-8 5B         (input # 60 -> glyph # 60)
  {  3, "\x18\x20\xc0"                             },  // '\' UTF-8 5C         (input # 61 -> glyph # 61)
  {  2, "\x88\xf8"                                 },  // ']' UTF-8 5D         (input # 62 -> glyph # 62)
  {  4, "\x00\x02\x01\x02"                         },  // '^' UTF-8 5E         (input # 63 -> glyph # 63)
  {  6, "\x80\x80\x80\x80\x80\x80"                 },  // '_' UTF-8 5F         (input # 64 -> glyph # 64)
  {  2, "\x01\x02"                                 },  // '`' UTF-8 60         (input # 65 -> glyph # 65)
  {  5, "\xf8\x48\x48\x48\xf8"                     },  // 'a' UTF-8 61         (input # 66 -> glyph # 66)
  {  5, "\xf8\xa8\xa8\xa8\xd8"                     },  // 'b' UTF-8 62         (input # 67 -> glyph # 67)
  {  5, "\xf8\x88\x88\x88\x88"                     },  // 'c' UTF-8 63         (input # 68 -> glyph # 68)
  {  5, "\xf8\x88\x88\x88\x70"                     },  // 'd' UTF-8 64         (input # 69 -> glyph # 69)
  {  5, "\xf8\xa8\xa8\xa8\x88"                     },  // 'e' UTF-8 65         (input # 70 -> glyph # 70)
  {  5, "\xf8\x28\x28\x28\x08"                     },  // 'f' UTF-8 66         (input # 71 -> glyph # 71)
  {  5, "\xf8\x88\x88\xa8\xe8"                     },  // 'g' UTF-8 67         (input # 72 -> glyph # 72)
  {  5, "\xf8\x20\x20\x20\xf8"                     },  // 'h' UTF-8 68         (input # 73 -> glyph # 73)
  {  5, "\x88\x88\xf8\x88\x88"                     },  // 'i' UTF-8 69         (input # 74 -> glyph # 74)
  {  5, "\xc0\x80\x80\x88\xf8"                     },  // 'j' UTF-8 6A         (input # 75 -> glyph # 75)
  {  5, "\xf8\x20\x20\x50\x88"                     },  // 'k' UTF-8 6B         (input # 76 -> glyph # 76)
  {  5, "\xf8\x80\x80\x80\x80"                     },  // 'l' UTF-8 6C         (input # 77 -> glyph # 77)
  {  5, "\xf8\x10\x20\x10\xf8"                     },  // 'm' UTF-8 6D         (input # 78 -> glyph # 78)
  {  5, "\xf8\x10\x20\x40\xf8"                     },  // 'n' UTF-8 6E         (input # 79 -> glyph # 79)
  {  5, "\x70\x88\x88\x88\x70"                     },  // 'o' UTF-8 6F         (input # 80 -> glyph # 80)
  {  5, "\xf8\x28\x28\x28\x10"                     },  // 'p' UTF-8 70         (input # 81 -> glyph # 81)
  {  5, "\x78\x48\xc8\x48\x78"                     },  // 'q' UTF-8 71         (input # 82 -> glyph # 82)
  {  5, "\xf8\x28\x28\x28\xd0"                     },  // 'r' UTF-8 72         (input # 83 -> glyph # 83)
  {  5, "\xb8\xa8\xa8\xa8\xe8"                     },  // 's' UTF-8 73         (input # 84 -> glyph # 84)
  {  5, "\x08\x08\xf8\x08\x08"                     },  // 't' UTF-8 74         (input # 85 -> glyph # 85)
  {  5, "\xf8\x80\x80\x80\xf8"                     },  // 'u' UTF-8 75         (input # 86 -> glyph # 86)
  {  5, "\x18\x60\x80\x60\x18"                     },  // 'v' UTF-8 76         (input # 87 -> glyph # 87)
  {  5, "\x78\x80\x60\x80\x78"                     },  // 'w' UTF-8 77         (input # 88 -> glyph # 88)
  {  5, "\x88\x50\x20\x50\x88"                     },  // 'x' UTF-8 78         (input # 89 -> glyph # 89)
  {  5, "\x18\x20\xc0\x20\x18"                     },  // 'y' UTF-8 79         (input # 90 -> glyph # 90)
  {  5, "\x88\xc8\xa8\x98\x88"                     },  // 'z' UTF-8 7A         (input # 91 -> glyph # 91)
  {  3, "\x20\xf8\x88"                             },  // '{' UTF-8 7B         (input # 92 -> glyph # 92)
  {  1, "\xd8"                                     },  // '|' UTF-8 7C         (input # 93 -> glyph # 93)
  {  3, "\x88\xf8\x20"                             },  // '}' UTF-8 7D         (input # 94 -> glyph # 94)
  {  4, "\x04\x02\x04\x02"                         },  // '~' UTF-8 7E         (input # 95 -> glyph # 95)
  {  5, "\xf8\x49\x4a\x48\xf8"                     },  // 'À' UTF-8 C3 80     (input # 96 -> glyph # 96)
  {  5, "\xf8\x48\x4a\x49\xf8"                     },  // 'Á' UTF-8 C3 81     (input # 97 -> glyph # 97)
  {  5, "\xf8\x4a\x49\x4a\xf8"                     },  // 'Â' UTF-8 C3 82     (input # 98 -> glyph # 98)
  {  5, "\xf8\x4a\x48\x4a\xf8"                     },  // 'Ä' UTF-8 C3 84     (input # 99 -> glyph # 99)
  {  5, "\xf8\xa9\xaa\xa8\x88"                     },  // 'È' UTF-8 C3 88     (input # 100 -> glyph # 100)
  {  5, "\xf8\xa8\xaa\xa9\x88"                     },  // 'É' UTF-8 C3 89     (input # 101 -> glyph # 101)
  {  5, "\xf8\xaa\xa9\xaa\x88"                     },  // 'Ê' UTF-8 C3 8A     (input # 102 -> glyph # 102)
  {  5, "\x70\x8a\x88\x8a\x70"                     },  // 'Ö' UTF-8 C3 96     (input # 103 -> glyph # 103)
  {  5, "\xf8\x82\x80\x82\xf8"                     },  // 'Ü' UTF-8 C3 9C     (input # 104 -> glyph # 104)
  {  5, "\xf8\x49\x4a\x48\xf8"                     },  // 'à' UTF-8 C3 A0     (input # 105 -> glyph # 105)
  {  5, "\xf8\x48\x4a\x49\xf8"                     },  // 'á' UTF-8 C3 A1     (input # 106 -> glyph # 106)
  {  5, "\xf8\x4a\x49\x4a\xf8"                     },  // 'â' UTF-8 C3 A2     (input # 107 -> glyph # 107)
  {  5, "\xf8\x4a\x48\x4a\xf8"                     },  // 'ä' UTF-8 C3 A4     (input # 108 -> glyph # 108)
  {  5, "\xf8\x88\x88\x88\x88"                     },  // 'ç' UTF-8 C3 A7     (input # 109 -> glyph # 109)
  {  5, "\xf8\xa9\xaa\xa8\x88"                     },  // 'è' UTF-8 C3 A8     (input # 110 -> glyph # 110)
  {  5, "\xf8\xa8\xaa\xa9\x88"                     },  // 'é' UTF-8 C3 A9     (input # 111 -> glyph # 111)
  {  5, "\xf8\xaa\xa9\xaa\x88"                     },  // 'ê' UTF-8 C3 AA     (input # 112 -> glyph # 112)
  {  5, "\xf8\xaa\xa8\xaa\x88"                     },  // 'ë' UTF-8 C3 AB     (input # 113 -> glyph # 113)
  {  5, "\x88\x89\xfa\x88\x88"                     },  // 'ì' UTF-8 C3 AC     (input # 114 -> glyph # 114)
  {  5, "\x88\x88\xfa\x89\x88"                     },  // 'í' UTF-8 C3 AD     (input # 115 -> glyph # 115)
  {  5, "\x88\x8a\xf9\x8a\x88"                     },  // 'î' UTF-8 C3 AE     (input # 116 -> glyph # 116)
  {  5, "\x88\x8a\xf8\x8a\x88"                     },  // 'ï' UTF-8 C3 AF     (input # 117 -> glyph # 117)
  {  5, "\x70\x8a\x88\x8a\x70"                     },  // 'ö' UTF-8 C3 B6     (input # 118 -> glyph # 118)
  {  5, "\xf8\x82\x80\x82\xf8"                     },  // 'ü' UTF-8 C3 BC     (input # 119 -> glyph # 119)
  {  7, "\x20\x20\x20\x20\x20\x20\x20"             },  // '–' UTF-8 E2 80 93 (input # 120 -> glyph # 120)
  {  1, "\x0c"                                     },  // '’' UTF-8 E2 80 99 (input # 121 -> glyph # 121)
  {  4, "\x00\x00\x30\x30"                         },  // '•' UTF-8 E2 80 A2 (input # 122 -> glyph # 122)
};

static const GlyphRange font_5x5_ranges[] = {
  { "", 0x20, 0x7E, 1 }, //  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
  { "\xc3", 0x80, 0x82, 96 }, // ÀÁÂ
  { "\xc3", 0x84, 0x84, 99 }, // Ä
  { "\xc3", 0x88, 0x8A, 100 }, // ÈÉÊ
  { "\xc3", 0x96, 0x96, 103 }, // Ö
  { "\xc3", 0x9C, 0x9C, 104 }, // Ü
  { "\xc3", 0xA0, 0xA2, 105 }, // àáâ
  { "\xc3", 0xA4, 0xA4, 108 }, // ä
  { "\xc3", 0xA7, 0xAF, 109 }, // çèéêëìíîï
  { "\xc3", 0xB6, 0xB6, 118 }, // ö
  { "\xc3", 0xBC, 0xBC, 119 }, // ü
  { "\xe2\x80", 0x93, 0x93, 120 }, // –
  { "\xe2\x80", 0x99, 0x99, 121 }, // ’
  { "\xe2\x80", 0xA2, 0xA2, 122 }, // •
  { NULL, 0, 0, 0 }
};

static const font_t font_5x5 = {
  .fontName = "5x5",
  .glyphHeight = 8,
  .numGlyphs = 123,
  .glyphRanges = font_5x5_ranges,
  .glyphs = font_5x5_glyphs,
   #ifdef GENERATE_FONT_SOURCE
   .copyright = font_5x5_copyright,
   .glyphstrings = font_5x5_glyphstrings
   #else
   .copyright = nullptr
   #endif
};

static BuiltinFontRegistrar r(font_5x5);

// MARK: - end of generated font data

