//  SPDX-License-Identifier: GPL-3.0-or-later
//
//  Autogenerated by p44lrgraphics font generator
//
//  You should have received a copy of the GNU General Public License
//  along with p44lrgraphics. If not, see <http://www.gnu.org/licenses/>.
//
// Original font is (c) by Daniel Linssen - No embedding restrictions

// Include this file into a p44lrgraphics build to define a built-in font

#include "fonts.hpp"

using namespace p44;

#ifdef GENERATE_FONT_SOURCE

// MARK: - 'm6x11' generated font verification data

static const char * font_m6x11_glyphstrings[] = {
  "placeholder" /* 0x00 - Glyph 0 */

  "\n"   "XXXXXXXXXXXXXX"   // 3F FF
  "\n"   "X............X"   // 20 01
  "\n"   "X............X"   // 20 01
  "\n"   "X............X"   // 20 01
  "\n"   "XXXXXXXXXXXXXX" , // 3F FF

  " " /* UTF-8 20 - Glyph 1 */

  "\n"   ".............."   // 00 00
  "\n"   ".............."   // 00 00
  "\n"   ".............."   // 00 00
  "\n"   ".............."   // 00 00
  "\n"   ".............." , // 00 00

  "!" /* UTF-8 21 - Glyph 2 */

  "\n"   "...XX.XXXXXXXX"   // 06 FF
  "\n"   "...XX.XXXXXXXX" , // 06 FF

  "\"" /* UTF-8 22 - Glyph 3 */

  "\n"   "............XX"   // 00 03
  "\n"   "...........XXX"   // 00 07
  "\n"   ".............."   // 00 00
  "\n"   "............XX"   // 00 03
  "\n"   "...........XXX" , // 00 07

  "#" /* UTF-8 23 - Glyph 4 */

  "\n"   "......XX.XX..."   // 00 D8
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "......XX.XX..."   // 00 D8
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "......XX.XX..." , // 00 D8

  "$" /* UTF-8 24 - Glyph 5 */

  "\n"   "....XX..XXX..."   // 03 38
  "\n"   "....XX.XXXXX.."   // 03 7C
  "\n"   "..XXXX.XX.XXXX"   // 0F 6F
  "\n"   "..XXXX.XX.XXXX"   // 0F 6F
  "\n"   "....XXXXX.XX.."   // 03 EC
  "\n"   ".....XXX..XX.." , // 01 CC

  "%" /* UTF-8 25 - Glyph 6 */

  "\n"   ".....XX...XX.."   // 01 8C
  "\n"   ".....XXX..XX.."   // 01 CC
  "\n"   "......XXX....."   // 00 E0
  "\n"   ".......XXX...."   // 00 70
  "\n"   "....XX..XXX..."   // 03 38
  "\n"   "....XX...XX..." , // 03 18

  "&" /* UTF-8 26 - Glyph 7 */

  "\n"   "....XXXXX....."   // 03 E0
  "\n"   "...XXXXXXXXXX."   // 07 FE
  "\n"   "...XX...XXXXXX"   // 06 3F
  "\n"   "...XX..XXX..XX"   // 06 73
  "\n"   "...XXXXXXX..XX"   // 07 F3
  "\n"   "....XXXXXXXXXX"   // 03 FF
  "\n"   "...XXXXX.XXXX."   // 07 DE
  "\n"   "...XX.XXX....."   // 06 E0
  "\n"   "...XX..XX....." , // 06 60

  "'" /* UTF-8 27 - Glyph 8 */

  "\n"   "............XX"   // 00 03
  "\n"   "...........XXX" , // 00 07

  "(" /* UTF-8 28 - Glyph 9 */

  "\n"   "..XXXXXXXXXXX."   // 0F FE
  "\n"   ".XXXXXXXXXXXXX"   // 1F FF
  "\n"   ".XX.........XX"   // 18 03
  "\n"   ".XX.........XX" , // 18 03

  ")" /* UTF-8 29 - Glyph 10 */

  "\n"   ".XX.........XX"   // 18 03
  "\n"   ".XX.........XX"   // 18 03
  "\n"   ".XXXXXXXXXXXXX"   // 1F FF
  "\n"   "..XXXXXXXXXXX." , // 0F FE

  "*" /* UTF-8 2A - Glyph 11 */

  "\n"   ".........XX.XX"   // 00 1B
  "\n"   ".........XXXXX"   // 00 1F
  "\n"   "..........XXX."   // 00 0E
  "\n"   ".........XXXXX"   // 00 1F
  "\n"   ".........XX.XX" , // 00 1B

  "+" /* UTF-8 2B - Glyph 12 */

  "\n"   ".......XX....."   // 00 60
  "\n"   ".......XX....."   // 00 60
  "\n"   ".....XXXXXX..."   // 01 F8
  "\n"   ".....XXXXXX..."   // 01 F8
  "\n"   ".......XX....."   // 00 60
  "\n"   ".......XX....." , // 00 60

  "," /* UTF-8 2C - Glyph 13 */

  "\n"   "...XX........."   // 06 00
  "\n"   "..XXX........." , // 0E 00

  "-" /* UTF-8 2D - Glyph 14 */

  "\n"   ".......XX....."   // 00 60
  "\n"   ".......XX....."   // 00 60
  "\n"   ".......XX....."   // 00 60
  "\n"   ".......XX....."   // 00 60
  "\n"   ".......XX....."   // 00 60
  "\n"   ".......XX....." , // 00 60

  "." /* UTF-8 2E - Glyph 15 */

  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........." , // 06 00

  "/" /* UTF-8 2F - Glyph 16 */

  "\n"   "...XXX........"   // 07 00
  "\n"   "...XXXXX......"   // 07 C0
  "\n"   ".....XXXXX...."   // 01 F0
  "\n"   ".......XXXXX.."   // 00 7C
  "\n"   ".........XXXXX"   // 00 1F
  "\n"   "...........XXX" , // 00 07

  "0" /* UTF-8 30 - Glyph 17 */

  "\n"   "....XXXXXXXXX."   // 03 FE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "....XXXXXXXXX." , // 03 FE

  "1" /* UTF-8 31 - Glyph 18 */

  "\n"   "...XX......XX."   // 06 06
  "\n"   "...XX......XX."   // 06 06
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........." , // 06 00

  "2" /* UTF-8 32 - Glyph 19 */

  "\n"   "...XXX.....XX."   // 07 06
  "\n"   "...XXXX....XXX"   // 07 87
  "\n"   "...XXXXX....XX"   // 07 C3
  "\n"   "...XX.XXX...XX"   // 06 E3
  "\n"   "...XX..XXXXXXX"   // 06 7F
  "\n"   "...XX...XXXXX." , // 06 3E

  "3" /* UTF-8 33 - Glyph 20 */

  "\n"   "....XX.....XX."   // 03 06
  "\n"   "...XXX.....XXX"   // 07 07
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "....XXXXX.XXX." , // 03 EE

  "4" /* UTF-8 34 - Glyph 21 */

  "\n"   "........XXXXXX"   // 00 3F
  "\n"   ".......XXXXXXX"   // 00 7F
  "\n"   ".......XX....."   // 00 60
  "\n"   ".......XX....."   // 00 60
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX" , // 07 FF

  "5" /* UTF-8 35 - Glyph 22 */

  "\n"   "...XX...XXXXXX"   // 06 3F
  "\n"   "...XX...XXXXXX"   // 06 3F
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XXXXXXX..XX"   // 07 F3
  "\n"   "....XXXXX...XX" , // 03 E3

  "6" /* UTF-8 36 - Glyph 23 */

  "\n"   "....XXXXXXXXX."   // 03 FE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XXXXXXX.XXX"   // 07 F7
  "\n"   "....XXXXX..XX." , // 03 E6

  "7" /* UTF-8 37 - Glyph 24 */

  "\n"   "............XX"   // 00 03
  "\n"   "............XX"   // 00 03
  "\n"   "...XXXXX....XX"   // 07 C3
  "\n"   "...XXXXXXX..XX"   // 07 F3
  "\n"   ".......XXXXXXX"   // 00 7F
  "\n"   ".........XXXXX" , // 00 1F

  "8" /* UTF-8 38 - Glyph 25 */

  "\n"   "....XXXXX.XXX."   // 03 EE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "....XXXXX.XXX." , // 03 EE

  "9" /* UTF-8 39 - Glyph 26 */

  "\n"   "....XX..XXXXX."   // 03 3E
  "\n"   "...XXX.XXXXXXX"   // 07 7F
  "\n"   "...XX..XX...XX"   // 06 63
  "\n"   "...XX..XX...XX"   // 06 63
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "....XXXXXXXXX." , // 03 FE

  ":" /* UTF-8 3A - Glyph 27 */

  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..." , // 06 18

  ";" /* UTF-8 3B - Glyph 28 */

  "\n"   "...XX....XX..."   // 06 18
  "\n"   "..XXX....XX..." , // 0E 18

  "<" /* UTF-8 3C - Glyph 29 */

  "\n"   "......XX......"   // 00 C0
  "\n"   ".....XXXX....."   // 01 E0
  "\n"   "....XXXXXX...."   // 03 F0
  "\n"   "...XXX..XXX..."   // 07 38
  "\n"   "...XX....XX..." , // 06 18

  "=" /* UTF-8 3D - Glyph 30 */

  "\n"   ".....XX..XX..."   // 01 98
  "\n"   ".....XX..XX..."   // 01 98
  "\n"   ".....XX..XX..."   // 01 98
  "\n"   ".....XX..XX..."   // 01 98
  "\n"   ".....XX..XX..."   // 01 98
  "\n"   ".....XX..XX..." , // 01 98

  ">" /* UTF-8 3E - Glyph 31 */

  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XXX..XXX..."   // 07 38
  "\n"   "....XXXXXX...."   // 03 F0
  "\n"   ".....XXXX....."   // 01 E0
  "\n"   "......XX......" , // 00 C0

  "?" /* UTF-8 3F - Glyph 32 */

  "\n"   "...........XX."   // 00 06
  "\n"   "...........XXX"   // 00 07
  "\n"   "...XX.XXX...XX"   // 06 E3
  "\n"   "...XX.XXXX..XX"   // 06 F3
  "\n"   "........XXXXXX"   // 00 3F
  "\n"   ".........XXXX." , // 00 1E

  "@" /* UTF-8 40 - Glyph 33 */

  "\n"   ".....XXXXXXX.."   // 01 FC
  "\n"   "....XXXXXXXXX."   // 03 FE
  "\n"   "...XXX.....XXX"   // 07 07
  "\n"   "...XX..XXX..XX"   // 06 73
  "\n"   "...XX.XXXXX.XX"   // 06 FB
  "\n"   "...XX.XX.XX.XX"   // 06 DB
  "\n"   "...XX.XXXXXXXX"   // 06 FF
  "\n"   "...XX.XXXXXXX."   // 06 FE
  "\n"   "...XX..XXXXX.." , // 06 7C

  "A" /* UTF-8 41 - Glyph 34 */

  "\n"   "...XXXXXXXXXX."   // 07 FE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   ".......XX...XX"   // 00 63
  "\n"   ".......XX...XX"   // 00 63
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXX." , // 07 FE

  "B" /* UTF-8 42 - Glyph 35 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "....XXXX.XXXX." , // 03 DE

  "C" /* UTF-8 43 - Glyph 36 */

  "\n"   "....XXXXXXXXX."   // 03 FE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XX.......XX" , // 06 03

  "D" /* UTF-8 44 - Glyph 37 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "....XXXXXXXXX." , // 03 FE

  "E" /* UTF-8 45 - Glyph 38 */

  "\n"   "....XXXXXXXXX."   // 03 FE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XX.......XX" , // 06 03

  "F" /* UTF-8 46 - Glyph 39 */

  "\n"   "...XXXXXXXXXX."   // 07 FE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "........XX..XX"   // 00 33
  "\n"   "........XX..XX"   // 00 33
  "\n"   "........XX..XX"   // 00 33
  "\n"   "............XX" , // 00 03

  "G" /* UTF-8 47 - Glyph 40 */

  "\n"   "....XXXXXXXXX."   // 03 FE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XXXXXXX..XX"   // 07 F3
  "\n"   "....XXXXXX..XX" , // 03 F3

  "H" /* UTF-8 48 - Glyph 41 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "........XX...."   // 00 30
  "\n"   "........XX...."   // 00 30
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX" , // 07 FF

  "I" /* UTF-8 49 - Glyph 42 */

  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XX.......XX" , // 06 03

  "J" /* UTF-8 4A - Glyph 43 */

  "\n"   "....XX......XX"   // 03 03
  "\n"   "...XXX......XX"   // 07 03
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "....XXXXXXXXXX" , // 03 FF

  "K" /* UTF-8 4B - Glyph 44 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   ".......XXX...."   // 00 70
  "\n"   "......XXXXX..."   // 00 F8
  "\n"   "...XXXXX.XXXXX"   // 07 DF
  "\n"   "...XXXX...XXXX" , // 07 8F

  "L" /* UTF-8 4C - Glyph 45 */

  "\n"   "....XXXXXXXXXX"   // 03 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........." , // 06 00

  "M" /* UTF-8 4D - Glyph 46 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "............XX"   // 00 03
  "\n"   ".....XXXXXXXXX"   // 01 FF
  "\n"   ".....XXXXXXXXX"   // 01 FF
  "\n"   "............XX"   // 00 03
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXX." , // 07 FE

  "N" /* UTF-8 4E - Glyph 47 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "............XX"   // 00 03
  "\n"   "............XX"   // 00 03
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXX." , // 07 FE

  "O" /* UTF-8 4F - Glyph 48 */

  "\n"   "....XXXXXXXXX."   // 03 FE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "....XXXXXXXXX." , // 03 FE

  "P" /* UTF-8 50 - Glyph 49 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   ".......XX...XX"   // 00 63
  "\n"   ".......XX...XX"   // 00 63
  "\n"   ".......XXXXXXX"   // 00 7F
  "\n"   "........XXXXX." , // 00 3E

  "Q" /* UTF-8 51 - Glyph 50 */

  "\n"   "....XXXXXXXXX."   // 03 FE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX.......XX"   // 06 03
  "\n"   "...XXX......XX"   // 07 03
  "\n"   "....XXXXXXXXXX"   // 03 FF
  "\n"   "...XXXXXXXXXX."   // 07 FE
  "\n"   "...XX........." , // 06 00

  "R" /* UTF-8 52 - Glyph 51 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "........XX..XX"   // 00 33
  "\n"   ".......XXX..XX"   // 00 73
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXX.XXXX." , // 07 DE

  "S" /* UTF-8 53 - Glyph 52 */

  "\n"   "...XX....XXXX."   // 06 1E
  "\n"   "...XX...XXXXXX"   // 06 3F
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XX...XX..XX"   // 06 33
  "\n"   "...XXXXXXX..XX"   // 07 F3
  "\n"   "....XXXXX...XX" , // 03 E3

  "T" /* UTF-8 54 - Glyph 53 */

  "\n"   "............XX"   // 00 03
  "\n"   "............XX"   // 00 03
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "............XX"   // 00 03
  "\n"   "............XX" , // 00 03

  "U" /* UTF-8 55 - Glyph 54 */

  "\n"   "....XXXXXXXXXX"   // 03 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........."   // 06 00
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "....XXXXXXXXXX" , // 03 FF

  "V" /* UTF-8 56 - Glyph 55 */

  "\n"   ".....XXXXXXXXX"   // 01 FF
  "\n"   "....XXXXXXXXXX"   // 03 FF
  "\n"   "...XXX........"   // 07 00
  "\n"   "...XXX........"   // 07 00
  "\n"   "....XXXXXXXXXX"   // 03 FF
  "\n"   ".....XXXXXXXXX" , // 01 FF

  "W" /* UTF-8 57 - Glyph 56 */

  "\n"   "....XXXXXXXXXX"   // 03 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX........."   // 06 00
  "\n"   "...XXXXXXX...."   // 07 F0
  "\n"   "...XXXXXXX...."   // 07 F0
  "\n"   "...XX........."   // 06 00
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "....XXXXXXXXXX" , // 03 FF

  "X" /* UTF-8 58 - Glyph 57 */

  "\n"   "...XXXX...XXXX"   // 07 8F
  "\n"   "...XXXXX.XXXXX"   // 07 DF
  "\n"   "......XXXXX..."   // 00 F8
  "\n"   ".......XXX...."   // 00 70
  "\n"   "......XXXXX..."   // 00 F8
  "\n"   "...XXXXX.XXXXX"   // 07 DF
  "\n"   "...XXXX...XXXX" , // 07 8F

  "Y" /* UTF-8 59 - Glyph 58 */

  "\n"   ".........XXXXX"   // 00 1F
  "\n"   "........XXXXXX"   // 00 3F
  "\n"   "...XXXXXXX...."   // 07 F0
  "\n"   "...XXXXXXX...."   // 07 F0
  "\n"   "........XXXXXX"   // 00 3F
  "\n"   ".........XXXXX" , // 00 1F

  "Z" /* UTF-8 5A - Glyph 59 */

  "\n"   "...XXX......XX"   // 07 03
  "\n"   "...XXXXX....XX"   // 07 C3
  "\n"   "...XXXXXXX..XX"   // 07 F3
  "\n"   "...XX..XXXXXXX"   // 06 7F
  "\n"   "...XX....XXXXX"   // 06 1F
  "\n"   "...XX......XXX" , // 06 07

  "[" /* UTF-8 5B - Glyph 60 */

  "\n"   ".XXXXXXXXXXXXX"   // 1F FF
  "\n"   ".XXXXXXXXXXXXX"   // 1F FF
  "\n"   ".XX.........XX"   // 18 03
  "\n"   ".XX.........XX" , // 18 03

  "\\" /* UTF-8 5C - Glyph 61 */

  "\n"   "...........XXX"   // 00 07
  "\n"   ".........XXXXX"   // 00 1F
  "\n"   ".......XXXXX.."   // 00 7C
  "\n"   ".....XXXXX...."   // 01 F0
  "\n"   "...XXXXX......"   // 07 C0
  "\n"   "...XXX........" , // 07 00

  "]" /* UTF-8 5D - Glyph 62 */

  "\n"   ".XX.........XX"   // 18 03
  "\n"   ".XX.........XX"   // 18 03
  "\n"   ".XXXXXXXXXXXXX"   // 1F FF
  "\n"   ".XXXXXXXXXXXXX" , // 1F FF

  "^" /* UTF-8 5E - Glyph 63 */

  "\n"   "..........XX.."   // 00 0C
  "\n"   "..........XXX."   // 00 0E
  "\n"   "...........XXX"   // 00 07
  "\n"   "...........XXX"   // 00 07
  "\n"   "..........XXX."   // 00 0E
  "\n"   "..........XX.." , // 00 0C

  "_" /* UTF-8 5F - Glyph 64 */

  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........." , // 06 00

  "`" /* UTF-8 60 - Glyph 65 */

  "\n"   "............XX"   // 00 03
  "\n"   "...........XXX" , // 00 07

  "a" /* UTF-8 61 - Glyph 66 */

  "\n"   "....XXX..XX..."   // 03 98
  "\n"   "...XXXXX.XX..."   // 07 D8
  "\n"   "...XX.XX.XX..."   // 06 D8
  "\n"   "...XX.XX.XX..."   // 06 D8
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XXXXXXX...." , // 07 F0

  "b" /* UTF-8 62 - Glyph 67 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "....XXXXXX...." , // 03 F0

  "c" /* UTF-8 63 - Glyph 68 */

  "\n"   "....XXXXXX...."   // 03 F0
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..." , // 06 18

  "d" /* UTF-8 64 - Glyph 69 */

  "\n"   "....XXXXXX...."   // 03 F0
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX" , // 07 FF

  "e" /* UTF-8 65 - Glyph 70 */

  "\n"   "....XXXXXX...."   // 03 F0
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XX.XX.XX..."   // 06 D8
  "\n"   "...XX.XX.XX..."   // 06 D8
  "\n"   "...XX.XXXXX..."   // 06 F8
  "\n"   "...XX.XXXX...." , // 06 F0

  "f" /* UTF-8 66 - Glyph 71 */

  "\n"   ".........XX..."   // 00 18
  "\n"   "...XXXXXXXXXX."   // 07 FE
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   ".........XX.XX"   // 00 1B
  "\n"   ".........XX.XX"   // 00 1B
  "\n"   "............XX" , // 00 03

  "g" /* UTF-8 67 - Glyph 72 */

  "\n"   "XX..XXXXXX...."   // 33 F0
  "\n"   "XX.XXXXXXXX..."   // 37 F8
  "\n"   "XX.XX....XX..."   // 36 18
  "\n"   "XX.XX....XX..."   // 36 18
  "\n"   "XXXXXXXXXXX..."   // 3F F8
  "\n"   ".XXXXXXXXX...." , // 1F F0

  "h" /* UTF-8 68 - Glyph 73 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   ".........XX..."   // 00 18
  "\n"   ".........XX..."   // 00 18
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XXXXXXX...." , // 07 F0

  "i" /* UTF-8 69 - Glyph 74 */

  "\n"   "...XXXXXXXX.XX"   // 07 FB
  "\n"   "...XXXXXXXX.XX" , // 07 FB

  "j" /* UTF-8 6A - Glyph 75 */

  "\n"   "XX............"   // 30 00
  "\n"   "XX............"   // 30 00
  "\n"   "XXXXXXXXXXX.XX"   // 3F FB
  "\n"   ".XXXXXXXXXX.XX" , // 1F FB

  "k" /* UTF-8 6B - Glyph 76 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "......XX.XX..."   // 00 D8
  "\n"   ".....XXX.XX..."   // 01 D8
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XXX.XXX...." , // 07 70

  "l" /* UTF-8 6C - Glyph 77 */

  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XXXXXXXXXXX" , // 07 FF

  "m" /* UTF-8 6D - Glyph 78 */

  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   ".........XX..."   // 00 18
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   ".........XX..."   // 00 18
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XXXXXXX...." , // 07 F0

  "n" /* UTF-8 6E - Glyph 79 */

  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   ".........XX..."   // 00 18
  "\n"   ".........XX..."   // 00 18
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XXXXXXX...." , // 07 F0

  "o" /* UTF-8 6F - Glyph 80 */

  "\n"   "....XXXXXX...."   // 03 F0
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "....XXXXXX...." , // 03 F0

  "p" /* UTF-8 70 - Glyph 81 */

  "\n"   "XXXXXXXXXX...."   // 3F F0
  "\n"   "XXXXXXXXXXX..."   // 3F F8
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "....XXXXXX...." , // 03 F0

  "q" /* UTF-8 71 - Glyph 82 */

  "\n"   "....XXXXXX...."   // 03 F0
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "XXXXXXXXXXX..."   // 3F F8
  "\n"   "XXXXXXXXXX...." , // 3F F0

  "r" /* UTF-8 72 - Glyph 83 */

  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "........XX...."   // 00 30
  "\n"   ".........XX..."   // 00 18
  "\n"   ".........XX..."   // 00 18
  "\n"   ".........XX..." , // 00 18

  "s" /* UTF-8 73 - Glyph 84 */

  "\n"   "...XX..XXX...."   // 06 70
  "\n"   "...XX.XXXXX..."   // 06 F8
  "\n"   "...XX.XX.XX..."   // 06 D8
  "\n"   "...XX.XX.XX..."   // 06 D8
  "\n"   "...XXXXX.XX..."   // 07 D8
  "\n"   "....XXX..XX..." , // 03 98

  "t" /* UTF-8 74 - Glyph 85 */

  "\n"   ".........XX..."   // 00 18
  "\n"   "....XXXXXXXXXX"   // 03 FF
  "\n"   "...XXXXXXXXXXX"   // 07 FF
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XX....XX..." , // 06 18

  "u" /* UTF-8 75 - Glyph 86 */

  "\n"   "....XXXXXXX..."   // 03 F8
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XX........."   // 06 00
  "\n"   "...XX........."   // 06 00
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "....XXXXXXX..." , // 03 F8

  "v" /* UTF-8 76 - Glyph 87 */

  "\n"   ".....XXXXXX..."   // 01 F8
  "\n"   "....XXXXXXX..."   // 03 F8
  "\n"   "...XXX........"   // 07 00
  "\n"   "...XXX........"   // 07 00
  "\n"   "....XXXXXXX..."   // 03 F8
  "\n"   ".....XXXXXX..." , // 01 F8

  "w" /* UTF-8 77 - Glyph 88 */

  "\n"   "....XXXXXXX..."   // 03 F8
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "...XX........."   // 06 00
  "\n"   "...XXXXXXX...."   // 07 F0
  "\n"   "...XXXXXXX...."   // 07 F0
  "\n"   "...XX........."   // 06 00
  "\n"   "...XXXXXXXX..."   // 07 F8
  "\n"   "....XXXXXXX..." , // 03 F8

  "x" /* UTF-8 78 - Glyph 89 */

  "\n"   "...XX....XX..."   // 06 18
  "\n"   "...XXX..XXX..."   // 07 38
  "\n"   "....XXXXXX...."   // 03 F0
  "\n"   ".....XXXX....."   // 01 E0
  "\n"   "....XXXXXX...."   // 03 F0
  "\n"   "...XXX..XXX..."   // 07 38
  "\n"   "...XX....XX..." , // 06 18

  "y" /* UTF-8 79 - Glyph 90 */

  "\n"   "XX..XXXXXXX..."   // 33 F8
  "\n"   "XX.XXXXXXXX..."   // 37 F8
  "\n"   "XX.XX........."   // 36 00
  "\n"   "XX.XX........."   // 36 00
  "\n"   "XXXXXXXXXXX..."   // 3F F8
  "\n"   ".XXXXXXXXXX..." , // 1F F8

  "z" /* UTF-8 7A - Glyph 91 */

  "\n"   "...XXX...XX..."   // 07 18
  "\n"   "...XXXX..XX..."   // 07 98
  "\n"   "...XXXXX.XX..."   // 07 D8
  "\n"   "...XX.XXXXX..."   // 06 F8
  "\n"   "...XX..XXXX..."   // 06 78
  "\n"   "...XX...XXX..." , // 06 38

  "{" /* UTF-8 7B - Glyph 92 */

  "\n"   ".......XX....."   // 00 60
  "\n"   "..XXXXXXXXXXX."   // 0F FE
  "\n"   ".XXXXXX.XXXXXX"   // 1F BF
  "\n"   ".XX.........XX"   // 18 03
  "\n"   ".XX.........XX" , // 18 03

  "|" /* UTF-8 7C - Glyph 93 */

  "\n"   ".XXXXXXXXXXXXX"   // 1F FF
  "\n"   ".XXXXXXXXXXXXX" , // 1F FF

  "}" /* UTF-8 7D - Glyph 94 */

  "\n"   ".XX.........XX"   // 18 03
  "\n"   ".XX.........XX"   // 18 03
  "\n"   ".XXXXXX.XXXXXX"   // 1F BF
  "\n"   "..XXXXXXXXXXX."   // 0F FE
  "\n"   ".......XX....." , // 00 60

  "~" /* UTF-8 7E - Glyph 95 */

  "\n"   "......XX......"   // 00 C0
  "\n"   "......XXX....."   // 00 E0
  "\n"   ".......XX....."   // 00 60
  "\n"   ".......XX....."   // 00 60
  "\n"   ".......XXX...."   // 00 70
  "\n"   "........XX...." , // 00 30

  nullptr // terminator
};

// MARK: - end of generated font verification data


#endif // GENERATE_FONT_SOURCE


// MARK: - 'm6x11' generated font data

static const glyph_t font_m6x11_glyphs[] = {
  {  5, "\x3f\xff\x20\x01\x20\x01\x20\x01\x3f\xff" },  // placeholder          (input # 81 -> glyph # 0)
  {  5, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" },  // ' ' UTF-8 20         (input # 0 -> glyph # 1)
  {  2, "\x06\xff\x06\xff"                         },  // '!' UTF-8 21         (input # 1 -> glyph # 2)
  {  5, "\x00\x03\x00\x07\x00\x00\x00\x03\x00\x07" },  // '"' UTF-8 22         (input # 2 -> glyph # 3)
  {  7, "\x00\xd8\x07\xff\x07\xff\x00\xd8\x07\xff\x07\xff\x00\xd8" },  // '#' UTF-8 23         (input # 3 -> glyph # 4)
  {  6, "\x03\x38\x03\x7c\x0f\x6f\x0f\x6f\x03\xec\x01\xcc" },  // '$' UTF-8 24         (input # 4 -> glyph # 5)
  {  6, "\x01\x8c\x01\xcc\x00\xe0\x00\x70\x03\x38\x03\x18" },  // '%' UTF-8 25         (input # 5 -> glyph # 6)
  {  9, "\x03\xe0\x07\xfe\x06\x3f\x06\x73\x07\xf3\x03\xff\x07\xde\x06\xe0\x06\x60" },  // '&' UTF-8 26         (input # 6 -> glyph # 7)
  {  2, "\x00\x03\x00\x07"                         },  // ''' UTF-8 27         (input # 7 -> glyph # 8)
  {  4, "\x0f\xfe\x1f\xff\x18\x03\x18\x03"         },  // '(' UTF-8 28         (input # 8 -> glyph # 9)
  {  4, "\x18\x03\x18\x03\x1f\xff\x0f\xfe"         },  // ')' UTF-8 29         (input # 9 -> glyph # 10)
  {  5, "\x00\x1b\x00\x1f\x00\x0e\x00\x1f\x00\x1b" },  // '*' UTF-8 2A         (input # 10 -> glyph # 11)
  {  6, "\x00\x60\x00\x60\x01\xf8\x01\xf8\x00\x60\x00\x60" },  // '+' UTF-8 2B         (input # 11 -> glyph # 12)
  {  2, "\x06\x00\x0e\x00"                         },  // ',' UTF-8 2C         (input # 12 -> glyph # 13)
  {  6, "\x00\x60\x00\x60\x00\x60\x00\x60\x00\x60\x00\x60" },  // '-' UTF-8 2D         (input # 13 -> glyph # 14)
  {  2, "\x06\x00\x06\x00"                         },  // '.' UTF-8 2E         (input # 14 -> glyph # 15)
  {  6, "\x07\x00\x07\xc0\x01\xf0\x00\x7c\x00\x1f\x00\x07" },  // '/' UTF-8 2F         (input # 15 -> glyph # 16)
  {  6, "\x03\xfe\x07\xff\x06\x03\x06\x03\x07\xff\x03\xfe" },  // '0' UTF-8 30         (input # 16 -> glyph # 17)
  {  6, "\x06\x06\x06\x06\x07\xff\x07\xff\x06\x00\x06\x00" },  // '1' UTF-8 31         (input # 17 -> glyph # 18)
  {  6, "\x07\x06\x07\x87\x07\xc3\x06\xe3\x06\x7f\x06\x3e" },  // '2' UTF-8 32         (input # 18 -> glyph # 19)
  {  6, "\x03\x06\x07\x07\x06\x33\x06\x33\x07\xff\x03\xee" },  // '3' UTF-8 33         (input # 19 -> glyph # 20)
  {  6, "\x00\x3f\x00\x7f\x00\x60\x00\x60\x07\xff\x07\xff" },  // '4' UTF-8 34         (input # 20 -> glyph # 21)
  {  6, "\x06\x3f\x06\x3f\x06\x33\x06\x33\x07\xf3\x03\xe3" },  // '5' UTF-8 35         (input # 21 -> glyph # 22)
  {  6, "\x03\xfe\x07\xff\x06\x33\x06\x33\x07\xf7\x03\xe6" },  // '6' UTF-8 36         (input # 22 -> glyph # 23)
  {  6, "\x00\x03\x00\x03\x07\xc3\x07\xf3\x00\x7f\x00\x1f" },  // '7' UTF-8 37         (input # 23 -> glyph # 24)
  {  6, "\x03\xee\x07\xff\x06\x33\x06\x33\x07\xff\x03\xee" },  // '8' UTF-8 38         (input # 24 -> glyph # 25)
  {  6, "\x03\x3e\x07\x7f\x06\x63\x06\x63\x07\xff\x03\xfe" },  // '9' UTF-8 39         (input # 25 -> glyph # 26)
  {  2, "\x06\x18\x06\x18"                         },  // ':' UTF-8 3A         (input # 26 -> glyph # 27)
  {  2, "\x06\x18\x0e\x18"                         },  // ';' UTF-8 3B         (input # 27 -> glyph # 28)
  {  5, "\x00\xc0\x01\xe0\x03\xf0\x07\x38\x06\x18" },  // '<' UTF-8 3C         (input # 28 -> glyph # 29)
  {  6, "\x01\x98\x01\x98\x01\x98\x01\x98\x01\x98\x01\x98" },  // '=' UTF-8 3D         (input # 29 -> glyph # 30)
  {  5, "\x06\x18\x07\x38\x03\xf0\x01\xe0\x00\xc0" },  // '>' UTF-8 3E         (input # 30 -> glyph # 31)
  {  6, "\x00\x06\x00\x07\x06\xe3\x06\xf3\x00\x3f\x00\x1e" },  // '?' UTF-8 3F         (input # 31 -> glyph # 32)
  {  9, "\x01\xfc\x03\xfe\x07\x07\x06\x73\x06\xfb\x06\xdb\x06\xff\x06\xfe\x06\x7c" },  // '@' UTF-8 40         (input # 32 -> glyph # 33)
  {  6, "\x07\xfe\x07\xff\x00\x63\x00\x63\x07\xff\x07\xfe" },  // 'A' UTF-8 41         (input # 33 -> glyph # 34)
  {  6, "\x07\xff\x07\xff\x06\x33\x06\x33\x07\xff\x03\xde" },  // 'B' UTF-8 42         (input # 34 -> glyph # 35)
  {  6, "\x03\xfe\x07\xff\x06\x03\x06\x03\x06\x03\x06\x03" },  // 'C' UTF-8 43         (input # 35 -> glyph # 36)
  {  6, "\x07\xff\x07\xff\x06\x03\x06\x03\x07\xff\x03\xfe" },  // 'D' UTF-8 44         (input # 36 -> glyph # 37)
  {  6, "\x03\xfe\x07\xff\x06\x33\x06\x33\x06\x33\x06\x03" },  // 'E' UTF-8 45         (input # 37 -> glyph # 38)
  {  6, "\x07\xfe\x07\xff\x00\x33\x00\x33\x00\x33\x00\x03" },  // 'F' UTF-8 46         (input # 38 -> glyph # 39)
  {  6, "\x03\xfe\x07\xff\x06\x03\x06\x33\x07\xf3\x03\xf3" },  // 'G' UTF-8 47         (input # 39 -> glyph # 40)
  {  6, "\x07\xff\x07\xff\x00\x30\x00\x30\x07\xff\x07\xff" },  // 'H' UTF-8 48         (input # 40 -> glyph # 41)
  {  6, "\x06\x03\x06\x03\x07\xff\x07\xff\x06\x03\x06\x03" },  // 'I' UTF-8 49         (input # 41 -> glyph # 42)
  {  6, "\x03\x03\x07\x03\x06\x03\x06\x03\x07\xff\x03\xff" },  // 'J' UTF-8 4A         (input # 42 -> glyph # 43)
  {  6, "\x07\xff\x07\xff\x00\x70\x00\xf8\x07\xdf\x07\x8f" },  // 'K' UTF-8 4B         (input # 43 -> glyph # 44)
  {  6, "\x03\xff\x07\xff\x06\x00\x06\x00\x06\x00\x06\x00" },  // 'L' UTF-8 4C         (input # 44 -> glyph # 45)
  {  8, "\x07\xff\x07\xff\x00\x03\x01\xff\x01\xff\x00\x03\x07\xff\x07\xfe" },  // 'M' UTF-8 4D         (input # 45 -> glyph # 46)
  {  6, "\x07\xff\x07\xff\x00\x03\x00\x03\x07\xff\x07\xfe" },  // 'N' UTF-8 4E         (input # 46 -> glyph # 47)
  {  6, "\x03\xfe\x07\xff\x06\x03\x06\x03\x07\xff\x03\xfe" },  // 'O' UTF-8 4F         (input # 47 -> glyph # 48)
  {  6, "\x07\xff\x07\xff\x00\x63\x00\x63\x00\x7f\x00\x3e" },  // 'P' UTF-8 50         (input # 48 -> glyph # 49)
  {  7, "\x03\xfe\x07\xff\x06\x03\x07\x03\x03\xff\x07\xfe\x06\x00" },  // 'Q' UTF-8 51         (input # 49 -> glyph # 50)
  {  6, "\x07\xff\x07\xff\x00\x33\x00\x73\x07\xff\x07\xde" },  // 'R' UTF-8 52         (input # 50 -> glyph # 51)
  {  6, "\x06\x1e\x06\x3f\x06\x33\x06\x33\x07\xf3\x03\xe3" },  // 'S' UTF-8 53         (input # 51 -> glyph # 52)
  {  6, "\x00\x03\x00\x03\x07\xff\x07\xff\x00\x03\x00\x03" },  // 'T' UTF-8 54         (input # 52 -> glyph # 53)
  {  6, "\x03\xff\x07\xff\x06\x00\x06\x00\x07\xff\x03\xff" },  // 'U' UTF-8 55         (input # 53 -> glyph # 54)
  {  6, "\x01\xff\x03\xff\x07\x00\x07\x00\x03\xff\x01\xff" },  // 'V' UTF-8 56         (input # 54 -> glyph # 55)
  {  8, "\x03\xff\x07\xff\x06\x00\x07\xf0\x07\xf0\x06\x00\x07\xff\x03\xff" },  // 'W' UTF-8 57         (input # 55 -> glyph # 56)
  {  7, "\x07\x8f\x07\xdf\x00\xf8\x00\x70\x00\xf8\x07\xdf\x07\x8f" },  // 'X' UTF-8 58         (input # 56 -> glyph # 57)
  {  6, "\x00\x1f\x00\x3f\x07\xf0\x07\xf0\x00\x3f\x00\x1f" },  // 'Y' UTF-8 59         (input # 57 -> glyph # 58)
  {  6, "\x07\x03\x07\xc3\x07\xf3\x06\x7f\x06\x1f\x06\x07" },  // 'Z' UTF-8 5A         (input # 58 -> glyph # 59)
  {  4, "\x1f\xff\x1f\xff\x18\x03\x18\x03"         },  // '[' UTF-8 5B         (input # 59 -> glyph # 60)
  {  6, "\x00\x07\x00\x1f\x00\x7c\x01\xf0\x07\xc0\x07\x00" },  // '\' UTF-8 5C         (input # 60 -> glyph # 61)
  {  4, "\x18\x03\x18\x03\x1f\xff\x1f\xff"         },  // ']' UTF-8 5D         (input # 61 -> glyph # 62)
  {  6, "\x00\x0c\x00\x0e\x00\x07\x00\x07\x00\x0e\x00\x0c" },  // '^' UTF-8 5E         (input # 62 -> glyph # 63)
  {  6, "\x06\x00\x06\x00\x06\x00\x06\x00\x06\x00\x06\x00" },  // '_' UTF-8 5F         (input # 63 -> glyph # 64)
  {  2, "\x00\x03\x00\x07"                         },  // '`' UTF-8 60         (input # 64 -> glyph # 65)
  {  6, "\x03\x98\x07\xd8\x06\xd8\x06\xd8\x07\xf8\x07\xf0" },  // 'a' UTF-8 61         (input # 65 -> glyph # 66)
  {  6, "\x07\xff\x07\xff\x06\x18\x06\x18\x07\xf8\x03\xf0" },  // 'b' UTF-8 62         (input # 66 -> glyph # 67)
  {  6, "\x03\xf0\x07\xf8\x06\x18\x06\x18\x06\x18\x06\x18" },  // 'c' UTF-8 63         (input # 67 -> glyph # 68)
  {  6, "\x03\xf0\x07\xf8\x06\x18\x06\x18\x07\xff\x07\xff" },  // 'd' UTF-8 64         (input # 68 -> glyph # 69)
  {  6, "\x03\xf0\x07\xf8\x06\xd8\x06\xd8\x06\xf8\x06\xf0" },  // 'e' UTF-8 65         (input # 69 -> glyph # 70)
  {  6, "\x00\x18\x07\xfe\x07\xff\x00\x1b\x00\x1b\x00\x03" },  // 'f' UTF-8 66         (input # 70 -> glyph # 71)
  {  6, "\x33\xf0\x37\xf8\x36\x18\x36\x18\x3f\xf8\x1f\xf0" },  // 'g' UTF-8 67         (input # 71 -> glyph # 72)
  {  6, "\x07\xff\x07\xff\x00\x18\x00\x18\x07\xf8\x07\xf0" },  // 'h' UTF-8 68         (input # 72 -> glyph # 73)
  {  2, "\x07\xfb\x07\xfb"                         },  // 'i' UTF-8 69         (input # 73 -> glyph # 74)
  {  4, "\x30\x00\x30\x00\x3f\xfb\x1f\xfb"         },  // 'j' UTF-8 6A         (input # 74 -> glyph # 75)
  {  6, "\x07\xff\x07\xff\x00\xd8\x01\xd8\x07\xf8\x07\x70" },  // 'k' UTF-8 6B         (input # 75 -> glyph # 76)
  {  2, "\x07\xff\x07\xff"                         },  // 'l' UTF-8 6C         (input # 76 -> glyph # 77)
  {  8, "\x07\xf8\x07\xf8\x00\x18\x07\xf8\x07\xf8\x00\x18\x07\xf8\x07\xf0" },  // 'm' UTF-8 6D         (input # 77 -> glyph # 78)
  {  6, "\x07\xf8\x07\xf8\x00\x18\x00\x18\x07\xf8\x07\xf0" },  // 'n' UTF-8 6E         (input # 78 -> glyph # 79)
  {  6, "\x03\xf0\x07\xf8\x06\x18\x06\x18\x07\xf8\x03\xf0" },  // 'o' UTF-8 6F         (input # 79 -> glyph # 80)
  {  6, "\x3f\xf0\x3f\xf8\x06\x18\x06\x18\x07\xf8\x03\xf0" },  // 'p' UTF-8 70         (input # 80 -> glyph # 81)
  {  6, "\x03\xf0\x07\xf8\x06\x18\x06\x18\x3f\xf8\x3f\xf0" },  // 'q' UTF-8 71         (input # 82 -> glyph # 82)
  {  6, "\x07\xf8\x07\xf8\x00\x30\x00\x18\x00\x18\x00\x18" },  // 'r' UTF-8 72         (input # 83 -> glyph # 83)
  {  6, "\x06\x70\x06\xf8\x06\xd8\x06\xd8\x07\xd8\x03\x98" },  // 's' UTF-8 73         (input # 84 -> glyph # 84)
  {  6, "\x00\x18\x03\xff\x07\xff\x06\x18\x06\x18\x06\x18" },  // 't' UTF-8 74         (input # 85 -> glyph # 85)
  {  6, "\x03\xf8\x07\xf8\x06\x00\x06\x00\x07\xf8\x03\xf8" },  // 'u' UTF-8 75         (input # 86 -> glyph # 86)
  {  6, "\x01\xf8\x03\xf8\x07\x00\x07\x00\x03\xf8\x01\xf8" },  // 'v' UTF-8 76         (input # 87 -> glyph # 87)
  {  8, "\x03\xf8\x07\xf8\x06\x00\x07\xf0\x07\xf0\x06\x00\x07\xf8\x03\xf8" },  // 'w' UTF-8 77         (input # 88 -> glyph # 88)
  {  7, "\x06\x18\x07\x38\x03\xf0\x01\xe0\x03\xf0\x07\x38\x06\x18" },  // 'x' UTF-8 78         (input # 89 -> glyph # 89)
  {  6, "\x33\xf8\x37\xf8\x36\x00\x36\x00\x3f\xf8\x1f\xf8" },  // 'y' UTF-8 79         (input # 90 -> glyph # 90)
  {  6, "\x07\x18\x07\x98\x07\xd8\x06\xf8\x06\x78\x06\x38" },  // 'z' UTF-8 7A         (input # 91 -> glyph # 91)
  {  5, "\x00\x60\x0f\xfe\x1f\xbf\x18\x03\x18\x03" },  // '{' UTF-8 7B         (input # 92 -> glyph # 92)
  {  2, "\x1f\xff\x1f\xff"                         },  // '|' UTF-8 7C         (input # 93 -> glyph # 93)
  {  5, "\x18\x03\x18\x03\x1f\xbf\x0f\xfe\x00\x60" },  // '}' UTF-8 7D         (input # 94 -> glyph # 94)
  {  6, "\x00\xc0\x00\xe0\x00\x60\x00\x60\x00\x70\x00\x30" },  // '~' UTF-8 7E         (input # 95 -> glyph # 95)
};

static const GlyphRange font_m6x11_ranges[] = {
  { "", 0x20, 0x7E, 1 }, //  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
  { NULL, 0, 0, 0 }
};

static const font_t font_m6x11 = {
  .fontName = "m6x11",
  .glyphHeight = 14,
  .numGlyphs = 96,
  .glyphRanges = font_m6x11_ranges,
  .glyphs = font_m6x11_glyphs
   #ifdef GENERATE_FONT_SOURCE
   , .glyphstrings = font_m6x11_glyphstrings
   #endif
};

static BuiltinFontRegistrar r(font_m6x11);

// MARK: - end of generated font data

